/*
 * Source code generated by UnvUS.
 * Copyright(c) 2017 unvus.com All rights reserved.
 * Template skrull-pack-mybatis:src/main/java/service/Service.e.vm.java
 * Template is part of project: https://git.unvus.com/unvus/opensource/pack-unvus-mybatis
 */
package com.neofect.gts.core.services.sm.service;

import java.util.List;
import java.util.Map;

import org.springframework.stereotype.Service;
import org.springframework.transaction.annotation.Transactional;

import com.neofect.gts.core.services.sm.domain.SmCommFile;
import com.neofect.gts.core.services.sm.repository.SmCommFileRepository;
import com.unvus.config.mybatis.pagination.OrderBy;
import com.unvus.query.QueryTool;


/**
 * Service for {@link SmCommFile}<br/>
 */
@Service
public class SmCommFileService {

    private final SmCommFileRepository smCommFileRepository;

    public SmCommFileService(SmCommFileRepository smCommFileRepository) {
        this.smCommFileRepository = smCommFileRepository;
    }

    //region ------------------------------------------------------------------------------------------------ smCommFile CRUD

    @Transactional
    public SmCommFile saveSmCommFile(SmCommFile smCommFile) {
        if (smCommFile.getId() == null) {
            addSmCommFile(smCommFile);
        } else {
            modifySmCommFile(smCommFile);
        }

        return smCommFile;
    }

    private int addSmCommFile(SmCommFile smCommFile) {
        int result = smCommFileRepository.insertSmCommFile(smCommFile);
        return result;
    }

    private int modifySmCommFile(SmCommFile smCommFile) {
        int result = smCommFileRepository.updateSmCommFile(smCommFile);
        return result;
    }

    @Transactional
    public int removeSmCommFile(Long id) {
        int rows = smCommFileRepository.deleteSmCommFile(id);
        return rows;
    }

    public SmCommFile getSmCommFile(Long id) {
        SmCommFile smCommFile = smCommFileRepository.getSmCommFile(id);

        return smCommFile;
    }

    public int listSmCommFileCnt(Map<String, Object> params) {
        int rows = smCommFileRepository.listSmCommFileCnt(params);
        return rows;
    }

    public List<SmCommFile> listSmCommFile(Map<String, Object> params) {
        List<SmCommFile> lists = smCommFileRepository.listSmCommFile(params);

        return lists;
    }

    public List<SmCommFile> listSmCommFileByIds(List<Long> ids, Map<String, Object> params) {
        params.put("ids", ids);
        QueryTool.setDefaultOrderBy(new OrderBy("ATCH_FILE_ID", ids));
        List<SmCommFile> lists = smCommFileRepository.listSmCommFile(params);

        return lists;
    }

    //endregion

}
