/*
 * Source code generated by UnvUS.
 * Copyright(c) 2017 unvus.com All rights reserved.
 * Template skrull-pack-mybatis:src/main/java/service/Service.e.vm.java
 * Template is part of project: https://git.unvus.com/unvus/opensource/pack-unvus-mybatis
 */
package com.neofect.gts.core.services.sm.service;

import java.util.List;
import java.util.Map;

import org.springframework.stereotype.Service;
import org.springframework.transaction.annotation.Transactional;

import com.neofect.gts.core.services.sm.domain.SmComcodeH;
import com.neofect.gts.core.services.sm.repository.SmComcodeHRepository;
import com.unvus.config.mybatis.pagination.OrderBy;
import com.unvus.query.QueryTool;


/**
 * Service for {@link SmComcodeH}<br/>
 */
@Service
public class SmComcodeHService {

    private final SmComcodeHRepository smComcodeHRepository;

    public SmComcodeHService(SmComcodeHRepository smComcodeHRepository) {
        this.smComcodeHRepository = smComcodeHRepository;
    }

    //region ------------------------------------------------------------------------------------------------ smComcodeH CRUD

    @Transactional
    public SmComcodeH saveSmComcodeH(SmComcodeH smComcodeH) {
        // if (smComcodeH.getId() == null) {
        //     addSmComcodeH(smComcodeH);
        // } else {
        //     modifySmComcodeH(smComcodeH);
        // }

        return smComcodeH;
    }

    private int addSmComcodeH(SmComcodeH smComcodeH) {
        int result = smComcodeHRepository.insertSmComcodeH(smComcodeH);
        return result;
    }

    private int modifySmComcodeH(SmComcodeH smComcodeH) {
        int result = smComcodeHRepository.updateSmComcodeH(smComcodeH);
        return result;
    }

    @Transactional
    public int removeSmComcodeH(Long id) {
        int rows = smComcodeHRepository.deleteSmComcodeH(id);
        return rows;
    }

    public SmComcodeH getSmComcodeH(Long id) {
        SmComcodeH smComcodeH = smComcodeHRepository.getSmComcodeH(id);

        return smComcodeH;
    }

    public int listSmComcodeHCnt(Map<String, Object> params) {
        int rows = smComcodeHRepository.listSmComcodeHCnt(params);
        return rows;
    }

    public List<SmComcodeH> listSmComcodeH(Map<String, Object> params) {
        List<SmComcodeH> lists = smComcodeHRepository.listSmComcodeH(params);

        return lists;
    }

    public List<SmComcodeH> listSmComcodeHByIds(List<Long> ids, Map<String, Object> params) {
        params.put("ids", ids);
        QueryTool.setDefaultOrderBy(new OrderBy("SYS_ID", ids));
        QueryTool.setDefaultOrderBy(new OrderBy("HCODE", ids));
        List<SmComcodeH> lists = smComcodeHRepository.listSmComcodeH(params);

        return lists;
    }

    //endregion

}
