/*
 * Source code generated by UnvUS.
 * Copyright(c) 2017 unvus.com All rights reserved.
 * Template skrull-pack-mybatis:src/main/java/service/Service.e.vm.java
 * Template is part of project: https://git.unvus.com/unvus/opensource/pack-unvus-mybatis
 */
package com.neofect.gts.core.services.sm.service;

import java.util.List;
import java.util.Map;

import org.springframework.stereotype.Service;
import org.springframework.transaction.annotation.Transactional;

import com.neofect.gts.core.services.sm.domain.SumPl;
import com.neofect.gts.core.services.sm.repository.SumPlRepository;
import com.unvus.config.mybatis.pagination.OrderBy;
import com.unvus.query.QueryTool;


/**
 * Service for {@link SumPl}<br/>
 */
@Service
public class SumPlService {

    private final SumPlRepository sumPlRepository;

    public SumPlService(SumPlRepository sumPlRepository) {
        this.sumPlRepository = sumPlRepository;
    }

    //region ------------------------------------------------------------------------------------------------ sumPl CRUD

    @Transactional
    public SumPl saveSumPl(SumPl sumPl) {
        // if (sumPl.getId() == null) {
        //     addSumPl(sumPl);
        // } else {
        //     modifySumPl(sumPl);
        // }

        return sumPl;
    }

    private int addSumPl(SumPl sumPl) {
        int result = sumPlRepository.insertSumPl(sumPl);
        return result;
    }

    private int modifySumPl(SumPl sumPl) {
        int result = sumPlRepository.updateSumPl(sumPl);
        return result;
    }

    @Transactional
    public int removeSumPl(Long id) {
        int rows = sumPlRepository.deleteSumPl(id);
        return rows;
    }

    public SumPl getSumPl(Long id) {
        SumPl sumPl = sumPlRepository.getSumPl(id);

        return sumPl;
    }

    public int listSumPlCnt(Map<String, Object> params) {
        int rows = sumPlRepository.listSumPlCnt(params);
        return rows;
    }

    public List<SumPl> listSumPl(Map<String, Object> params) {
        List<SumPl> lists = sumPlRepository.listSumPl(params);

        return lists;
    }

    public List<SumPl> listSumPlByIds(List<Long> ids, Map<String, Object> params) {
        params.put("ids", ids);
        QueryTool.setDefaultOrderBy(new OrderBy("DEPT_ID", ids));
        QueryTool.setDefaultOrderBy(new OrderBy("YYYYMM", ids));
        QueryTool.setDefaultOrderBy(new OrderBy("ITEM_CODE", ids));
        QueryTool.setDefaultOrderBy(new OrderBy("PL_TYPE", ids));
        QueryTool.setDefaultOrderBy(new OrderBy("STATUS", ids));
        List<SumPl> lists = sumPlRepository.listSumPl(params);

        return lists;
    }

    //endregion

}
