/*
 * Source code generated by UnvUS.
 * Copyright(c) 2017 unvus.com All rights reserved.
 * Template skrull-pack-mybatis:src/main/java/domain/EntityBase.e.vm.java
 * Template is part of project: https://git.unvus.com/unvus/opensource/pack-unvus-mybatis
 */
package com.neofect.gts.core.services.zp.domain;

import java.io.Serializable;
import java.time.LocalDateTime;
import java.util.HashMap;
import java.util.Map;

import org.apache.ibatis.type.Alias;

import lombok.Data;

/**
 * @see com.neofect.gts.core.services.zp.domain.ZDwoconfig
 */
@Alias("zp_zDwoconfig_")
@Data
public abstract class ZDwoconfig_ implements Serializable {

    private static final long serialVersionUID = 1L;

    // Raw attributes
    protected String syscode;
    protected String dwname;
    protected String pbdurl;
    protected LocalDateTime changedate;
    protected String argtype;
    protected String argname;
    protected String sql1;
    protected String sql2;
    protected String sql3;
    protected String sql4;
    protected String sql5;
    protected String sql6;
    protected String sql7;
    protected String sql8;
    protected String sql9;
    protected String sql10;
    protected String sql11;
    protected String sql12;
    protected String sql13;
    protected String sql14;
    protected String sql15;
    protected String sql16;
    protected String sql17;
    protected String sql18;
    protected String sql19;
    protected String sql20;
    protected String sql21;
    protected String sql22;
    protected String sql23;
    protected String sql24;
    protected String sql25;
    protected String remark;
    protected String logYn;
    protected String rowInputEmpNo;
    protected LocalDateTime rowInputDate;
    protected String rowInputIp;
    protected String rowUpdateEmpNo;
    protected String rowUpdateDate;
    protected String rowUpdateIp;

    protected Map<String, Object> _meta = new HashMap();
}
