/*
 * Source code generated by UnvUS.
 * Copyright(c) 2017 unvus.com All rights reserved.
 * Template skrull-pack-mybatis:src/main/java/service/Service.e.vm.java
 * Template is part of project: https://git.unvus.com/unvus/opensource/pack-unvus-mybatis
 */
package com.neofect.gts.core.services.zp.service;

import java.util.List;
import java.util.Map;

import org.springframework.stereotype.Service;
import org.springframework.transaction.annotation.Transactional;

import com.neofect.gts.core.services.zp.domain.ZDwoconfig;
import com.neofect.gts.core.services.zp.repository.ZDwoconfigRepository;
import com.unvus.config.mybatis.pagination.OrderBy;
import com.unvus.query.QueryTool;


/**
 * Service for {@link ZDwoconfig}<br/>
 */
@Service
public class ZDwoconfigService {

    private final ZDwoconfigRepository zDwoconfigRepository;

    public ZDwoconfigService(ZDwoconfigRepository zDwoconfigRepository) {
        this.zDwoconfigRepository = zDwoconfigRepository;
    }

    //region ------------------------------------------------------------------------------------------------ zDwoconfig CRUD

    @Transactional
    public ZDwoconfig saveZDwoconfig(ZDwoconfig zDwoconfig) {
        // if (zDwoconfig.getId() == null) {
        //     addZDwoconfig(zDwoconfig);
        // } else {
        //     modifyZDwoconfig(zDwoconfig);
        // }

        return zDwoconfig;
    }

    private int addZDwoconfig(ZDwoconfig zDwoconfig) {
        int result = zDwoconfigRepository.insertZDwoconfig(zDwoconfig);
        return result;
    }

    private int modifyZDwoconfig(ZDwoconfig zDwoconfig) {
        int result = zDwoconfigRepository.updateZDwoconfig(zDwoconfig);
        return result;
    }

    @Transactional
    public int removeZDwoconfig(Long id) {
        int rows = zDwoconfigRepository.deleteZDwoconfig(id);
        return rows;
    }

    public ZDwoconfig getZDwoconfig(Long id) {
        ZDwoconfig zDwoconfig = zDwoconfigRepository.getZDwoconfig(id);

        return zDwoconfig;
    }

    public int listZDwoconfigCnt(Map<String, Object> params) {
        int rows = zDwoconfigRepository.listZDwoconfigCnt(params);
        return rows;
    }

    public List<ZDwoconfig> listZDwoconfig(Map<String, Object> params) {
        List<ZDwoconfig> lists = zDwoconfigRepository.listZDwoconfig(params);

        return lists;
    }

    public List<ZDwoconfig> listZDwoconfigByIds(List<Long> ids, Map<String, Object> params) {
        params.put("ids", ids);
        QueryTool.setDefaultOrderBy(new OrderBy("SYSCODE", ids));
        QueryTool.setDefaultOrderBy(new OrderBy("DWNAME", ids));
        QueryTool.setDefaultOrderBy(new OrderBy("PBDURL", ids));
        List<ZDwoconfig> lists = zDwoconfigRepository.listZDwoconfig(params);

        return lists;
    }

    //endregion

}
