/*
 * Source code generated by UnvUS.
 * Copyright(c) 2017 unvus.com All rights reserved.
 * Template skrull-pack-mybatis:src/main/java/repository/Repository.e.vm.java
 * Template is part of project: https://git.unvus.com/unvus/opensource/pack-unvus-mybatis
 */
package com.neofect.gts.core.services.user.repository;

import java.util.List;
import java.util.Map;

import com.neofect.gts.core.services.user.domain.User;
import org.springframework.stereotype.Repository;

import com.unvus.config.mybatis.pagination.Pageable;
import com.unvus.config.mybatis.support.DefaultMapper;
import com.neofect.gts.core.services.user.domain.User;

/**
 * Repository for {@link User}<br/>
 * Available methods are.. <br/>
 * <ul>
 * <li>User getUser(Long id);</li>
 * <li>int listUserCnt(Map<String, Object> params);</li>
 * <li>List<User> listUser(Map<String, Object> params);</li>
 * <li>int insertUser(User user);</li>
 * <li>int updateUser(User user);</li>
 * <li>int deleteUser(Long id);</li>
 * </ul>
 */
@DefaultMapper
@Repository
public interface UserRepository extends UserRepository_ {
    User getUser(Long id);

    int listUserCnt(Map<String, Object> params);

    /**
     * if yuou want to avoid result objects less than dataPerPage caused by "1:N mappings".. <br/>
     * add function that return "distinct id list" and name it with : <br/>
     * <code>List<Long> listUserIds(Map<String, Object> params)</code> <br/>
     * and replace @Pageable with :  <br/>
     * <code>@Pageable(useMergeQuery = true)</code> <br/>
     */
    @Pageable
    List<User> listUser(Map<String, Object> params);

    List<Long> listUserIds(Map<String, Object> params);

}
