/*
 * Source code generated by UnvUS.
 * Copyright(c) 2017 unvus.com All rights reserved.
 * Template skrull-pack-mybatis:src/main/java/repository/Repository.e.vm.java
 * Template is part of project: https://git.unvus.com/unvus/opensource/pack-unvus-mybatis
 */
package com.neofect.gts.core.services.xg.repository;

import java.util.List;
import java.util.Map;

import org.springframework.stereotype.Repository;

import com.neofect.gts.core.services.xg.domain.XgSysSvclog;
import com.unvus.config.mybatis.pagination.Pageable;
import com.unvus.config.mybatis.support.DefaultMapper;

/**
 * Repository for {@link XgSysSvclog}<br/>
 * Available methods are.. <br/>
 * <ul>
 * <li>XgSysSvclog getXgSysSvclog(Long id);</li>
 * <li>int listXgSysSvclogCnt(Map<String, Object> params);</li>
 * <li>List<XgSysSvclog> listXgSysSvclog(Map<String, Object> params);</li>
 * <li>int insertXgSysSvclog(XgSysSvclog xgsyssvclog);</li>
 * <li>int updateXgSysSvclog(XgSysSvclog xgsyssvclog);</li>
 * <li>int deleteXgSysSvclog(Long id);</li>
 * </ul>
 */
@DefaultMapper
@Repository
public interface XgSysSvclogRepository extends XgSysSvclogRepository_ {
    XgSysSvclog getXgSysSvclog(Long id);

    int listXgSysSvclogCnt(Map<String, Object> params);

    /**
     * if yuou want to avoid result objects less than dataPerPage caused by "1:N mappings".. <br/>
     * add function that return "distinct id list" and name it with : <br/>
     * <code>List<Long> listXgSysSvclogIds(Map<String, Object> params)</code> <br/>
     * and replace @Pageable with :  <br/>
     * <code>@Pageable(useMergeQuery = true)</code> <br/>
     */
    @Pageable
    List<XgSysSvclog> listXgSysSvclog(Map<String, Object> params);

    List<Long> listXgSysSvclogIds(Map<String, Object> params);

}
