/*
 * Source code generated by UnvUS.
 * Copyright(c) 2017 unvus.com All rights reserved.
 * Template skrull-pack-mybatis:src/main/java/repository/Repository.e.vm.java
 * Template is part of project: https://git.unvus.com/unvus/opensource/pack-unvus-mybatis
 */
package com.neofect.gts.core.services.estorder.repository;

import java.util.List;
import java.util.Map;

import org.springframework.stereotype.Repository;

import com.neofect.gts.core.services.estorder.domain.EstorderMain;
import com.unvus.config.mybatis.pagination.Pageable;
import com.unvus.config.mybatis.support.DefaultMapper;

/**
 * Repository for {@link EstorderMain}<br/>
 * Available methods are.. <br/>
 * <ul>
 * <li>EstorderMain getEstorderMain(Long id);</li>
 * <li>int listEstorderMainCnt(Map<String, Object> params);</li>
 * <li>List<EstorderMain> listEstorderMain(Map<String, Object> params);</li>
 * <li>int insertEstorderMain(EstorderMain estordermain);</li>
 * <li>int updateEstorderMain(EstorderMain estordermain);</li>
 * <li>int deleteEstorderMain(Long id);</li>
 * </ul>
 */
@DefaultMapper
@Repository
public interface EstorderMainRepository extends EstorderMainRepository_ {
    EstorderMain getEstorderMain(Long id);

    int listEstorderMainCnt(Map<String, Object> params);

    /**
     * if yuou want to avoid result objects less than dataPerPage caused by "1:N mappings".. <br/>
     * add function that return "distinct id list" and name it with : <br/>
     * <code>List<Long> listEstorderMainIds(Map<String, Object> params)</code> <br/>
     * and replace @Pageable with :  <br/>
     * <code>@Pageable(useMergeQuery = true)</code> <br/>
     */
    @Pageable
    List<EstorderMain> listEstorderMain(Map<String, Object> params);

    List<Long> listEstorderMainIds(Map<String, Object> params);

}
