/*
 * Source code generated by UnvUS.
 * Copyright(c) 2017 unvus.com All rights reserved.
 * Template skrull-pack-mybatis:src/main/java/service/Service.e.vm.java
 * Template is part of project: https://git.unvus.com/unvus/opensource/pack-unvus-mybatis
 */
package com.neofect.gts.core.services.xg.service;

import java.util.List;
import java.util.Map;

import org.springframework.stereotype.Service;
import org.springframework.transaction.annotation.Transactional;

import com.neofect.gts.core.services.xg.domain.XgComtnLoginlog;
import com.neofect.gts.core.services.xg.repository.XgComtnLoginlogRepository;
import com.unvus.config.mybatis.pagination.OrderBy;
import com.unvus.query.QueryTool;


/**
 * Service for {@link XgComtnLoginlog}<br/>
 */
@Service
public class XgComtnLoginlogService {

    private final XgComtnLoginlogRepository xgComtnLoginlogRepository;

    public XgComtnLoginlogService(XgComtnLoginlogRepository xgComtnLoginlogRepository) {
        this.xgComtnLoginlogRepository = xgComtnLoginlogRepository;
    }

    //region ------------------------------------------------------------------------------------------------ xgComtnLoginlog CRUD

    @Transactional
    public XgComtnLoginlog saveXgComtnLoginlog(XgComtnLoginlog xgComtnLoginlog) {
        // if (xgComtnLoginlog.getId() == null) {
        //     addXgComtnLoginlog(xgComtnLoginlog);
        // } else {
        //     modifyXgComtnLoginlog(xgComtnLoginlog);
        // }

        return xgComtnLoginlog;
    }

    private int addXgComtnLoginlog(XgComtnLoginlog xgComtnLoginlog) {
        int result = xgComtnLoginlogRepository.insertXgComtnLoginlog(xgComtnLoginlog);
        return result;
    }

    private int modifyXgComtnLoginlog(XgComtnLoginlog xgComtnLoginlog) {
        int result = xgComtnLoginlogRepository.updateXgComtnLoginlog(xgComtnLoginlog);
        return result;
    }

    @Transactional
    public int removeXgComtnLoginlog(Long id) {
        int rows = xgComtnLoginlogRepository.deleteXgComtnLoginlog(id);
        return rows;
    }

    public XgComtnLoginlog getXgComtnLoginlog(Long id) {
        XgComtnLoginlog xgComtnLoginlog = xgComtnLoginlogRepository.getXgComtnLoginlog(id);

        return xgComtnLoginlog;
    }

    public int listXgComtnLoginlogCnt(Map<String, Object> params) {
        int rows = xgComtnLoginlogRepository.listXgComtnLoginlogCnt(params);
        return rows;
    }

    public List<XgComtnLoginlog> listXgComtnLoginlog(Map<String, Object> params) {
        List<XgComtnLoginlog> lists = xgComtnLoginlogRepository.listXgComtnLoginlog(params);

        return lists;
    }

    public List<XgComtnLoginlog> listXgComtnLoginlogByIds(List<Long> ids, Map<String, Object> params) {
        params.put("ids", ids);
        QueryTool.setDefaultOrderBy(new OrderBy("COMPANY_CODE", ids));
        QueryTool.setDefaultOrderBy(new OrderBy("LOG_ID", ids));
        List<XgComtnLoginlog> lists = xgComtnLoginlogRepository.listXgComtnLoginlog(params);

        return lists;
    }

    //endregion

}
