/*
 * Source code generated by UnvUS.
 * Copyright(c) 2017 unvus.com All rights reserved.
 * Template skrull-pack-mybatis:src/main/java/repository/Repository.e.vm.java
 * Template is part of project: https://git.unvus.com/unvus/opensource/pack-unvus-mybatis
 */
package com.neofect.gts.core.services.gs.repository;

import java.util.List;
import java.util.Map;

import org.springframework.stereotype.Repository;

import com.neofect.gts.core.services.gs.domain.GsSlipAcnt;
import com.unvus.config.mybatis.pagination.Pageable;
import com.unvus.config.mybatis.support.DefaultMapper;

/**
 * Repository for {@link GsSlipAcnt}<br/>
 * Available methods are.. <br/>
 * <ul>
 * <li>GsSlipAcnt getGsSlipAcnt(Long id);</li>
 * <li>int listGsSlipAcntCnt(Map<String, Object> params);</li>
 * <li>List<GsSlipAcnt> listGsSlipAcnt(Map<String, Object> params);</li>
 * <li>int insertGsSlipAcnt(GsSlipAcnt gsslipacnt);</li>
 * <li>int updateGsSlipAcnt(GsSlipAcnt gsslipacnt);</li>
 * <li>int deleteGsSlipAcnt(Long id);</li>
 * </ul>
 */
@DefaultMapper
@Repository
public interface GsSlipAcntRepository extends GsSlipAcntRepository_ {
    GsSlipAcnt getGsSlipAcnt(Long id);

    int listGsSlipAcntCnt(Map<String, Object> params);

    /**
     * if yuou want to avoid result objects less than dataPerPage caused by "1:N mappings".. <br/>
     * add function that return "distinct id list" and name it with : <br/>
     * <code>List<Long> listGsSlipAcntIds(Map<String, Object> params)</code> <br/>
     * and replace @Pageable with :  <br/>
     * <code>@Pageable(useMergeQuery = true)</code> <br/>
     */
    @Pageable
    List<GsSlipAcnt> listGsSlipAcnt(Map<String, Object> params);

    List<Long> listGsSlipAcntIds(Map<String, Object> params);

}
