/*
 * Source code generated by UnvUS.
 * Copyright(c) 2017 unvus.com All rights reserved.
 * Template skrull-pack-mybatis:src/main/java/domain/EntityBase.e.vm.java
 * Template is part of project: https://git.unvus.com/unvus/opensource/pack-unvus-mybatis
 */
package com.neofect.gts.core.services.sm.domain;

import java.io.Serializable;
import java.time.LocalDateTime;
import java.util.HashMap;
import java.util.Map;

import org.apache.ibatis.type.Alias;

import lombok.Data;

/**
 * @see com.neofect.gts.core.services.sm.domain.SmAuthPgmcode
 */
@Alias("sm_smAuthPgmcode_")
@Data
public abstract class SmAuthPgmcode_ implements Serializable {

    private static final long serialVersionUID = 1L;

    // Raw attributes
    protected String companyCode;
    protected String sysId;
    protected String pgmCode;
    protected String pgmName;
    protected String pgmUrl;
    protected String showYesno;
    protected String movebtnYesno;
    protected String updateYesno;
    protected String retrieveYesno;
    protected String insertYesno;
    protected String appendYesno;
    protected String duplicateYesno;
    protected String deleteYesno;
    protected String printYesno;
    protected String excelYesno;
    protected String closeYesno;
    protected String developedYesno;
    protected String helpYesno;
    protected String remark;
    protected String sortCode;
    protected Integer sortOrder;
    protected String parentSortCode;
    protected Integer menuLevel;
    protected LocalDateTime rowInputDate;
    protected String rowInputIp;
    protected String rowInputEmpNo;
    protected LocalDateTime rowUpdateDate;
    protected String rowUpdateIp;
    protected String rowUpdateEmpNo;
    protected String pageLink;
    protected String pageView;

    protected Map<String, Object> _meta = new HashMap();
}
