/*
 * Source code generated by UnvUS.
 * Copyright(c) 2017 unvus.com All rights reserved.
 * Template skrull-pack-mybatis:src/main/java/domain/EntityBase.e.vm.java
 * Template is part of project: https://git.unvus.com/unvus/opensource/pack-unvus-mybatis
 */
package com.neofect.gts.core.services.sm.domain;

import java.io.Serializable;
import java.time.LocalDateTime;
import java.util.HashMap;
import java.util.Map;

import org.apache.ibatis.type.Alias;

import lombok.Data;

/**
 * @see com.neofect.gts.core.services.sm.domain.SmCodeCust
 */
@Alias("sm_smCodeCust_")
@Data
public abstract class SmCodeCust_ implements Serializable {

    private static final long serialVersionUID = 1L;

    // Raw attributes
    protected String id;
    protected String approveYn;
    protected String useYn;
    protected String custDiv;
    protected String custName;
    protected String custAbbr;
    protected String custEng;
    protected String custLegalNo;
    protected String representName;
    protected String representRrn;
    protected String bizStatus;
    protected String bizType;
    protected String phone;
    protected String fax;
    protected String zipCode;
    protected String addr1;
    protected String addr2;
    protected String custMatching;
    protected String custKind;
    protected String inoutTag;
    protected String partnerTag;
    protected String inputDutyId;
    protected String inputDate;
    protected String chgDutyId;
    protected String chgDate;
    protected String inputCompCode;
    protected String chgCompCode;
    protected String sysId;
    protected String compCode;
    protected String statusCode;
    protected String closingDate;
    protected String rowInputEmpNo;
    protected LocalDateTime rowInputDate;
    protected String rowInputIp;
    protected String rowUpdateEmpNo;
    protected String rowUpdateDate;
    protected String rowUpdateIp;

    protected Map<String, Object> _meta = new HashMap();
}
