/*
 * Source code generated by UnvUS.
 * Copyright(c) 2017 unvus.com All rights reserved.
 * Template skrull-pack-mybatis:src/main/java/domain/EntityBase.e.vm.java
 * Template is part of project: https://git.unvus.com/unvus/opensource/pack-unvus-mybatis
 */
package com.neofect.gts.core.services.sm.domain;

import java.io.Serializable;
import java.math.BigInteger;
import java.time.LocalDateTime;
import java.util.HashMap;
import java.util.Map;

import org.apache.ibatis.type.Alias;

import lombok.Data;

/**
 * @see com.neofect.gts.core.services.sm.domain.SmComcodeH
 */
@Alias("sm_smComcodeH_")
@Data
public abstract class SmComcodeH_ implements Serializable {

    private static final long serialVersionUID = 1L;

    // Raw attributes
    /**
    * 업무코드
    */
    protected String sysId;
    /**
    * 주코드
    */
    protected String hcode;
    /**
    * 주코드명
    */
    protected String hname;
    /**
    * DCODE_SIZE
    */
    protected BigInteger dcodeSize;
    /**
    * HNAME1
    */
    protected String hname1;
    /**
    * 자료TYPE
    */
    protected BigInteger dataType;
    /**
    * 코드SIZE
    */
    protected Integer codeSize;
    /**
    * 명칭SIZE
    */
    protected Integer nameSize;
    /**
    * FLOAT_POS
    */
    protected Integer floatPos;
    /**
    * 테이블명
    */
    protected String tableName;
    /**
    * 코드TYPE
    */
    protected String codeType;
    /**
    * 비고
    */
    protected String rmk;
    /**
    * 작성일시
    */
    protected LocalDateTime rowInputDate;
    /**
    * 작성자
    */
    protected String rowInputEmpNo;
    /**
    * 작성자IP
    */
    protected String rowInputIp;
    /**
    * 수정일시
    */
    protected LocalDateTime rowUpdateDate;
    /**
    * 수정자
    */
    protected String rowUpdateEmpNo;
    /**
    * 수정자IP
    */
    protected String rowUpdateIp;

    protected Map<String, Object> _meta = new HashMap();
}
