/*
 * Source code generated by UnvUS.
 * Copyright(c) 2017 unvus.com All rights reserved.
 * Template skrull-pack-mybatis:src/main/java/domain/EntityBase.e.vm.java
 * Template is part of project: https://git.unvus.com/unvus/opensource/pack-unvus-mybatis
 */
package com.neofect.gts.core.services.sm.domain;

import java.io.Serializable;
import java.math.BigDecimal;
import java.time.LocalDateTime;
import java.util.HashMap;
import java.util.Map;

import org.apache.ibatis.type.Alias;

import lombok.Data;

/**
 * @see com.neofect.gts.core.services.sm.domain.SmComcodeD
 */
@Alias("sm_smComcodeD_")
@Data
public abstract class SmComcodeD_ implements Serializable {

    private static final long serialVersionUID = 1L;

    // Raw attributes
    /**
    * 업무코드
    */
    protected String sysId;
    /**
    * 주코드
    */
    protected String hcode;
    /**
    * 부코드
    */
    protected String dcode;
    /**
    * 부코드명
    */
    protected String dname;
    /**
    * 부코드명1
    */
    protected String dname1;
    /**
    * 부코드명2
    */
    protected String dname2;
    protected String dname3;
    protected String dname4;
    protected String dname5;
    /**
    * 자료값(숫자)
    */
    protected BigDecimal dvalue;
    protected String dvalue1;
    /**
    * 자료값(문자)
    */
    protected String dvalue2;
    protected String dvalue3;
    protected String dvalue4;
    protected String dvalue5;
    protected String hdcode;
    /**
    * 관련코드1
    */
    protected String relateCode1;
    /**
    * 관련코드2
    */
    protected String relateCode2;
    /**
    * 관련코드3
    */
    protected String relateCode3;
    /**
    * 관련코드4
    */
    protected String relateCode4;
    /**
    * 관련코드5
    */
    protected String relateCode5;
    /**
    * 고정코드1
    */
    protected String fixCode1;
    /**
    * 고정코드2
    */
    protected String fixCode2;
    /**
    * 고정코드3
    */
    protected String fixCode3;
    /**
    * 고정코드4
    */
    protected String fixCode4;
    /**
    * 고정코드5
    */
    protected String fixCode5;
    /**
    * SYSTEM_CODE
    */
    protected String systemCode;
    /**
    * CODE_TYPE
    */
    protected String codeType;
    /**
    * 사용여부
    */
    protected String useYn;
    /**
    * CODE_GU
    */
    protected String codeGu;
    /**
    * 비고
    */
    protected String rmk;
    /**
    * 건설부문여부
    */
    protected String conDiv;
    /**
    * 작성일시
    */
    protected LocalDateTime rowInputDate;
    /**
    * 작성자
    */
    protected String rowInputEmpNo;
    /**
    * 작성자IP
    */
    protected String rowInputIp;
    /**
    * 수정일시
    */
    protected LocalDateTime rowUpdateDate;
    /**
    * 수정자
    */
    protected String rowUpdateEmpNo;
    /**
    * 수정자IP
    */
    protected String rowUpdateIp;

    protected Map<String, Object> _meta = new HashMap();
}
