/*
 * Source code generated by UnvUS.
 * Copyright(c) 2017 unvus.com All rights reserved.
 * Template skrull-pack-mybatis:src/main/java/domain/FieldBase.e.vm.java
 * Template is part of project: https://git.unvus.com/unvus/opensource/pack-unvus-mybatis
 */
package com.neofect.gts.core.services.site.domain.query.field;

import java.util.HashMap;
import java.util.Map;

import com.unvus.query.FieldUtil;
import com.unvus.query.frag.Field;

public interface TermField_ {

    Map<String, Field> _FIELD_MAP = new HashMap<String, Field>() {
        {
            FieldUtil.toMap(this, new Field("id", "term_code"));
            FieldUtil.toMap(this, new Field("revision", "term_revision"));
            FieldUtil.toMap(this, new Field("deleted", "term_deleted"));
            FieldUtil.toMap(this, new Field("createdDt", "term_created_dt"));
            FieldUtil.toMap(this, new Field("createdBy", "term_created_by"));
        }
    };

    String prefix();

    /**
    * 약관코드
    */
    default Field id() {
        return new Field(prefix(), "id", "term_code");
    }

    default Field id(String prefix) {
        return new Field(prefix, "id", "term_code");
    }

    /**
    * 현재 약관리비전
    */
    default Field revision() {
        return new Field(prefix(), "revision", "term_revision");
    }

    default Field revision(String prefix) {
        return new Field(prefix, "revision", "term_revision");
    }

    /**
    * 삭제여부
    */
    default Field deleted() {
        return new Field(prefix(), "deleted", "term_deleted");
    }

    default Field deleted(String prefix) {
        return new Field(prefix, "deleted", "term_deleted");
    }

    /**
    * 등록일시
    */
    default Field createdDt() {
        return new Field(prefix(), "createdDt", "term_created_dt");
    }

    default Field createdDt(String prefix) {
        return new Field(prefix, "createdDt", "term_created_dt");
    }

    /**
    * 등록자
    */
    default Field createdBy() {
        return new Field(prefix(), "createdBy", "term_created_by");
    }

    default Field createdBy(String prefix) {
        return new Field(prefix, "createdBy", "term_created_by");
    }

}
