/*
 * Source code generated by UnvUS.
 * Copyright(c) 2017 unvus.com All rights reserved.
 * Template skrull-pack-mybatis:src/main/java/domain/EntityBase.e.vm.java
 * Template is part of project: https://git.unvus.com/unvus/opensource/pack-unvus-mybatis
 */
package com.neofect.gts.core.services.common.domain;

import java.io.Serializable;
import java.time.LocalDateTime;
import java.util.HashMap;
import java.util.Map;

import org.apache.ibatis.type.Alias;

import lombok.Data;

/**
 * 코드_고객거래처
 */

/**
 * @see com.neofect.gts.core.services.common.domain.CodeCust
 */
@Alias("common_codeCust_")
@Data
public abstract class CodeCust_ implements Serializable {

    private static final long serialVersionUID = 1L;

    // Raw attributes
    /**
    * 고객ID
    */
    protected Integer id;
    /**
    * 매입처, 매출처/일반고객, 지사
    */
    protected String clientDiv;
    /**
    * 지사ID
    */
    protected String deptId;
    /**
    * 주민/사업자번호
    */
    protected String custCode;
    /**
    * 거래처명
    */
    protected String custName;
    /**
    * 주민/법인번호
    */
    protected String bizRegno;
    /**
    * 대표자
    */
    protected String bizOwner;
    /**
    * 업태
    */
    protected String bizUptae;
    /**
    * 업종
    */
    protected String bizUpjong;
    /**
    * 우편번호
    */
    protected String zipCode;
    /**
    * 주소1
    */
    protected String addr1;
    /**
    * 주소2
    */
    protected String addr2;
    /**
    * DM우편번호
    */
    protected String dmZipCode;
    /**
    * DM주소1
    */
    protected String dmAddr1;
    /**
    * DM주소2
    */
    protected String dmAddr2;
    /**
    * 전화번호
    */
    protected String phone;
    /**
    * 팩스번호
    */
    protected String fax;
    /**
    * 핸드폰
    */
    protected String hp;
    /**
    * 이메일
    */
    protected String email;
    /**
    * 담당자성명
    */
    protected String managerName;
    /**
    * 담당자전화
    */
    protected String managerPhone;
    /**
    * 담당자핸드폰
    */
    protected String managerHp;
    /**
    * 부가세별도 부가세포함 영세율
    */
    protected String vatDiv;
    /**
    * 현재미수금
    */
    protected Long remainAmt;
    /**
    * 계좌번호
    */
    protected String depositno;
    /**
    * 은행코드
    */
    protected String bankDiv;
    /**
    * 일반/기초수급대상자
    */
    protected String custGubunDiv;
    /**
    * 1 2 3 등급
    */
    protected String custLevelDiv;
    /**
    * 일반일경우 요율
    */
    protected String appRateDiv;
    /**
    * 일반, 요율7.5% 일때 경로연금지급/의료급여수급권자
    */
    protected String reductionDiv;
    /**
    * 요양인정번호
    */
    protected String manageNo;
    /**
    * 인정유효기간(시작)
    */
    protected LocalDateTime startDate;
    /**
    * 보장기관
    */
    protected String manageOfficeDiv;
    /**
    * 생일
    */
    protected LocalDateTime birthDate;
    /**
    * 양음력
    */
    protected String moonYn;
    /**
    * 결혼기념일
    */
    protected LocalDateTime wedDate;
    /**
    * 접수일
    */
    protected LocalDateTime regDate;
    /**
    * 장애등급
    */
    protected String absenseDiv;
    /**
    * 비고
    */
    protected String remark;
    /**
    * 인정유효기간(종료)
    */
    protected LocalDateTime endDate;
    /**
    * 주소동일여부
    */
    protected String chkAddr;
    protected String depositOwner;
    /**
    * 홈페이지
    */
    protected String homepage;
    protected String rowInputEmpNo;
    protected LocalDateTime rowInputDate;
    protected String rowInputIp;
    protected String rowUpdateEmpNo;
    protected String rowUpdateDate;
    protected String rowUpdateIp;
    /**
    * 요양인정번호여부
    */
    protected String manageYn;
    /**
    * 사용안함
    */
    protected String oldCustCode;
    /**
    * 사용안함
    */
    protected String oldAddr1;
    /**
    * 사용안함
    */
    protected String oldAddr2;
    /**
    * 사용안함
    */
    protected String oldDmAddr1;
    /**
    * 사용안함
    */
    protected String oldDmAddr2;
    /**
    * 사용안함
    */
    protected String oldPhone;
    /**
    * 사용안함
    */
    protected String oldFax;
    /**
    * 사용안함
    */
    protected String oldHp;
    /**
    * 사용안함
    */
    protected String oldEmail;
    /**
    * 사용안함
    */
    protected String oldDepositno;
    /**
    * 주민등록번호
    */
    protected String rrnNo;
    /**
    * 요양인정번호 뒷자리
    */
    protected String manageNo2;
    /**
    * 작성자 사번
    */
    protected String memberId;
    /**
    * 요양인정번호 앞자
    */
    protected String manageNo1;
    /**
    * 보호자 순번
    */
    protected Integer proSeq;
    /**
    * 월한도금액
    */
    protected Integer mLimitAmt;
    /**
    * 본인부담금 한도금액
    */
    protected Integer reqLimitAmt;
    /**
    * 구청 승인금액
    */
    protected Integer officeAmt;
    /**
    * 계약변경일자
    */
    protected LocalDateTime changeDate;
    /**
    * 계약시작일자
    */
    protected LocalDateTime contSdate;
    /**
    * 계약종료일자
    */
    protected LocalDateTime contEdate;
    /**
    * 지로번호
    */
    protected String jiroNo;
    /**
    * 현금영수증 번호
    */
    protected String cashReceiptNo;
    /**
    * 가상계좌1(은행은 공통코드에)
    */
    protected String vdepositNo1;
    /**
    * 가상계좌2(은행은 공통코드에)
    */
    protected String vdepositNo2;
    /**
    * 가상계좌3(은행은 공통코드에)
    */
    protected String vdepositNo3;
    /**
    * 가상계좌4(은행은 공통코드에)
    */
    protected String vdepositNo4;
    /**
    * 가상계좌5(은행은 공통코드에)
    */
    protected String vdepositNo5;
    /**
    * 성별
    */
    protected String sex;
    /**
    * 주요질환
    */
    protected String mainDis;

    protected Map<String, Object> _meta = new HashMap();
}
