/*
 * Source code generated by UnvUS.
 * Copyright(c) 2017 unvus.com All rights reserved.
 * Template skrull-pack-mybatis:src/main/java/domain/EntityBase.e.vm.java
 * Template is part of project: https://git.unvus.com/unvus/opensource/pack-unvus-mybatis
 */
package com.neofect.gts.core.services.common.domain;

import java.io.Serializable;
import java.time.LocalDateTime;
import java.util.HashMap;
import java.util.Map;

import org.apache.ibatis.type.Alias;

import lombok.Data;

/**
 * @see com.neofect.gts.core.services.common.domain.CodeCustindept
 */
@Alias("common_codeCustindept_")
@Data
public abstract class CodeCustindept_ implements Serializable {

    private static final long serialVersionUID = 1L;

    // Raw attributes
    /**
    * 순번
    */
    protected Integer id;
    /**
    * 지사ID
    */
    protected String deptId;
    /**
    * 고객ID
    */
    protected Integer custId;
    protected String rowInputEmpNo;
    protected LocalDateTime rowInputDate;
    protected String rowInputIp;
    protected String rowUpdateEmpNo;
    protected String rowUpdateDate;
    protected String rowUpdateIp;
    /**
    * 비고
    */
    protected String remark;
    /**
    * 현재지사여부
    */
    protected String useYn;

    protected Map<String, Object> _meta = new HashMap();
}
