/*
 * Source code generated by UnvUS.
 * Copyright(c) 2017 unvus.com All rights reserved.
 * Template skrull-pack-mybatis:src/main/java/domain/EntityBase.e.vm.java
 * Template is part of project: https://git.unvus.com/unvus/opensource/pack-unvus-mybatis
 */
package com.neofect.gts.core.services.common.domain;

import java.io.Serializable;
import java.time.LocalDateTime;
import java.util.HashMap;
import java.util.Map;

import org.apache.ibatis.type.Alias;

import lombok.Data;

/**
 * @see com.neofect.gts.core.services.common.domain.CodeCustExcel
 */
@Alias("common_codeCustExcel_")
@Data
public abstract class CodeCustExcel_ implements Serializable {

    private static final long serialVersionUID = 1L;

    // Raw attributes
    protected Integer jobId;
    protected Integer custId;
    protected String jiroNo;
    protected String cashReceiptNo;
    protected String vdepositNo1;
    protected String vdepositNo2;
    protected String vdepositNo3;
    protected String rowInputEmpNo;
    protected LocalDateTime rowInputDate;
    protected String rowInputIp;
    protected String rowUpdateEmpNo;
    protected String rowUpdateDate;
    protected String rowUpdateIp;

    protected Map<String, Object> _meta = new HashMap();
}
