/*
 * Source code generated by UnvUS.
 * Copyright(c) 2017 unvus.com All rights reserved.
 * Template skrull-pack-mybatis:src/main/java/domain/EntityBase.e.vm.java
 * Template is part of project: https://git.unvus.com/unvus/opensource/pack-unvus-mybatis
 */
package com.neofect.gts.core.services.common.domain;

import java.io.Serializable;
import java.time.LocalDateTime;
import java.util.HashMap;
import java.util.Map;

import org.apache.ibatis.type.Alias;

import lombok.Data;

/**
 * 코드_보호자
 */

/**
 * @see com.neofect.gts.core.services.common.domain.CodeCustprotector
 */
@Alias("common_codeCustprotector_")
@Data
public abstract class CodeCustprotector_ implements Serializable {

    private static final long serialVersionUID = 1L;

    // Raw attributes
    /**
    * 고객ID
    */
    protected Integer custId;
    /**
    * 순번
    */
    protected Integer proSeq;
    /**
    * 보호자명
    */
    protected String proName;
    /**
    * 관계
    */
    protected String relationDiv;
    /**
    * 이메일
    */
    protected String email;
    /**
    * 전화번호
    */
    protected String phone;
    /**
    * 핸드폰
    */
    protected String hp;
    /**
    * 우편번호
    */
    protected String zipCode;
    /**
    * 주소1
    */
    protected String addr1;
    /**
    * 주소2
    */
    protected String addr2;
    protected String rowInputEmpNo;
    protected LocalDateTime rowInputDate;
    protected String rowInputIp;
    protected String rowUpdateEmpNo;
    protected String rowUpdateDate;
    protected String rowUpdateIp;
    protected String birthDate;

    protected Map<String, Object> _meta = new HashMap();
}
