/*
 * Source code generated by UnvUS.
 * Copyright(c) 2017 unvus.com All rights reserved.
 * Template skrull-pack-mybatis:src/main/java/domain/EntityBase.e.vm.java
 * Template is part of project: https://git.unvus.com/unvus/opensource/pack-unvus-mybatis
 */
package com.neofect.gts.core.services.common.domain;

import java.io.Serializable;
import java.time.LocalDateTime;
import java.util.HashMap;
import java.util.Map;

import org.apache.ibatis.type.Alias;

import lombok.Data;

/**
 * 코드_요양비용
 */

/**
 * @see com.neofect.gts.core.services.common.domain.CodeCareamt
 */
@Alias("common_codeCareamt_")
@Data
public abstract class CodeCareamt_ implements Serializable {

    private static final long serialVersionUID = 1L;

    // Raw attributes
    /**
    * 요양시설구분
    */
    protected String carefacilityDiv;
    /**
    * 고객등급
    */
    protected String custLevelDiv;
    protected LocalDateTime applyDate;
    /**
    * 월한도액
    */
    protected Long limitAmt;
    /**
    * 일반부담금
    */
    protected Long gPayamt;
    /**
    * 비고
    */
    protected String remark;
    /**
    * 의료급여자부담금(7.5%)
    */
    protected Long mPayamt;
    /**
    * 사용여부
    */
    protected String useYn;
    protected String rowInputEmpNo;
    protected LocalDateTime rowInputDate;
    protected String rowInputIp;
    protected String rowUpdateEmpNo;
    protected String rowUpdateDate;
    protected String rowUpdateIp;
    /**
    * 의료급여(6%)
    */
    protected Long lPayamt;
    /**
    * 의료급여(9%)
    */
    protected Long nPayamt;

    protected Map<String, Object> _meta = new HashMap();
}
