/*
 * Source code generated by UnvUS.
 * Copyright(c) 2017 unvus.com All rights reserved.
 * Template skrull-pack-mybatis:src/main/java/repository/Repository.e.vm.java
 * Template is part of project: https://git.unvus.com/unvus/opensource/pack-unvus-mybatis
 */
package com.neofect.gts.core.services.am.repository;

import java.util.List;
import java.util.Map;

import org.springframework.stereotype.Repository;

import com.neofect.gts.core.services.am.domain.AmCodeItemAsst;
import com.unvus.config.mybatis.pagination.Pageable;
import com.unvus.config.mybatis.support.DefaultMapper;

/**
 * Repository for {@link AmCodeItemAsst}<br/>
 * Available methods are.. <br/>
 * <ul>
 * <li>AmCodeItemAsst getAmCodeItemAsst(Long id);</li>
 * <li>int listAmCodeItemAsstCnt(Map<String, Object> params);</li>
 * <li>List<AmCodeItemAsst> listAmCodeItemAsst(Map<String, Object> params);</li>
 * <li>int insertAmCodeItemAsst(AmCodeItemAsst amcodeitemasst);</li>
 * <li>int updateAmCodeItemAsst(AmCodeItemAsst amcodeitemasst);</li>
 * <li>int deleteAmCodeItemAsst(Long id);</li>
 * </ul>
 */
@DefaultMapper
@Repository
public interface AmCodeItemAsstRepository extends AmCodeItemAsstRepository_ {
    AmCodeItemAsst getAmCodeItemAsst(Long id);

    int listAmCodeItemAsstCnt(Map<String, Object> params);

    /**
     * if yuou want to avoid result objects less than dataPerPage caused by "1:N mappings".. <br/>
     * add function that return "distinct id list" and name it with : <br/>
     * <code>List<Long> listAmCodeItemAsstIds(Map<String, Object> params)</code> <br/>
     * and replace @Pageable with :  <br/>
     * <code>@Pageable(useMergeQuery = true)</code> <br/>
     */
    @Pageable
    List<AmCodeItemAsst> listAmCodeItemAsst(Map<String, Object> params);

    List<Long> listAmCodeItemAsstIds(Map<String, Object> params);

}
