/*
 * Source code generated by UnvUS.
 * Copyright(c) 2017 unvus.com All rights reserved.
 * Template skrull-pack-mybatis:src/main/java/repository/Repository.e.vm.java
 * Template is part of project: https://git.unvus.com/unvus/opensource/pack-unvus-mybatis
 */
package com.neofect.gts.core.services.am.repository;

import java.util.List;
import java.util.Map;

import org.springframework.stereotype.Repository;

import com.neofect.gts.core.services.am.domain.AmCodeAsset;
import com.unvus.config.mybatis.pagination.Pageable;
import com.unvus.config.mybatis.support.DefaultMapper;

/**
 * Repository for {@link AmCodeAsset}<br/>
 * Available methods are.. <br/>
 * <ul>
 * <li>AmCodeAsset getAmCodeAsset(Long id);</li>
 * <li>int listAmCodeAssetCnt(Map<String, Object> params);</li>
 * <li>List<AmCodeAsset> listAmCodeAsset(Map<String, Object> params);</li>
 * <li>int insertAmCodeAsset(AmCodeAsset amcodeasset);</li>
 * <li>int updateAmCodeAsset(AmCodeAsset amcodeasset);</li>
 * <li>int deleteAmCodeAsset(Long id);</li>
 * </ul>
 */
@DefaultMapper
@Repository
public interface AmCodeAssetRepository extends AmCodeAssetRepository_ {
    AmCodeAsset getAmCodeAsset(Long id);

    int listAmCodeAssetCnt(Map<String, Object> params);

    /**
     * if yuou want to avoid result objects less than dataPerPage caused by "1:N mappings".. <br/>
     * add function that return "distinct id list" and name it with : <br/>
     * <code>List<Long> listAmCodeAssetIds(Map<String, Object> params)</code> <br/>
     * and replace @Pageable with :  <br/>
     * <code>@Pageable(useMergeQuery = true)</code> <br/>
     */
    @Pageable
    List<AmCodeAsset> listAmCodeAsset(Map<String, Object> params);

    List<Long> listAmCodeAssetIds(Map<String, Object> params);

}
