/*
 * Source code generated by UnvUS.
 * Copyright(c) 2017 unvus.com All rights reserved.
 * Template skrull-pack-mybatis:src/main/java/repository/Repository.e.vm.java
 * Template is part of project: https://git.unvus.com/unvus/opensource/pack-unvus-mybatis
 */
package com.neofect.gts.core.services.am.repository;

import java.util.List;
import java.util.Map;

import org.springframework.stereotype.Repository;

import com.neofect.gts.core.services.am.domain.AmCodeRate;
import com.unvus.config.mybatis.pagination.Pageable;
import com.unvus.config.mybatis.support.DefaultMapper;

/**
 * Repository for {@link AmCodeRate}<br/>
 * Available methods are.. <br/>
 * <ul>
 * <li>AmCodeRate getAmCodeRate(Long id);</li>
 * <li>int listAmCodeRateCnt(Map<String, Object> params);</li>
 * <li>List<AmCodeRate> listAmCodeRate(Map<String, Object> params);</li>
 * <li>int insertAmCodeRate(AmCodeRate amcoderate);</li>
 * <li>int updateAmCodeRate(AmCodeRate amcoderate);</li>
 * <li>int deleteAmCodeRate(Long id);</li>
 * </ul>
 */
@DefaultMapper
@Repository
public interface AmCodeRateRepository extends AmCodeRateRepository_ {
    AmCodeRate getAmCodeRate(Long id);

    int listAmCodeRateCnt(Map<String, Object> params);

    /**
     * if yuou want to avoid result objects less than dataPerPage caused by "1:N mappings".. <br/>
     * add function that return "distinct id list" and name it with : <br/>
     * <code>List<Long> listAmCodeRateIds(Map<String, Object> params)</code> <br/>
     * and replace @Pageable with :  <br/>
     * <code>@Pageable(useMergeQuery = true)</code> <br/>
     */
    @Pageable
    List<AmCodeRate> listAmCodeRate(Map<String, Object> params);

    List<Long> listAmCodeRateIds(Map<String, Object> params);

}
