/*
 * Source code generated by UnvUS.
 * Copyright(c) 2017 unvus.com All rights reserved.
 * Template skrull-pack-mybatis:src/main/java/repository/Repository.e.vm.java
 * Template is part of project: https://git.unvus.com/unvus/opensource/pack-unvus-mybatis
 */
package com.neofect.gts.core.services.am.repository;

import java.util.List;
import java.util.Map;

import org.springframework.stereotype.Repository;

import com.neofect.gts.core.services.am.domain.AmCodeKind;
import com.unvus.config.mybatis.pagination.Pageable;
import com.unvus.config.mybatis.support.DefaultMapper;

/**
 * Repository for {@link AmCodeKind}<br/>
 * Available methods are.. <br/>
 * <ul>
 * <li>AmCodeKind getAmCodeKind(Long id);</li>
 * <li>int listAmCodeKindCnt(Map<String, Object> params);</li>
 * <li>List<AmCodeKind> listAmCodeKind(Map<String, Object> params);</li>
 * <li>int insertAmCodeKind(AmCodeKind amcodekind);</li>
 * <li>int updateAmCodeKind(AmCodeKind amcodekind);</li>
 * <li>int deleteAmCodeKind(Long id);</li>
 * </ul>
 */
@DefaultMapper
@Repository
public interface AmCodeKindRepository extends AmCodeKindRepository_ {
    AmCodeKind getAmCodeKind(Long id);

    int listAmCodeKindCnt(Map<String, Object> params);

    /**
     * if yuou want to avoid result objects less than dataPerPage caused by "1:N mappings".. <br/>
     * add function that return "distinct id list" and name it with : <br/>
     * <code>List<Long> listAmCodeKindIds(Map<String, Object> params)</code> <br/>
     * and replace @Pageable with :  <br/>
     * <code>@Pageable(useMergeQuery = true)</code> <br/>
     */
    @Pageable
    List<AmCodeKind> listAmCodeKind(Map<String, Object> params);

    List<Long> listAmCodeKindIds(Map<String, Object> params);

}
