/*
 * Source code generated by UnvUS.
 * Copyright(c) 2017 unvus.com All rights reserved.
 * Template skrull-pack-mybatis:src/main/java/repository/Repository.e.vm.java
 * Template is part of project: https://git.unvus.com/unvus/opensource/pack-unvus-mybatis
 */
package com.neofect.gts.core.services.am.repository;

import java.util.List;
import java.util.Map;

import org.springframework.stereotype.Repository;

import com.neofect.gts.core.services.am.domain.AmCodeValidMast;
import com.unvus.config.mybatis.pagination.Pageable;
import com.unvus.config.mybatis.support.DefaultMapper;

/**
 * Repository for {@link AmCodeValidMast}<br/>
 * Available methods are.. <br/>
 * <ul>
 * <li>AmCodeValidMast getAmCodeValidMast(Long id);</li>
 * <li>int listAmCodeValidMastCnt(Map<String, Object> params);</li>
 * <li>List<AmCodeValidMast> listAmCodeValidMast(Map<String, Object> params);</li>
 * <li>int insertAmCodeValidMast(AmCodeValidMast amcodevalidmast);</li>
 * <li>int updateAmCodeValidMast(AmCodeValidMast amcodevalidmast);</li>
 * <li>int deleteAmCodeValidMast(Long id);</li>
 * </ul>
 */
@DefaultMapper
@Repository
public interface AmCodeValidMastRepository extends AmCodeValidMastRepository_ {
    AmCodeValidMast getAmCodeValidMast(Long id);

    int listAmCodeValidMastCnt(Map<String, Object> params);

    /**
     * if yuou want to avoid result objects less than dataPerPage caused by "1:N mappings".. <br/>
     * add function that return "distinct id list" and name it with : <br/>
     * <code>List<Long> listAmCodeValidMastIds(Map<String, Object> params)</code> <br/>
     * and replace @Pageable with :  <br/>
     * <code>@Pageable(useMergeQuery = true)</code> <br/>
     */
    @Pageable
    List<AmCodeValidMast> listAmCodeValidMast(Map<String, Object> params);

    List<Long> listAmCodeValidMastIds(Map<String, Object> params);

}
