/*
 * Source code generated by UnvUS.
 * Copyright(c) 2017 unvus.com All rights reserved.
 * Template skrull-pack-mybatis:src/main/java/rest/Rest.e.vm.java
 * Template is part of project: https://git.unvus.com/unvus/opensource/pack-unvus-mybatis
 */
package com.neofect.gts.web.cms.rest.member;

import java.net.URISyntaxException;
import java.util.HashMap;
import java.util.List;
import java.util.Map;

import org.springframework.http.HttpHeaders;
import org.springframework.http.HttpStatus;
import org.springframework.http.MediaType;
import org.springframework.http.ResponseEntity;
import org.springframework.web.bind.annotation.*;

import com.google.common.collect.ImmutableMap;
import com.neofect.gts.core.services.member.domain.MemberPayment;
import com.neofect.gts.core.services.member.service.MemberPaymentService;
import com.unvus.web.util.PaginationUtil;

import lombok.extern.slf4j.Slf4j;

/**
 * Rest for {@link MemberPayment}<br/>
 */
@Slf4j
@RestController
@RequestMapping("/api")
public class MemberPaymentResource {

    private final MemberPaymentService memberPaymentService;

    public MemberPaymentResource(MemberPaymentService memberPaymentService) {
        this.memberPaymentService = memberPaymentService;
    }

    //region ------------------------------------------------------------------------------------------------ memberPayment API

    /**
     *
     */
    @GetMapping(value = "/member-payment", produces = MediaType.APPLICATION_JSON_VALUE)
    public ResponseEntity<List<MemberPayment>> listMemberPayment(@RequestParam(value = "q", required = false) Map<String, Object> q) throws URISyntaxException {
        if (q == null) {
            q = new HashMap();
        }

        List<MemberPayment> memberPaymentList = memberPaymentService.listMemberPayment(q);

        HttpHeaders headers = PaginationUtil.generatePaginationHttpHeaders();

        return new ResponseEntity<>(memberPaymentList, headers, HttpStatus.OK);
    }

    /**
     * get count
     * @return
     */
    @GetMapping(value = "/member-payment/_count", produces = MediaType.APPLICATION_JSON_VALUE)
    public ResponseEntity<Map> getCount(@RequestParam(value = "q", required = false) Map<String, Object> q) {
        int count = memberPaymentService.listMemberPaymentCnt(q);

        return new ResponseEntity<>(ImmutableMap.of("count", count), HttpStatus.OK);
    }

    /**
     * get empty object
     * @return
     */
    @GetMapping(value = "/member-payment/_empty", produces = MediaType.APPLICATION_JSON_VALUE)
    public ResponseEntity<MemberPayment> getEmptyMemberPayment() {
        MemberPayment memberPayment = new MemberPayment();
        return new ResponseEntity<>(memberPayment, HttpStatus.OK);
    }

    /**
     * get
     */
    @GetMapping(value = "/member-payment/{id}", produces = MediaType.APPLICATION_JSON_VALUE)
    public ResponseEntity<MemberPayment> getMemberPayment(@PathVariable("id") Long id) {
        MemberPayment memberPayment = memberPaymentService.getMemberPayment(id);
        return new ResponseEntity<>(memberPayment, HttpStatus.OK);
    }

    /**
     * add
     */
    @PostMapping("/member-payment")
    public ResponseEntity<Void> addMemberPayment(@RequestBody MemberPayment memberPayment) {
        memberPaymentService.saveMemberPayment(memberPayment);

        return ResponseEntity.ok().build();
    }

    /**
     * modify
     */
    @PutMapping("/member-payment/{id}")
    public ResponseEntity<Void> updateMemberPayment(@PathVariable("id") Long id, @RequestBody MemberPayment memberPayment) throws Exception {
        // if (!id.equals(memberPayment.getId())) {
        //     return new ResponseEntity(HttpStatus.BAD_REQUEST);
        // }
        memberPaymentService.saveMemberPayment(memberPayment);
        return ResponseEntity.ok().build();
    }

    /**
     * delete
     */
    @DeleteMapping("/member-payment/{id}")
    public ResponseEntity<Void> removeMemberPayment(@PathVariable("id") Long id) {
        memberPaymentService.removeMemberPayment(id);
        return ResponseEntity.ok().build();
    }

    //endregion

}
