/*
 * Source code generated by UnvUS.
 * Copyright(c) 2017 unvus.com All rights reserved.
 * Template skrull-pack-mybatis:src/main/java/rest/Rest.e.vm.java
 * Template is part of project: https://git.unvus.com/unvus/opensource/pack-unvus-mybatis
 */
package com.neofect.gts.web.cms.rest.member;

import java.net.URISyntaxException;
import java.util.HashMap;
import java.util.List;
import java.util.Map;

import org.springframework.http.HttpHeaders;
import org.springframework.http.HttpStatus;
import org.springframework.http.MediaType;
import org.springframework.http.ResponseEntity;
import org.springframework.web.bind.annotation.*;

import com.google.common.collect.ImmutableMap;
import com.neofect.gts.core.services.member.domain.MemberVacation;
import com.neofect.gts.core.services.member.service.MemberVacationService;
import com.unvus.web.util.PaginationUtil;

import lombok.extern.slf4j.Slf4j;

/**
 * Rest for {@link MemberVacation}<br/>
 */
@Slf4j
@RestController
@RequestMapping("/api")
public class MemberVacationResource {

    private final MemberVacationService memberVacationService;

    public MemberVacationResource(MemberVacationService memberVacationService) {
        this.memberVacationService = memberVacationService;
    }

    //region ------------------------------------------------------------------------------------------------ memberVacation API

    /**
     *
     */
    @GetMapping(value = "/member-vacation", produces = MediaType.APPLICATION_JSON_VALUE)
    public ResponseEntity<List<MemberVacation>> listMemberVacation(@RequestParam(value = "q", required = false) Map<String, Object> q)
            throws URISyntaxException {
        if (q == null) {
            q = new HashMap();
        }

        List<MemberVacation> memberVacationList = memberVacationService.listMemberVacation(q);

        HttpHeaders headers = PaginationUtil.generatePaginationHttpHeaders();

        return new ResponseEntity<>(memberVacationList, headers, HttpStatus.OK);
    }

    /**
     * get count
     * @return
     */
    @GetMapping(value = "/member-vacation/_count", produces = MediaType.APPLICATION_JSON_VALUE)
    public ResponseEntity<Map> getCount(@RequestParam(value = "q", required = false) Map<String, Object> q) {
        int count = memberVacationService.listMemberVacationCnt(q);

        return new ResponseEntity<>(ImmutableMap.of("count", count), HttpStatus.OK);
    }

    /**
     * get empty object
     * @return
     */
    @GetMapping(value = "/member-vacation/_empty", produces = MediaType.APPLICATION_JSON_VALUE)
    public ResponseEntity<MemberVacation> getEmptyMemberVacation() {
        MemberVacation memberVacation = new MemberVacation();
        return new ResponseEntity<>(memberVacation, HttpStatus.OK);
    }

    /**
     * get
     */
    @GetMapping(value = "/member-vacation/{id}", produces = MediaType.APPLICATION_JSON_VALUE)
    public ResponseEntity<MemberVacation> getMemberVacation(@PathVariable("id") Long id) {
        MemberVacation memberVacation = memberVacationService.getMemberVacation(id);
        return new ResponseEntity<>(memberVacation, HttpStatus.OK);
    }

    /**
     * add
     */
    @PostMapping("/member-vacation")
    public ResponseEntity<Void> addMemberVacation(@RequestBody MemberVacation memberVacation) {
        memberVacationService.saveMemberVacation(memberVacation);

        return ResponseEntity.ok().build();
    }

    /**
     * modify
     */
    @PutMapping("/member-vacation/{id}")
    public ResponseEntity<Void> updateMemberVacation(@PathVariable("id") Long id, @RequestBody MemberVacation memberVacation) throws Exception {
        if (!id.equals(memberVacation.getId())) {
            return new ResponseEntity(HttpStatus.BAD_REQUEST);
        }
        memberVacationService.saveMemberVacation(memberVacation);
        return ResponseEntity.ok().build();
    }

    /**
     * delete
     */
    @DeleteMapping("/member-vacation/{id}")
    public ResponseEntity<Void> removeMemberVacation(@PathVariable("id") Long id) {
        memberVacationService.removeMemberVacation(id);
        return ResponseEntity.ok().build();
    }

    //endregion

}
