/*
 * Source code generated by UnvUS.
 * Copyright(c) 2017 unvus.com All rights reserved.
 * Template skrull-pack-mybatis:src/main/java/repository/RepositoryBase.e.vm.java
 * Template is part of project: https://git.unvus.com/unvus/opensource/pack-unvus-mybatis
 */
package com.neofect.gts.core.services.estorder.repository;

import java.util.List;
import java.util.Map;

import org.springframework.stereotype.Repository;

import com.neofect.gts.core.services.estorder.domain.EstorderDetail;
import com.unvus.config.mybatis.pagination.Pageable;
import com.unvus.config.mybatis.support.DefaultMapper;

/**
 * Repository for {@link EstorderDetail}
 * @see com.neofect.gts.core.services.estorder.repository.EstorderDetailRepository
 */
@DefaultMapper
@Repository
public interface EstorderDetailRepository_ {

    EstorderDetail simpleGetEstorderDetail(Long id);

    int simpleListEstorderDetailCnt(Map<String, Object> params);

    /**
     * if yuou want to avoid result objects less than dataPerPage caused by "1:N mappings".. <br/>
     * add function that return "distinct id list" and name it with : <br/>
     * <code>List<Long> listEstorderDetailIds(Map<String, Object> params)</code> <br/>
     * and replace @Pageable with :  <br/>
     * <code>@Pageable(useMergeQuery = true)</code> <br/>
     */
    @Pageable
    List<EstorderDetail> simpleListEstorderDetail(Map<String, Object> params);

    int insertEstorderDetail(EstorderDetail estorderDetail);

    int updateEstorderDetail(EstorderDetail estorderDetail);

    int updateEstorderDetailDynamic(EstorderDetail estorderDetail);

    int deleteEstorderDetail(Long id);

}
