/*
 * Source code generated by UnvUS.
 * Copyright(c) 2017 unvus.com All rights reserved.
 * Template skrull-pack-mybatis:src/main/java/domain/EntityBase.e.vm.java
 * Template is part of project: https://git.unvus.com/unvus/opensource/pack-unvus-mybatis
 */
package com.neofect.gts.core.services.srvce.domain;

import java.io.Serializable;
import java.time.LocalDateTime;
import java.util.HashMap;
import java.util.Map;

import org.apache.ibatis.type.Alias;

import lombok.Data;

/**
 * @see com.neofect.gts.core.services.srvce.domain.ServicePaySum
 */
@Alias("srvce_servicePaySum_")
@Data
public abstract class ServicePaySum_ implements Serializable {

    private static final long serialVersionUID = 1L;

    // Raw attributes
    /**
    * 지사ID
    */
    protected String deptId;
    /**
    * 고객ID
    */
    protected Integer custId;
    /**
    * 집계년월
    */
    protected String yyyymm;
    /**
    * 본인부담금
    */
    protected Integer payAmt;
    /**
    * 청구금
    */
    protected Integer reqAmt;
    /**
    * 구청청구번호
    */
    protected String reqNo;
    /**
    * 구청청구일자
    */
    protected LocalDateTime reqDate;
    /**
    * 구청반제여부
    */
    protected String reqYn;
    /**
    * 구청반제일자
    */
    protected LocalDateTime reqRedate;
    protected String rowInputEmpNo;
    protected LocalDateTime rowInputDate;
    protected String rowInputIp;
    protected String rowUpdateEmpNo;
    protected String rowUpdateDate;
    protected String rowUpdateIp;
    /**
    * 비급여 금액
    */
    protected Integer bpayAmt;

    protected Map<String, Object> _meta = new HashMap();
}
