/*
 * Source code generated by UnvUS.
 * Copyright(c) 2017 unvus.com All rights reserved.
 * Template skrull-pack-mybatis:src/main/java/domain/FieldBase.e.vm.java
 * Template is part of project: https://git.unvus.com/unvus/opensource/pack-unvus-mybatis
 */
package com.neofect.gts.core.services.common.domain.query.field;

import java.util.HashMap;
import java.util.Map;

import com.unvus.query.FieldUtil;
import com.unvus.query.frag.Field;

public interface ActionLogField_ {

    Map<String, Field> _FIELD_MAP = new HashMap<String, Field>() {
        {
            FieldUtil.toMap(this, new Field("id", "al_id"));
            FieldUtil.toMap(this, new Field("refTarget", "al_ref_target"));
            FieldUtil.toMap(this, new Field("refTargetKey", "al_ref_target_key"));
            FieldUtil.toMap(this, new Field("refTargetType", "al_ref_target_type"));
            FieldUtil.toMap(this, new Field("action", "al_action"));
            FieldUtil.toMap(this, new Field("log", "al_log"));
            FieldUtil.toMap(this, new Field("message", "al_message"));
            FieldUtil.toMap(this, new Field("ip", "al_ip"));
            FieldUtil.toMap(this, new Field("year", "al_year"));
            FieldUtil.toMap(this, new Field("month", "al_month"));
            FieldUtil.toMap(this, new Field("day", "al_day"));
            FieldUtil.toMap(this, new Field("createdBy", "al_created_by"));
            FieldUtil.toMap(this, new Field("createdDt", "al_created_dt"));
        }
    };

    String prefix();

    /**
    * 아이디
    */
    default Field id() {
        return new Field(prefix(), "id", "al_id");
    }

    default Field id(String prefix) {
        return new Field(prefix, "id", "al_id");
    }

    /**
    * 참조구분
    */
    default Field refTarget() {
        return new Field(prefix(), "refTarget", "al_ref_target");
    }

    default Field refTarget(String prefix) {
        return new Field(prefix, "refTarget", "al_ref_target");
    }

    /**
    * 참조구분키
    */
    default Field refTargetKey() {
        return new Field(prefix(), "refTargetKey", "al_ref_target_key");
    }

    default Field refTargetKey(String prefix) {
        return new Field(prefix, "refTargetKey", "al_ref_target_key");
    }

    /**
    * 참조타입
    */
    default Field refTargetType() {
        return new Field(prefix(), "refTargetType", "al_ref_target_type");
    }

    default Field refTargetType(String prefix) {
        return new Field(prefix, "refTargetType", "al_ref_target_type");
    }

    /**
    * 액션
    */
    default Field action() {
        return new Field(prefix(), "action", "al_action");
    }

    default Field action(String prefix) {
        return new Field(prefix, "action", "al_action");
    }

    /**
    * 로그
    */
    default Field log() {
        return new Field(prefix(), "log", "al_log");
    }

    default Field log(String prefix) {
        return new Field(prefix, "log", "al_log");
    }

    /**
    * 메시지
    */
    default Field message() {
        return new Field(prefix(), "message", "al_message");
    }

    default Field message(String prefix) {
        return new Field(prefix, "message", "al_message");
    }

    /**
    * IP
    */
    default Field ip() {
        return new Field(prefix(), "ip", "al_ip");
    }

    default Field ip(String prefix) {
        return new Field(prefix, "ip", "al_ip");
    }

    /**
    * 년
    */
    default Field year() {
        return new Field(prefix(), "year", "al_year");
    }

    default Field year(String prefix) {
        return new Field(prefix, "year", "al_year");
    }

    /**
    * 월
    */
    default Field month() {
        return new Field(prefix(), "month", "al_month");
    }

    default Field month(String prefix) {
        return new Field(prefix, "month", "al_month");
    }

    /**
    * 일
    */
    default Field day() {
        return new Field(prefix(), "day", "al_day");
    }

    default Field day(String prefix) {
        return new Field(prefix, "day", "al_day");
    }

    /**
    * 등록자
    */
    default Field createdBy() {
        return new Field(prefix(), "createdBy", "al_created_by");
    }

    default Field createdBy(String prefix) {
        return new Field(prefix, "createdBy", "al_created_by");
    }

    /**
    * 등록일시
    */
    default Field createdDt() {
        return new Field(prefix(), "createdDt", "al_created_dt");
    }

    default Field createdDt(String prefix) {
        return new Field(prefix, "createdDt", "al_created_dt");
    }

}
