/*
 * Source code generated by UnvUS.
 * Copyright(c) 2017 unvus.com All rights reserved.
 * Template skrull-pack-mybatis:src/main/java/service/Service.e.vm.java
 * Template is part of project: https://git.unvus.com/unvus/opensource/pack-unvus-mybatis
 */
package com.neofect.gts.core.services.common.service;

import java.util.List;
import java.util.Map;

import org.springframework.stereotype.Service;
import org.springframework.transaction.annotation.Transactional;

import com.neofect.gts.core.services.common.domain.CodeCareamt;
import com.neofect.gts.core.services.common.repository.CodeCareamtRepository;
import com.unvus.config.mybatis.pagination.OrderBy;
import com.unvus.query.QueryTool;

/**
 * Service for {@link CodeCareamt}<br/>
 */
@Service
public class CodeCareamtService {

    private final CodeCareamtRepository codeCareamtRepository;

    public CodeCareamtService(CodeCareamtRepository codeCareamtRepository) {
        this.codeCareamtRepository = codeCareamtRepository;
    }

    //region ------------------------------------------------------------------------------------------------ codeCareamt CRUD

    @Transactional
    public CodeCareamt saveCodeCareamt(CodeCareamt codeCareamt) {
        // if (codeCareamt.getId() == null) {
        //     addCodeCareamt(codeCareamt);
        // } else {
        //     modifyCodeCareamt(codeCareamt);
        // }

        return codeCareamt;
    }

    private int addCodeCareamt(CodeCareamt codeCareamt) {
        int result = codeCareamtRepository.insertCodeCareamt(codeCareamt);
        return result;
    }

    private int modifyCodeCareamt(CodeCareamt codeCareamt) {
        int result = codeCareamtRepository.updateCodeCareamt(codeCareamt);
        return result;
    }

    @Transactional
    public int removeCodeCareamt(Long id) {
        int rows = codeCareamtRepository.deleteCodeCareamt(id);
        return rows;
    }

    public CodeCareamt getCodeCareamt(Long id) {
        CodeCareamt codeCareamt = codeCareamtRepository.getCodeCareamt(id);

        return codeCareamt;
    }

    public int listCodeCareamtCnt(Map<String, Object> params) {
        int rows = codeCareamtRepository.listCodeCareamtCnt(params);
        return rows;
    }

    public List<CodeCareamt> listCodeCareamt(Map<String, Object> params) {
        List<CodeCareamt> lists = codeCareamtRepository.listCodeCareamt(params);

        return lists;
    }

    public List<CodeCareamt> listCodeCareamtByIds(List<Long> ids, Map<String, Object> params) {
        params.put("ids", ids);
        QueryTool.setDefaultOrderBy(new OrderBy("CAREFACILITY_DIV", ids));
        QueryTool.setDefaultOrderBy(new OrderBy("CUST_LEVEL_DIV", ids));
        QueryTool.setDefaultOrderBy(new OrderBy("APPLY_DATE", ids));
        List<CodeCareamt> lists = codeCareamtRepository.listCodeCareamt(params);

        return lists;
    }

    //endregion

}
