/*
 * Source code generated by UnvUS.
 * Copyright(c) 2017 unvus.com All rights reserved.
 * Template skrull-pack-mybatis:src/main/java/service/Service.e.vm.java
 * Template is part of project: https://git.unvus.com/unvus/opensource/pack-unvus-mybatis
 */
package com.neofect.gts.core.services.common.service;

import java.util.List;
import java.util.Map;

import org.springframework.stereotype.Service;
import org.springframework.transaction.annotation.Transactional;

import com.neofect.gts.core.services.common.domain.CodePl;
import com.neofect.gts.core.services.common.repository.CodePlRepository;
import com.unvus.config.mybatis.pagination.OrderBy;
import com.unvus.query.QueryTool;

/**
 * Service for {@link CodePl}<br/>
 */
@Service
public class CodePlService {

    private final CodePlRepository codePlRepository;

    public CodePlService(CodePlRepository codePlRepository) {
        this.codePlRepository = codePlRepository;
    }

    //region ------------------------------------------------------------------------------------------------ codePl CRUD

    @Transactional
    public CodePl saveCodePl(CodePl codePl) {
        // if (codePl.getId() == null) {
        //     addCodePl(codePl);
        // } else {
        //     modifyCodePl(codePl);
        // }

        return codePl;
    }

    private int addCodePl(CodePl codePl) {
        int result = codePlRepository.insertCodePl(codePl);
        return result;
    }

    private int modifyCodePl(CodePl codePl) {
        int result = codePlRepository.updateCodePl(codePl);
        return result;
    }

    @Transactional
    public int removeCodePl(Long id) {
        int rows = codePlRepository.deleteCodePl(id);
        return rows;
    }

    public CodePl getCodePl(Long id) {
        CodePl codePl = codePlRepository.getCodePl(id);

        return codePl;
    }

    public int listCodePlCnt(Map<String, Object> params) {
        int rows = codePlRepository.listCodePlCnt(params);
        return rows;
    }

    public List<CodePl> listCodePl(Map<String, Object> params) {
        List<CodePl> lists = codePlRepository.listCodePl(params);

        return lists;
    }

    public List<CodePl> listCodePlByIds(List<Long> ids, Map<String, Object> params) {
        params.put("ids", ids);
        QueryTool.setDefaultOrderBy(new OrderBy("PL_TYPE", ids));
        QueryTool.setDefaultOrderBy(new OrderBy("ITEM_CODE", ids));
        List<CodePl> lists = codePlRepository.listCodePl(params);

        return lists;
    }

    //endregion

}
