/*
 * Source code generated by UnvUS.
 * Copyright(c) 2017 unvus.com All rights reserved.
 * Template skrull-pack-mybatis:src/main/java/service/Service.e.vm.java
 * Template is part of project: https://git.unvus.com/unvus/opensource/pack-unvus-mybatis
 */
package com.neofect.gts.core.services.common.service;

import java.util.List;
import java.util.Map;

import org.springframework.stereotype.Service;
import org.springframework.transaction.annotation.Transactional;

import com.neofect.gts.core.services.common.domain.CodeMember;
import com.neofect.gts.core.services.common.repository.CodeMemberRepository;
import com.unvus.config.mybatis.pagination.OrderBy;
import com.unvus.query.QueryTool;

/**
 * Service for {@link CodeMember}<br/>
 */
@Service
public class CodeMemberService {

    private final CodeMemberRepository codeMemberRepository;

    public CodeMemberService(CodeMemberRepository codeMemberRepository) {
        this.codeMemberRepository = codeMemberRepository;
    }

    //region ------------------------------------------------------------------------------------------------ codeMember CRUD

    @Transactional
    public CodeMember saveCodeMember(CodeMember codeMember) {
        if (codeMember.getId() == null) {
            addCodeMember(codeMember);
        } else {
            modifyCodeMember(codeMember);
        }

        return codeMember;
    }

    private int addCodeMember(CodeMember codeMember) {
        int result = codeMemberRepository.insertCodeMember(codeMember);
        return result;
    }

    private int modifyCodeMember(CodeMember codeMember) {
        int result = codeMemberRepository.updateCodeMember(codeMember);
        return result;
    }

    @Transactional
    public int removeCodeMember(Long id) {
        int rows = codeMemberRepository.deleteCodeMember(id);
        return rows;
    }

    public CodeMember getCodeMember(Long id) {
        CodeMember codeMember = codeMemberRepository.getCodeMember(id);

        return codeMember;
    }

    public int listCodeMemberCnt(Map<String, Object> params) {
        int rows = codeMemberRepository.listCodeMemberCnt(params);
        return rows;
    }

    public List<CodeMember> listCodeMember(Map<String, Object> params) {
        List<CodeMember> lists = codeMemberRepository.listCodeMember(params);

        return lists;
    }

    public List<CodeMember> listCodeMemberByIds(List<Long> ids, Map<String, Object> params) {
        params.put("ids", ids);
        QueryTool.setDefaultOrderBy(new OrderBy("MEMBER_ID", ids));
        List<CodeMember> lists = codeMemberRepository.listCodeMember(params);

        return lists;
    }

    //endregion

}
