/*
 * Source code generated by UnvUS.
 * Copyright(c) 2017 unvus.com All rights reserved.
 * Template skrull-pack-mybatis:src/main/java/repository/RepositoryBase.e.vm.java
 * Template is part of project: https://git.unvus.com/unvus/opensource/pack-unvus-mybatis
 */
package com.neofect.gts.core.services.site.repository;

import java.util.List;
import java.util.Map;

import org.springframework.stereotype.Repository;

import com.unvus.config.mybatis.pagination.Pageable;
import com.unvus.config.mybatis.support.DefaultMapper;
import com.neofect.gts.core.services.site.domain.Term;

/**
 * Repository for {@link Term}
 * @see TermRepository
 */
@DefaultMapper
@Repository
public interface TermRepository_ {

    Term simpleGetTerm(Long id);

    int simpleListTermCnt(Map<String, Object> params);

    /**
     * if yuou want to avoid result objects less than dataPerPage caused by "1:N mappings".. <br/>
     * add function that return "distinct id list" and name it with : <br/>
     * <code>List<Long> listTermIds(Map<String, Object> params)</code> <br/>
     * and replace @Pageable with :  <br/>
     * <code>@Pageable(useMergeQuery = true)</code> <br/>
     */
    @Pageable
    List<Term> simpleListTerm(Map<String, Object> params);

    int insertTerm(Term term);

    int updateTerm(Term term);

    int updateTermDynamic(Term term);

    int deleteTerm(Long id);

}
