/*
 * Source code generated by UnvUS.
 * Copyright(c) 2017 unvus.com All rights reserved.
 * Template skrull-pack-mybatis:src/main/java/rest/Rest.e.vm.java
 * Template is part of project: https://git.unvus.com/unvus/opensource/pack-unvus-mybatis
 */
package com.neofect.gts.web.cms.rest.common;

import java.net.URISyntaxException;
import java.util.HashMap;
import java.util.List;
import java.util.Map;

import org.springframework.http.HttpHeaders;
import org.springframework.http.HttpStatus;
import org.springframework.http.MediaType;
import org.springframework.http.ResponseEntity;
import org.springframework.web.bind.annotation.*;

import com.google.common.collect.ImmutableMap;
import com.neofect.gts.core.services.common.domain.CodeComdiv;
import com.neofect.gts.core.services.common.service.CodeComdivService;
import com.unvus.web.util.PaginationUtil;

import lombok.extern.slf4j.Slf4j;

/**
 * Rest for {@link CodeComdiv}<br/>
 */
@Slf4j
@RestController
@RequestMapping("/api")
public class CodeComdivResource {

    private final CodeComdivService codeComdivService;

    public CodeComdivResource(CodeComdivService codeComdivService) {
        this.codeComdivService = codeComdivService;
    }

    //region ------------------------------------------------------------------------------------------------ codeComdiv API

    /**
     *
     */
    @GetMapping(value = "/code-comdiv", produces = MediaType.APPLICATION_JSON_VALUE)
    public ResponseEntity<List<CodeComdiv>> listCodeComdiv(@RequestParam(value = "q", required = false) Map<String, Object> q) throws URISyntaxException {
        if (q == null) {
            q = new HashMap();
        }

        List<CodeComdiv> codeComdivList = codeComdivService.listCodeComdiv(q);

        HttpHeaders headers = PaginationUtil.generatePaginationHttpHeaders();

        return new ResponseEntity<>(codeComdivList, headers, HttpStatus.OK);
    }

    /**
     * get count
     * @return
     */
    @GetMapping(value = "/code-comdiv/_count", produces = MediaType.APPLICATION_JSON_VALUE)
    public ResponseEntity<Map> getCount(@RequestParam(value = "q", required = false) Map<String, Object> q) {
        int count = codeComdivService.listCodeComdivCnt(q);

        return new ResponseEntity<>(ImmutableMap.of("count", count), HttpStatus.OK);
    }

    /**
     * get empty object
     * @return
     */
    @GetMapping(value = "/code-comdiv/_empty", produces = MediaType.APPLICATION_JSON_VALUE)
    public ResponseEntity<CodeComdiv> getEmptyCodeComdiv() {
        CodeComdiv codeComdiv = new CodeComdiv();
        return new ResponseEntity<>(codeComdiv, HttpStatus.OK);
    }

    /**
     * get
     */
    @GetMapping(value = "/code-comdiv/{id}", produces = MediaType.APPLICATION_JSON_VALUE)
    public ResponseEntity<CodeComdiv> getCodeComdiv(@PathVariable("id") Long id) {
        CodeComdiv codeComdiv = codeComdivService.getCodeComdiv(id);
        return new ResponseEntity<>(codeComdiv, HttpStatus.OK);
    }

    /**
     * add
     */
    @PostMapping("/code-comdiv")
    public ResponseEntity<Void> addCodeComdiv(@RequestBody CodeComdiv codeComdiv) {
        codeComdivService.saveCodeComdiv(codeComdiv);

        return ResponseEntity.ok().build();
    }

    /**
     * modify
     */
    @PutMapping("/code-comdiv/{id}")
    public ResponseEntity<Void> updateCodeComdiv(@PathVariable("id") Long id, @RequestBody CodeComdiv codeComdiv) throws Exception {
        // if (!id.equals(codeComdiv.getId())) {
        //     return new ResponseEntity(HttpStatus.BAD_REQUEST);
        // }
        codeComdivService.saveCodeComdiv(codeComdiv);
        return ResponseEntity.ok().build();
    }

    /**
     * delete
     */
    @DeleteMapping("/code-comdiv/{id}")
    public ResponseEntity<Void> removeCodeComdiv(@PathVariable("id") Long id) {
        codeComdivService.removeCodeComdiv(id);
        return ResponseEntity.ok().build();
    }

    //endregion

}
