/*
 * Source code generated by UnvUS.
 * Copyright(c) 2017 unvus.com All rights reserved.
 * Template skrull-pack-mybatis:src/main/java/rest/Rest.e.vm.java
 * Template is part of project: https://git.unvus.com/unvus/opensource/pack-unvus-mybatis
 */
package com.neofect.gts.web.cms.rest.common;

import java.net.URISyntaxException;
import java.util.HashMap;
import java.util.List;
import java.util.Map;

import org.springframework.http.HttpHeaders;
import org.springframework.http.HttpStatus;
import org.springframework.http.MediaType;
import org.springframework.http.ResponseEntity;
import org.springframework.web.bind.annotation.*;

import com.google.common.collect.ImmutableMap;
import com.neofect.gts.core.services.common.domain.CodeAccount;
import com.neofect.gts.core.services.common.service.CodeAccountService;
import com.unvus.web.util.PaginationUtil;

import lombok.extern.slf4j.Slf4j;

/**
 * Rest for {@link CodeAccount}<br/>
 */
@Slf4j
@RestController
@RequestMapping("/api")
public class CodeAccountResource {

    private final CodeAccountService codeAccountService;

    public CodeAccountResource(CodeAccountService codeAccountService) {
        this.codeAccountService = codeAccountService;
    }

    //region ------------------------------------------------------------------------------------------------ codeAccount API

    /**
     *
     */
    @GetMapping(value = "/code-account", produces = MediaType.APPLICATION_JSON_VALUE)
    public ResponseEntity<List<CodeAccount>> listCodeAccount(@RequestParam(value = "q", required = false) Map<String, Object> q) throws URISyntaxException {
        if (q == null) {
            q = new HashMap();
        }

        List<CodeAccount> codeAccountList = codeAccountService.listCodeAccount(q);

        HttpHeaders headers = PaginationUtil.generatePaginationHttpHeaders();

        return new ResponseEntity<>(codeAccountList, headers, HttpStatus.OK);
    }

    /**
     * get count
     * @return
     */
    @GetMapping(value = "/code-account/_count", produces = MediaType.APPLICATION_JSON_VALUE)
    public ResponseEntity<Map> getCount(@RequestParam(value = "q", required = false) Map<String, Object> q) {
        int count = codeAccountService.listCodeAccountCnt(q);

        return new ResponseEntity<>(ImmutableMap.of("count", count), HttpStatus.OK);
    }

    /**
     * get empty object
     * @return
     */
    @GetMapping(value = "/code-account/_empty", produces = MediaType.APPLICATION_JSON_VALUE)
    public ResponseEntity<CodeAccount> getEmptyCodeAccount() {
        CodeAccount codeAccount = new CodeAccount();
        return new ResponseEntity<>(codeAccount, HttpStatus.OK);
    }

    /**
     * get
     */
    @GetMapping(value = "/code-account/{id}", produces = MediaType.APPLICATION_JSON_VALUE)
    public ResponseEntity<CodeAccount> getCodeAccount(@PathVariable("id") Long id) {
        CodeAccount codeAccount = codeAccountService.getCodeAccount(id);
        return new ResponseEntity<>(codeAccount, HttpStatus.OK);
    }

    /**
     * add
     */
    @PostMapping("/code-account")
    public ResponseEntity<Void> addCodeAccount(@RequestBody CodeAccount codeAccount) {
        codeAccountService.saveCodeAccount(codeAccount);

        return ResponseEntity.ok().build();
    }

    /**
     * modify
     */
    @PutMapping("/code-account/{id}")
    public ResponseEntity<Void> updateCodeAccount(@PathVariable("id") Long id, @RequestBody CodeAccount codeAccount) throws Exception {
        if (!id.equals(codeAccount.getId())) {
            return new ResponseEntity(HttpStatus.BAD_REQUEST);
        }
        codeAccountService.saveCodeAccount(codeAccount);
        return ResponseEntity.ok().build();
    }

    /**
     * delete
     */
    @DeleteMapping("/code-account/{id}")
    public ResponseEntity<Void> removeCodeAccount(@PathVariable("id") Long id) {
        codeAccountService.removeCodeAccount(id);
        return ResponseEntity.ok().build();
    }

    //endregion

}
