/*
 * Source code generated by UnvUS.
 * Copyright(c) 2017 unvus.com All rights reserved.
 * Template skrull-pack-mybatis:src/main/java/rest/Rest.e.vm.java
 * Template is part of project: https://git.unvus.com/unvus/opensource/pack-unvus-mybatis
 */
package com.neofect.gts.web.cms.rest.common;

import java.net.URISyntaxException;
import java.util.HashMap;
import java.util.List;
import java.util.Map;

import org.springframework.http.HttpHeaders;
import org.springframework.http.HttpStatus;
import org.springframework.http.MediaType;
import org.springframework.http.ResponseEntity;
import org.springframework.web.bind.annotation.*;

import com.google.common.collect.ImmutableMap;
import com.neofect.gts.core.services.common.domain.CodeInoutItem;
import com.neofect.gts.core.services.common.service.CodeInoutItemService;
import com.unvus.web.util.PaginationUtil;

import lombok.extern.slf4j.Slf4j;

/**
 * Rest for {@link CodeInoutItem}<br/>
 */
@Slf4j
@RestController
@RequestMapping("/api")
public class CodeInoutItemResource {

    private final CodeInoutItemService codeInoutItemService;

    public CodeInoutItemResource(CodeInoutItemService codeInoutItemService) {
        this.codeInoutItemService = codeInoutItemService;
    }

    //region ------------------------------------------------------------------------------------------------ codeInoutItem API

    /**
     *
     */
    @GetMapping(value = "/code-inout-item", produces = MediaType.APPLICATION_JSON_VALUE)
    public ResponseEntity<List<CodeInoutItem>> listCodeInoutItem(@RequestParam(value = "q", required = false) Map<String, Object> q) throws URISyntaxException {
        if (q == null) {
            q = new HashMap();
        }

        List<CodeInoutItem> codeInoutItemList = codeInoutItemService.listCodeInoutItem(q);

        HttpHeaders headers = PaginationUtil.generatePaginationHttpHeaders();

        return new ResponseEntity<>(codeInoutItemList, headers, HttpStatus.OK);
    }

    /**
     * get count
     * @return
     */
    @GetMapping(value = "/code-inout-item/_count", produces = MediaType.APPLICATION_JSON_VALUE)
    public ResponseEntity<Map> getCount(@RequestParam(value = "q", required = false) Map<String, Object> q) {
        int count = codeInoutItemService.listCodeInoutItemCnt(q);

        return new ResponseEntity<>(ImmutableMap.of("count", count), HttpStatus.OK);
    }

    /**
     * get empty object
     * @return
     */
    @GetMapping(value = "/code-inout-item/_empty", produces = MediaType.APPLICATION_JSON_VALUE)
    public ResponseEntity<CodeInoutItem> getEmptyCodeInoutItem() {
        CodeInoutItem codeInoutItem = new CodeInoutItem();
        return new ResponseEntity<>(codeInoutItem, HttpStatus.OK);
    }

    /**
     * get
     */
    @GetMapping(value = "/code-inout-item/{id}", produces = MediaType.APPLICATION_JSON_VALUE)
    public ResponseEntity<CodeInoutItem> getCodeInoutItem(@PathVariable("id") Long id) {
        CodeInoutItem codeInoutItem = codeInoutItemService.getCodeInoutItem(id);
        return new ResponseEntity<>(codeInoutItem, HttpStatus.OK);
    }

    /**
     * add
     */
    @PostMapping("/code-inout-item")
    public ResponseEntity<Void> addCodeInoutItem(@RequestBody CodeInoutItem codeInoutItem) {
        codeInoutItemService.saveCodeInoutItem(codeInoutItem);

        return ResponseEntity.ok().build();
    }

    /**
     * modify
     */
    @PutMapping("/code-inout-item/{id}")
    public ResponseEntity<Void> updateCodeInoutItem(@PathVariable("id") Long id, @RequestBody CodeInoutItem codeInoutItem) throws Exception {
        if (!id.equals(codeInoutItem.getId())) {
            return new ResponseEntity(HttpStatus.BAD_REQUEST);
        }
        codeInoutItemService.saveCodeInoutItem(codeInoutItem);
        return ResponseEntity.ok().build();
    }

    /**
     * delete
     */
    @DeleteMapping("/code-inout-item/{id}")
    public ResponseEntity<Void> removeCodeInoutItem(@PathVariable("id") Long id) {
        codeInoutItemService.removeCodeInoutItem(id);
        return ResponseEntity.ok().build();
    }

    //endregion

}
