/*
 * Source code generated by UnvUS.
 * Copyright(c) 2017 unvus.com All rights reserved.
 * Template skrull-pack-mybatis:src/main/java/rest/Rest.e.vm.java
 * Template is part of project: https://git.unvus.com/unvus/opensource/pack-unvus-mybatis
 */
package com.neofect.gts.web.cms.rest.common;

import java.net.URISyntaxException;
import java.util.HashMap;
import java.util.List;
import java.util.Map;

import org.springframework.http.HttpHeaders;
import org.springframework.http.HttpStatus;
import org.springframework.http.MediaType;
import org.springframework.http.ResponseEntity;
import org.springframework.web.bind.annotation.*;

import com.google.common.collect.ImmutableMap;
import com.neofect.gts.core.services.common.domain.CodeProduct;
import com.neofect.gts.core.services.common.service.CodeProductService;
import com.unvus.web.util.PaginationUtil;

import lombok.extern.slf4j.Slf4j;

/**
 * Rest for {@link CodeProduct}<br/>
 */
@Slf4j
@RestController
@RequestMapping("/api")
public class CodeProductResource {

    private final CodeProductService codeProductService;

    public CodeProductResource(CodeProductService codeProductService) {
        this.codeProductService = codeProductService;
    }

    //region ------------------------------------------------------------------------------------------------ codeProduct API

    /**
     *
     */
    @GetMapping(value = "/code-product", produces = MediaType.APPLICATION_JSON_VALUE)
    public ResponseEntity<List<CodeProduct>> listCodeProduct(@RequestParam(value = "q", required = false) Map<String, Object> q) throws URISyntaxException {
        if (q == null) {
            q = new HashMap();
        }

        List<CodeProduct> codeProductList = codeProductService.listCodeProduct(q);

        HttpHeaders headers = PaginationUtil.generatePaginationHttpHeaders();

        return new ResponseEntity<>(codeProductList, headers, HttpStatus.OK);
    }

    /**
     * get count
     * @return
     */
    @GetMapping(value = "/code-product/_count", produces = MediaType.APPLICATION_JSON_VALUE)
    public ResponseEntity<Map> getCount(@RequestParam(value = "q", required = false) Map<String, Object> q) {
        int count = codeProductService.listCodeProductCnt(q);

        return new ResponseEntity<>(ImmutableMap.of("count", count), HttpStatus.OK);
    }

    /**
     * get empty object
     * @return
     */
    @GetMapping(value = "/code-product/_empty", produces = MediaType.APPLICATION_JSON_VALUE)
    public ResponseEntity<CodeProduct> getEmptyCodeProduct() {
        CodeProduct codeProduct = new CodeProduct();
        return new ResponseEntity<>(codeProduct, HttpStatus.OK);
    }

    /**
     * get
     */
    @GetMapping(value = "/code-product/{id}", produces = MediaType.APPLICATION_JSON_VALUE)
    public ResponseEntity<CodeProduct> getCodeProduct(@PathVariable("id") Long id) {
        CodeProduct codeProduct = codeProductService.getCodeProduct(id);
        return new ResponseEntity<>(codeProduct, HttpStatus.OK);
    }

    /**
     * add
     */
    @PostMapping("/code-product")
    public ResponseEntity<Void> addCodeProduct(@RequestBody CodeProduct codeProduct) {
        codeProductService.saveCodeProduct(codeProduct);

        return ResponseEntity.ok().build();
    }

    /**
     * modify
     */
    @PutMapping("/code-product/{id}")
    public ResponseEntity<Void> updateCodeProduct(@PathVariable("id") Long id, @RequestBody CodeProduct codeProduct) throws Exception {
        if (!id.equals(codeProduct.getId())) {
            return new ResponseEntity(HttpStatus.BAD_REQUEST);
        }
        codeProductService.saveCodeProduct(codeProduct);
        return ResponseEntity.ok().build();
    }

    /**
     * delete
     */
    @DeleteMapping("/code-product/{id}")
    public ResponseEntity<Void> removeCodeProduct(@PathVariable("id") Long id) {
        codeProductService.removeCodeProduct(id);
        return ResponseEntity.ok().build();
    }

    //endregion

}
