/*
 * Source code generated by UnvUS.
 * Copyright(c) 2017 unvus.com All rights reserved.
 * Template skrull-pack-mybatis:src/main/java/rest/Rest.e.vm.java
 * Template is part of project: https://git.unvus.com/unvus/opensource/pack-unvus-mybatis
 */
package com.neofect.gts.web.cms.rest.common;

import java.net.URISyntaxException;
import java.util.HashMap;
import java.util.List;
import java.util.Map;

import org.springframework.http.HttpHeaders;
import org.springframework.http.HttpStatus;
import org.springframework.http.MediaType;
import org.springframework.http.ResponseEntity;
import org.springframework.web.bind.annotation.*;

import com.google.common.collect.ImmutableMap;
import com.neofect.gts.core.services.common.domain.CodePl;
import com.neofect.gts.core.services.common.service.CodePlService;
import com.unvus.web.util.PaginationUtil;

import lombok.extern.slf4j.Slf4j;

/**
 * Rest for {@link CodePl}<br/>
 */
@Slf4j
@RestController
@RequestMapping("/api")
public class CodePlResource {

    private final CodePlService codePlService;

    public CodePlResource(CodePlService codePlService) {
        this.codePlService = codePlService;
    }

    //region ------------------------------------------------------------------------------------------------ codePl API

    /**
     *
     */
    @GetMapping(value = "/code-pl", produces = MediaType.APPLICATION_JSON_VALUE)
    public ResponseEntity<List<CodePl>> listCodePl(@RequestParam(value = "q", required = false) Map<String, Object> q) throws URISyntaxException {
        if (q == null) {
            q = new HashMap();
        }

        List<CodePl> codePlList = codePlService.listCodePl(q);

        HttpHeaders headers = PaginationUtil.generatePaginationHttpHeaders();

        return new ResponseEntity<>(codePlList, headers, HttpStatus.OK);
    }

    /**
     * get count
     * @return
     */
    @GetMapping(value = "/code-pl/_count", produces = MediaType.APPLICATION_JSON_VALUE)
    public ResponseEntity<Map> getCount(@RequestParam(value = "q", required = false) Map<String, Object> q) {
        int count = codePlService.listCodePlCnt(q);

        return new ResponseEntity<>(ImmutableMap.of("count", count), HttpStatus.OK);
    }

    /**
     * get empty object
     * @return
     */
    @GetMapping(value = "/code-pl/_empty", produces = MediaType.APPLICATION_JSON_VALUE)
    public ResponseEntity<CodePl> getEmptyCodePl() {
        CodePl codePl = new CodePl();
        return new ResponseEntity<>(codePl, HttpStatus.OK);
    }

    /**
     * get
     */
    @GetMapping(value = "/code-pl/{id}", produces = MediaType.APPLICATION_JSON_VALUE)
    public ResponseEntity<CodePl> getCodePl(@PathVariable("id") Long id) {
        CodePl codePl = codePlService.getCodePl(id);
        return new ResponseEntity<>(codePl, HttpStatus.OK);
    }

    /**
     * add
     */
    @PostMapping("/code-pl")
    public ResponseEntity<Void> addCodePl(@RequestBody CodePl codePl) {
        codePlService.saveCodePl(codePl);

        return ResponseEntity.ok().build();
    }

    /**
     * modify
     */
    @PutMapping("/code-pl/{id}")
    public ResponseEntity<Void> updateCodePl(@PathVariable("id") Long id, @RequestBody CodePl codePl) throws Exception {
        // if (!id.equals(codePl.getId())) {
        //     return new ResponseEntity(HttpStatus.BAD_REQUEST);
        // }
        codePlService.saveCodePl(codePl);
        return ResponseEntity.ok().build();
    }

    /**
     * delete
     */
    @DeleteMapping("/code-pl/{id}")
    public ResponseEntity<Void> removeCodePl(@PathVariable("id") Long id) {
        codePlService.removeCodePl(id);
        return ResponseEntity.ok().build();
    }

    //endregion

}
