/*
 * Source code generated by UnvUS.
 * Copyright(c) 2017 unvus.com All rights reserved.
 * Template skrull-pack-mybatis:src/main/java/repository/RepositoryBase.e.vm.java
 * Template is part of project: https://git.unvus.com/unvus/opensource/pack-unvus-mybatis
 */
package com.neofect.gts.core.services.am.repository;

import java.util.List;
import java.util.Map;

import org.springframework.stereotype.Repository;

import com.neofect.gts.core.services.am.domain.AmCodeAcntComp;
import com.unvus.config.mybatis.pagination.Pageable;
import com.unvus.config.mybatis.support.DefaultMapper;

/**
 * Repository for {@link AmCodeAcntComp}
 * @see com.neofect.gts.core.services.am.repository.AmCodeAcntCompRepository
 */
@DefaultMapper
@Repository
public interface AmCodeAcntCompRepository_ {

    AmCodeAcntComp simpleGetAmCodeAcntComp(Long id);

    int simpleListAmCodeAcntCompCnt(Map<String, Object> params);

    /**
     * if yuou want to avoid result objects less than dataPerPage caused by "1:N mappings".. <br/>
     * add function that return "distinct id list" and name it with : <br/>
     * <code>List<Long> listAmCodeAcntCompIds(Map<String, Object> params)</code> <br/>
     * and replace @Pageable with :  <br/>
     * <code>@Pageable(useMergeQuery = true)</code> <br/>
     */
    @Pageable
    List<AmCodeAcntComp> simpleListAmCodeAcntComp(Map<String, Object> params);

    int insertAmCodeAcntComp(AmCodeAcntComp amCodeAcntComp);

    int updateAmCodeAcntComp(AmCodeAcntComp amCodeAcntComp);

    int updateAmCodeAcntCompDynamic(AmCodeAcntComp amCodeAcntComp);

    int deleteAmCodeAcntComp(Long id);

}
