/*
 * Source code generated by UnvUS.
 * Copyright(c) 2017 unvus.com All rights reserved.
 * Template skrull-pack-mybatis:src/main/java/repository/RepositoryBase.e.vm.java
 * Template is part of project: https://git.unvus.com/unvus/opensource/pack-unvus-mybatis
 */
package com.neofect.gts.core.services.am.repository;

import java.util.List;
import java.util.Map;

import org.springframework.stereotype.Repository;

import com.neofect.gts.core.services.am.domain.AmCodeDept;
import com.unvus.config.mybatis.pagination.Pageable;
import com.unvus.config.mybatis.support.DefaultMapper;

/**
 * Repository for {@link AmCodeDept}
 * @see com.neofect.gts.core.services.am.repository.AmCodeDeptRepository
 */
@DefaultMapper
@Repository
public interface AmCodeDeptRepository_ {

    AmCodeDept simpleGetAmCodeDept(Long id);

    int simpleListAmCodeDeptCnt(Map<String, Object> params);

    /**
     * if yuou want to avoid result objects less than dataPerPage caused by "1:N mappings".. <br/>
     * add function that return "distinct id list" and name it with : <br/>
     * <code>List<Long> listAmCodeDeptIds(Map<String, Object> params)</code> <br/>
     * and replace @Pageable with :  <br/>
     * <code>@Pageable(useMergeQuery = true)</code> <br/>
     */
    @Pageable
    List<AmCodeDept> simpleListAmCodeDept(Map<String, Object> params);

    int insertAmCodeDept(AmCodeDept amCodeDept);

    int updateAmCodeDept(AmCodeDept amCodeDept);

    int updateAmCodeDeptDynamic(AmCodeDept amCodeDept);

    int deleteAmCodeDept(Long id);

}
