/*
 * Source code generated by UnvUS.
 * Copyright(c) 2017 unvus.com All rights reserved.
 * Template skrull-pack-mybatis:src/main/java/repository/RepositoryBase.e.vm.java
 * Template is part of project: https://git.unvus.com/unvus/opensource/pack-unvus-mybatis
 */
package com.neofect.gts.core.services.sm.repository;

import java.util.List;
import java.util.Map;

import org.springframework.stereotype.Repository;

import com.neofect.gts.core.services.sm.domain.SmAuthActUser;
import com.unvus.config.mybatis.pagination.Pageable;
import com.unvus.config.mybatis.support.DefaultMapper;

/**
 * Repository for {@link SmAuthActUser}
 * @see com.neofect.gts.core.services.sm.repository.SmAuthActUserRepository
 */
@DefaultMapper
@Repository
public interface SmAuthActUserRepository_ {

    SmAuthActUser simpleGetSmAuthActUser(Long id);

    int simpleListSmAuthActUserCnt(Map<String, Object> params);

    /**
     * if yuou want to avoid result objects less than dataPerPage caused by "1:N mappings".. <br/>
     * add function that return "distinct id list" and name it with : <br/>
     * <code>List<Long> listSmAuthActUserIds(Map<String, Object> params)</code> <br/>
     * and replace @Pageable with :  <br/>
     * <code>@Pageable(useMergeQuery = true)</code> <br/>
     */
    @Pageable
    List<SmAuthActUser> simpleListSmAuthActUser(Map<String, Object> params);

    int insertSmAuthActUser(SmAuthActUser smAuthActUser);

    int updateSmAuthActUser(SmAuthActUser smAuthActUser);

    int updateSmAuthActUserDynamic(SmAuthActUser smAuthActUser);

    int deleteSmAuthActUser(Long id);

}
