/*
 * Source code generated by UnvUS.
 * Copyright(c) 2017 unvus.com All rights reserved.
 * Template skrull-pack-mybatis:src/main/java/service/Service.e.vm.java
 * Template is part of project: https://git.unvus.com/unvus/opensource/pack-unvus-mybatis
 */
package com.neofect.gts.core.services.gs.service;

import java.util.List;
import java.util.Map;

import org.springframework.stereotype.Service;
import org.springframework.transaction.annotation.Transactional;

import com.neofect.gts.core.services.gs.domain.GsSlipAcnt;
import com.neofect.gts.core.services.gs.repository.GsSlipAcntRepository;
import com.unvus.config.mybatis.pagination.OrderBy;
import com.unvus.query.QueryTool;


/**
 * Service for {@link GsSlipAcnt}<br/>
 */
@Service
public class GsSlipAcntService {

    private final GsSlipAcntRepository gsSlipAcntRepository;

    public GsSlipAcntService(GsSlipAcntRepository gsSlipAcntRepository) {
        this.gsSlipAcntRepository = gsSlipAcntRepository;
    }

    //region ------------------------------------------------------------------------------------------------ gsSlipAcnt CRUD

    @Transactional
    public GsSlipAcnt saveGsSlipAcnt(GsSlipAcnt gsSlipAcnt) {
        if (gsSlipAcnt.getId() == null) {
            addGsSlipAcnt(gsSlipAcnt);
        } else {
            modifyGsSlipAcnt(gsSlipAcnt);
        }

        return gsSlipAcnt;
    }

    private int addGsSlipAcnt(GsSlipAcnt gsSlipAcnt) {
        int result = gsSlipAcntRepository.insertGsSlipAcnt(gsSlipAcnt);
        return result;
    }

    private int modifyGsSlipAcnt(GsSlipAcnt gsSlipAcnt) {
        int result = gsSlipAcntRepository.updateGsSlipAcnt(gsSlipAcnt);
        return result;
    }

    @Transactional
    public int removeGsSlipAcnt(Long id) {
        int rows = gsSlipAcntRepository.deleteGsSlipAcnt(id);
        return rows;
    }

    public GsSlipAcnt getGsSlipAcnt(Long id) {
        GsSlipAcnt gsSlipAcnt = gsSlipAcntRepository.getGsSlipAcnt(id);

        return gsSlipAcnt;
    }

    public int listGsSlipAcntCnt(Map<String, Object> params) {
        int rows = gsSlipAcntRepository.listGsSlipAcntCnt(params);
        return rows;
    }

    public List<GsSlipAcnt> listGsSlipAcnt(Map<String, Object> params) {
        List<GsSlipAcnt> lists = gsSlipAcntRepository.listGsSlipAcnt(params);

        return lists;
    }

    public List<GsSlipAcnt> listGsSlipAcntByIds(List<Long> ids, Map<String, Object> params) {
        params.put("ids", ids);
        QueryTool.setDefaultOrderBy(new OrderBy("ACNT_CODE", ids));
        List<GsSlipAcnt> lists = gsSlipAcntRepository.listGsSlipAcnt(params);

        return lists;
    }

    //endregion

}
