/*
 * Source code generated by UnvUS.
 * Copyright(c) 2017 unvus.com All rights reserved.
 * Template skrull-pack-mybatis:src/main/java/rest/Rest.e.vm.java
 * Template is part of project: https://git.unvus.com/unvus/opensource/pack-unvus-mybatis
 */
package com.neofect.gts.web.cms.rest.estorder;

import java.net.URISyntaxException;
import java.util.HashMap;
import java.util.List;
import java.util.Map;

import org.springframework.http.HttpHeaders;
import org.springframework.http.HttpStatus;
import org.springframework.http.MediaType;
import org.springframework.http.ResponseEntity;
import org.springframework.web.bind.annotation.*;

import com.google.common.collect.ImmutableMap;
import com.neofect.gts.core.services.estorder.domain.EstorderDetail;
import com.neofect.gts.core.services.estorder.service.EstorderDetailService;
import com.unvus.web.util.PaginationUtil;

import lombok.extern.slf4j.Slf4j;

/**
 * Rest for {@link EstorderDetail}<br/>
 */
@Slf4j
@RestController
@RequestMapping("/api")
public class EstorderDetailResource {

    private final EstorderDetailService estorderDetailService;

    public EstorderDetailResource(EstorderDetailService estorderDetailService) {
        this.estorderDetailService = estorderDetailService;
    }

    //region ------------------------------------------------------------------------------------------------ estorderDetail API

    /**
     *
     */
    @GetMapping(value = "/estorder-detail", produces = MediaType.APPLICATION_JSON_VALUE)
    public ResponseEntity<List<EstorderDetail>> listEstorderDetail(@RequestParam(value = "q", required = false) Map<String, Object> q)
            throws URISyntaxException {
        if (q == null) {
            q = new HashMap();
        }

        List<EstorderDetail> estorderDetailList = estorderDetailService.listEstorderDetail(q);

        HttpHeaders headers = PaginationUtil.generatePaginationHttpHeaders();

        return new ResponseEntity<>(estorderDetailList, headers, HttpStatus.OK);
    }

    /**
     * get count
     * @return
     */
    @GetMapping(value = "/estorder-detail/_count", produces = MediaType.APPLICATION_JSON_VALUE)
    public ResponseEntity<Map> getCount(@RequestParam(value = "q", required = false) Map<String, Object> q) {
        int count = estorderDetailService.listEstorderDetailCnt(q);

        return new ResponseEntity<>(ImmutableMap.of("count", count), HttpStatus.OK);
    }

    /**
     * get empty object
     * @return
     */
    @GetMapping(value = "/estorder-detail/_empty", produces = MediaType.APPLICATION_JSON_VALUE)
    public ResponseEntity<EstorderDetail> getEmptyEstorderDetail() {
        EstorderDetail estorderDetail = new EstorderDetail();
        return new ResponseEntity<>(estorderDetail, HttpStatus.OK);
    }

    /**
     * get
     */
    @GetMapping(value = "/estorder-detail/{id}", produces = MediaType.APPLICATION_JSON_VALUE)
    public ResponseEntity<EstorderDetail> getEstorderDetail(@PathVariable("id") Long id) {
        EstorderDetail estorderDetail = estorderDetailService.getEstorderDetail(id);
        return new ResponseEntity<>(estorderDetail, HttpStatus.OK);
    }

    /**
     * add
     */
    @PostMapping("/estorder-detail")
    public ResponseEntity<Void> addEstorderDetail(@RequestBody EstorderDetail estorderDetail) {
        estorderDetailService.saveEstorderDetail(estorderDetail);

        return ResponseEntity.ok().build();
    }

    /**
     * modify
     */
    @PutMapping("/estorder-detail/{id}")
    public ResponseEntity<Void> updateEstorderDetail(@PathVariable("id") Long id, @RequestBody EstorderDetail estorderDetail) throws Exception {
        // if (!id.equals(estorderDetail.getId())) {
        //     return new ResponseEntity(HttpStatus.BAD_REQUEST);
        // }
        estorderDetailService.saveEstorderDetail(estorderDetail);
        return ResponseEntity.ok().build();
    }

    /**
     * delete
     */
    @DeleteMapping("/estorder-detail/{id}")
    public ResponseEntity<Void> removeEstorderDetail(@PathVariable("id") Long id) {
        estorderDetailService.removeEstorderDetail(id);
        return ResponseEntity.ok().build();
    }

    //endregion

}
