/*
 * Source code generated by UnvUS.
 * Copyright(c) 2017 unvus.com All rights reserved.
 * Template skrull-pack-mybatis:src/main/java/domain/FieldBase.e.vm.java
 * Template is part of project: https://git.unvus.com/unvus/opensource/pack-unvus-mybatis
 */
package com.neofect.gts.core.services.user.domain.query.field;

import java.util.HashMap;
import java.util.Map;

import com.unvus.query.FieldUtil;
import com.unvus.query.frag.Field;

public interface PersistentTokenField_ {

    Map<String, Field> _FIELD_MAP = new HashMap<String, Field>() {
        {
            FieldUtil.toMap(this, new Field("id", "pt_id"));
            FieldUtil.toMap(this, new Field("series", "pt_series"));
            FieldUtil.toMap(this, new Field("tokenValue", "pt_token_value"));
            FieldUtil.toMap(this, new Field("tokenDate", "pt_token_date"));
            FieldUtil.toMap(this, new Field("ipAddress", "pt_ip_address"));
            FieldUtil.toMap(this, new Field("userAgent", "pt_user_agent"));
            FieldUtil.toMap(this, new Field("userKey", "pt_user_key"));
        }
    };

    String prefix();

    /**
    * 아이디
    */
    default Field id() {
        return new Field(prefix(), "id", "pt_id");
    }

    default Field id(String prefix) {
        return new Field(prefix, "id", "pt_id");
    }

    /**
    * 시리즈
    */
    default Field series() {
        return new Field(prefix(), "series", "pt_series");
    }

    default Field series(String prefix) {
        return new Field(prefix, "series", "pt_series");
    }

    /**
    * 토큰값
    */
    default Field tokenValue() {
        return new Field(prefix(), "tokenValue", "pt_token_value");
    }

    default Field tokenValue(String prefix) {
        return new Field(prefix, "tokenValue", "pt_token_value");
    }

    /**
    * 토큰일자
    */
    default Field tokenDate() {
        return new Field(prefix(), "tokenDate", "pt_token_date");
    }

    default Field tokenDate(String prefix) {
        return new Field(prefix, "tokenDate", "pt_token_date");
    }

    /**
    * 아이피
    */
    default Field ipAddress() {
        return new Field(prefix(), "ipAddress", "pt_ip_address");
    }

    default Field ipAddress(String prefix) {
        return new Field(prefix, "ipAddress", "pt_ip_address");
    }

    /**
    * 유저에이전트
    */
    default Field userAgent() {
        return new Field(prefix(), "userAgent", "pt_user_agent");
    }

    default Field userAgent(String prefix) {
        return new Field(prefix, "userAgent", "pt_user_agent");
    }

    /**
    * 사용자아이디
    */
    default Field userKey() {
        return new Field(prefix(), "userKey", "pt_user_key");
    }

    default Field userKey(String prefix) {
        return new Field(prefix, "userKey", "pt_user_key");
    }

}
