/*
 * Source code generated by UnvUS.
 * Copyright(c) 2017 unvus.com All rights reserved.
 * Template skrull-pack-mybatis:src/main/java/domain/FieldBase.e.vm.java
 * Template is part of project: https://git.unvus.com/unvus/opensource/pack-unvus-mybatis
 */
package com.neofect.gts.core.services.user.domain.query.field;

import java.util.HashMap;
import java.util.Map;

import com.unvus.query.FieldUtil;
import com.unvus.query.frag.Field;

public interface SubscribeAgreeField_ {

    Map<String, Field> _FIELD_MAP = new HashMap<String, Field>() {
        {
            FieldUtil.toMap(this, new Field("id", "sa_id"));
            FieldUtil.toMap(this, new Field("acntId", "sa_acnt_id"));
            FieldUtil.toMap(this, new Field("alertType", "sa_alert_type"));
            FieldUtil.toMap(this, new Field("chanelCode", "sa_chanel_code"));
            FieldUtil.toMap(this, new Field("agree", "sa_agree"));
            FieldUtil.toMap(this, new Field("modifiedDt", "sa_modified_dt"));
            FieldUtil.toMap(this, new Field("modifiedBy", "sa_modified_by"));
        }
    };

    String prefix();

    /**
    * 아이디
    */
    default Field id() {
        return new Field(prefix(), "id", "sa_id");
    }

    default Field id(String prefix) {
        return new Field(prefix, "id", "sa_id");
    }

    /**
    * 계정아이디
    */
    default Field acntId() {
        return new Field(prefix(), "acntId", "sa_acnt_id");
    }

    default Field acntId(String prefix) {
        return new Field(prefix, "acntId", "sa_acnt_id");
    }

    /**
    * 송신 내용타입
    */
    default Field alertType() {
        return new Field(prefix(), "alertType", "sa_alert_type");
    }

    default Field alertType(String prefix) {
        return new Field(prefix, "alertType", "sa_alert_type");
    }

    /**
    * 송신 채널코드
    */
    default Field chanelCode() {
        return new Field(prefix(), "chanelCode", "sa_chanel_code");
    }

    default Field chanelCode(String prefix) {
        return new Field(prefix, "chanelCode", "sa_chanel_code");
    }

    /**
    * 동의여부
    */
    default Field agree() {
        return new Field(prefix(), "agree", "sa_agree");
    }

    default Field agree(String prefix) {
        return new Field(prefix, "agree", "sa_agree");
    }

    /**
    * 수정일시
    */
    default Field modifiedDt() {
        return new Field(prefix(), "modifiedDt", "sa_modified_dt");
    }

    default Field modifiedDt(String prefix) {
        return new Field(prefix, "modifiedDt", "sa_modified_dt");
    }

    /**
    * 수정자
    */
    default Field modifiedBy() {
        return new Field(prefix(), "modifiedBy", "sa_modified_by");
    }

    default Field modifiedBy(String prefix) {
        return new Field(prefix, "modifiedBy", "sa_modified_by");
    }

}
