/*
 * Source code generated by UnvUS.
 * Copyright(c) 2017 unvus.com All rights reserved.
 * Template skrull-pack-mybatis:src/main/java/domain/EntityBase.e.vm.java
 * Template is part of project: https://git.unvus.com/unvus/opensource/pack-unvus-mybatis
 */
package com.neofect.gts.core.services.am.domain;

import java.io.Serializable;
import java.time.LocalDateTime;
import java.util.HashMap;
import java.util.Map;

import org.apache.ibatis.type.Alias;

import lombok.Data;

/**
 * AM_고정자산_종류코드
 */

/**
 * @see com.neofect.gts.core.services.am.domain.AmCodeKind
 */
@Alias("am_amCodeKind_")
@Data
public abstract class AmCodeKind_ implements Serializable {

    private static final long serialVersionUID = 1L;

    // Raw attributes
    /**
    * 회사코드
    */
    protected String companyCode;
    /**
    * 고정자산종류코드
    */
    protected String faKindCode;
    /**
    * 고정자산종류명칭
    */
    protected String faKindName;
    /**
    * 고정자산상각구분
    */
    protected String faRepayDiv;
    /**
    * 계정코드
    */
    protected String acntCode;
    /**
    * 계정코드_충당금
    */
    protected String acntCodeAppro;
    /**
    * 고정자산분류
    */
    protected String faDiv;
    /**
    * 계정코드_국고보조금
    */
    protected String acntCodeTreasury;
    /**
    * 유/무형자산구분
    */
    protected String materialityAssetTag;
    protected String rowInputEmpNo;
    protected LocalDateTime rowInputDate;
    protected String rowInputIp;
    protected String rowUpdateEmpNo;
    protected String rowUpdateDate;
    protected String rowUpdateIp;

    protected Map<String, Object> _meta = new HashMap();
}
