/*
 * Source code generated by UnvUS.
 * Copyright(c) 2017 unvus.com All rights reserved.
 * Template skrull-pack-mybatis:src/main/java/domain/EntityBase.e.vm.java
 * Template is part of project: https://git.unvus.com/unvus/opensource/pack-unvus-mybatis
 */
package com.neofect.gts.core.services.am.domain;

import java.io.Serializable;
import java.time.LocalDateTime;
import java.util.HashMap;
import java.util.Map;

import org.apache.ibatis.type.Alias;

import lombok.Data;

/**
 * @see com.neofect.gts.core.services.am.domain.AmCodeTaxcomp
 */
@Alias("am_amCodeTaxcomp_")
@Data
public abstract class AmCodeTaxcomp_ implements Serializable {

    private static final long serialVersionUID = 1L;

    // Raw attributes
    protected String companyCode;
    protected String taxCompCode;
    protected String taxCompName;
    protected String taxOfficeCode;
    protected String vendorNo;
    protected String vendorName;
    protected String vendorNameEng;
    protected String representName;
    protected String representRrn;
    protected String legalNo;
    protected String bizStatus;
    protected String bizType;
    protected String phone;
    protected String zipCode;
    protected String addr1;
    protected String addr2;
    protected String useYn;
    protected String slipEvidCntYn;
    protected String taxEvidIssueYn;
    protected String vatInYn;
    protected String vatOutYn;
    protected String inputDutyId;
    protected String inputDate;
    protected String chgDutyId;
    protected String chgDate;
    protected String rowInputEmpNo;
    protected LocalDateTime rowInputDate;
    protected String rowInputIp;
    protected String rowUpdateEmpNo;
    protected String rowUpdateDate;
    protected String rowUpdateIp;

    protected Map<String, Object> _meta = new HashMap();
}
