/*
 * Source code generated by UnvUS.
 * Copyright(c) 2017 unvus.com All rights reserved.
 * Template skrull-pack-mybatis:src/main/java/domain/EntityBase.e.vm.java
 * Template is part of project: https://git.unvus.com/unvus/opensource/pack-unvus-mybatis
 */
package com.neofect.gts.core.services.am.domain;

import java.io.Serializable;
import java.time.LocalDateTime;
import java.util.HashMap;
import java.util.Map;

import org.apache.ibatis.type.Alias;

import lombok.Data;

/**
 * AM_코드_전표종류
 */

/**
 * @see com.neofect.gts.core.services.am.domain.AmCodeSlipKind
 */
@Alias("am_amCodeSlipKind_")
@Data
public abstract class AmCodeSlipKind_ implements Serializable {

    private static final long serialVersionUID = 1L;

    // Raw attributes
    /**
    * 전표종류코드
    */
    protected String id;
    /**
    * 전표종류명칭
    */
    protected String slipKindName;
    /**
    * 전표처리시스템
    */
    protected String slipProcessDiv;
    /**
    * 자동발생여부
    */
    protected String autoYn;
    /**
    * 재무결산구분
    */
    protected String financeDiv;
    /**
    * 가전표수정구분
    */
    protected String deleteYn;
    /**
    * 매출증빙발행처리구분
    */
    protected String taxEvidIssueDiv;
    /**
    * 원가이체처리여부
    */
    protected String costTransYn;
    /**
    * 원가이체확정여부
    */
    protected String costConfirmYn;
    /**
    * 가전표경유여부
    */
    protected String workPassYn;
    protected String rowInputEmpNo;
    protected LocalDateTime rowInputDate;
    protected String rowInputIp;
    protected String rowUpdateEmpNo;
    protected String rowUpdateDate;
    protected String rowUpdateIp;

    protected Map<String, Object> _meta = new HashMap();
}
