/*
 * Source code generated by UnvUS.
 * Copyright(c) 2017 unvus.com All rights reserved.
 * Template skrull-pack-mybatis:src/main/java/domain/EntityBase.e.vm.java
 * Template is part of project: https://git.unvus.com/unvus/opensource/pack-unvus-mybatis
 */
package com.neofect.gts.core.services.am.domain;

import java.io.Serializable;
import java.time.LocalDateTime;
import java.util.HashMap;
import java.util.Map;

import org.apache.ibatis.type.Alias;

import lombok.Data;

/**
 * AM_코드_은행본점
 */

/**
 * @see com.neofect.gts.core.services.am.domain.AmCodeBankHead
 */
@Alias("am_amCodeBankHead_")
@Data
public abstract class AmCodeBankHead_ implements Serializable {

    private static final long serialVersionUID = 1L;

    // Raw attributes
    /**
    * 은행본점코드
    */
    protected String id;
    /**
    * 은행본점명칭
    */
    protected String bankHeadName;
    /**
    * 은행분류구분
    */
    protected String bankClsDiv;
    protected String rowInputEmpNo;
    protected LocalDateTime rowInputDate;
    protected String rowInputIp;
    protected String rowUpdateEmpNo;
    protected String rowUpdateDate;
    protected String rowUpdateIp;

    protected Map<String, Object> _meta = new HashMap();
}
