/*
 * Source code generated by UnvUS.
 * Copyright(c) 2017 unvus.com All rights reserved.
 * Template skrull-pack-mybatis:src/main/java/domain/EntityBase.e.vm.java
 * Template is part of project: https://git.unvus.com/unvus/opensource/pack-unvus-mybatis
 */
package com.neofect.gts.core.services.am.domain;

import java.io.Serializable;
import java.time.LocalDateTime;
import java.util.HashMap;
import java.util.Map;

import org.apache.ibatis.type.Alias;

import lombok.Data;

/**
 * AM_코드_부서
 */

/**
 * @see com.neofect.gts.core.services.am.domain.AmCodeDept
 */
@Alias("am_amCodeDept_")
@Data
public abstract class AmCodeDept_ implements Serializable {

    private static final long serialVersionUID = 1L;

    // Raw attributes
    /**
    * 회사코드
    */
    protected String companyCode;
    /**
    * 부서코드
    */
    protected String deptCode;
    /**
    * 세무회사코드
    */
    protected String taxCompCode;
    /**
    * 원가종류코드
    */
    protected String costKindCode;
    /**
    * 집계부서코드
    */
    protected String totalizeCode;
    /**
    * 예산대비부서코드
    */
    protected String bdgtDeptCode;
    /**
    * 내부명칭
    */
    protected String deptName;
    /**
    * 부서종류
    */
    protected String deptKind;
    /**
    * 사용여부
    */
    protected String useYn;
    /**
    * 외부명칭
    */
    protected String deptOutName;
    /**
    * 부서약칭
    */
    protected String deptAbbr;
    /**
    * 부서영문
    */
    protected String deptEng;
    /**
    * 부서한자
    */
    protected String deptChi;
    /**
    * 출력순위
    */
    protected Integer printOrder;
    /**
    * 불공제율
    */
    protected Double undeductRate;
    /**
    * 원천신고처코드
    */
    protected String sourReportDiv;
    /**
    * 공동공사여부
    */
    protected String joincontYn;
    /**
    * 면세여부
    */
    protected String vatYn;
    /**
    * 건설중인자산여부
    */
    protected String assetYn;
    /**
    * 입력담당
    */
    protected String inputDutyId;
    /**
    * 입력일시
    */
    protected String inputDate;
    /**
    * 변경담당
    */
    protected String chgDutyId;
    /**
    * 변경일시
    */
    protected String chgDate;
    protected String levelCode;
    protected String costCenterCode;
    protected String costDeptCode;
    protected String custCode;
    protected String rowInputEmpNo;
    protected LocalDateTime rowInputDate;
    protected String rowInputIp;
    protected String rowUpdateEmpNo;
    protected String rowUpdateDate;
    protected String rowUpdateIp;

    protected Map<String, Object> _meta = new HashMap();
}
