/*
 * Source code generated by UnvUS.
 * Copyright(c) 2017 unvus.com All rights reserved.
 * Template skrull-pack-mybatis:src/main/java/domain/EntityBase.e.vm.java
 * Template is part of project: https://git.unvus.com/unvus/opensource/pack-unvus-mybatis
 */
package com.neofect.gts.core.services.slip.domain;

import java.io.Serializable;
import java.math.BigDecimal;
import java.time.LocalDateTime;
import java.util.HashMap;
import java.util.Map;

import org.apache.ibatis.type.Alias;

import lombok.Data;

/**
 * 전표판매_상세
 */

/**
 * @see com.neofect.gts.core.services.slip.domain.SlipSaleDetail
 */
@Alias("slip_slipSaleDetail_")
@Data
public abstract class SlipSaleDetail_ implements Serializable {

    private static final long serialVersionUID = 1L;

    // Raw attributes
    /**
    * 전표일자
    */
    protected LocalDateTime slipDate;
    /**
    * 지사ID
    */
    protected String deptId;
    /**
    * 전표번호
    */
    protected Integer slipSeq;
    /**
    * 전표순번 단 수금일경우 999부터 역 세팅
    */
    protected Integer slipItem;
    /**
    * 판매/대여/요양/지사판매/지사대여
    */
    protected String sslipDiv;
    /**
    * 수입 : 개인분담금/구청청구금/지사판매금/지사대여금
    */
    protected String incomeDiv;
    protected Integer custId;
    /**
    * 거래처코드
    */
    protected String custCode;
    /**
    * 거래처명
    */
    protected String custName;
    /**
    * 품목ID
    */
    protected Integer productId;
    /**
    * 수량
    */
    protected Integer qty;
    /**
    * 단가
    */
    protected Long damt;
    /**
    * 금액
    */
    protected Long amt;
    /**
    * 공급가액
    */
    protected Long supplyAmt;
    /**
    * 부가세액
    */
    protected Long vatAmt;
    /**
    * 적요
    */
    protected String remark;
    /**
    * 창고코드
    */
    protected String wareDiv;
    /**
    * 입출고여부 매입 입고 Y, 매출 출고 Y
    */
    protected String inoutYn;
    /**
    * 박스단위
    */
    protected String unitDiv;
    /**
    * 박스수량
    */
    protected Integer unitqty;
    /**
    * 고객구분코드
    */
    protected String custGubunDiv;
    /**
    * 고객등급코드
    */
    protected String custLevelDiv;
    /**
    * 적요요율률
    */
    protected String appRateDiv;
    /**
    * 경감구분코드
    */
    protected String reductionDiv;
    /**
    * 요양인정번호
    */
    protected String manageNo;
    /**
    * 장기요양결과
    */
    protected String longtermDiv;
    /**
    * 서비스개시일
    */
    protected LocalDateTime startDate;
    /**
    * 서비스종료일
    */
    protected LocalDateTime endDate;
    /**
    * 일수
    */
    protected Integer supplyDays;
    /**
    * 본인부담금
    */
    protected Long payAmt;
    /**
    * 청구금액
    */
    protected Long reqAmt;
    /**
    * 월잔여요양비용
    */
    protected Long remainAmt;
    /**
    * 보장기관코드
    */
    protected String manageOfficeDiv;
    /**
    * 구청청구번호
    */
    protected String reqNo;
    /**
    * 소개사번
    */
    protected String introId;
    /**
    * 소개율
    */
    protected Double introRate;
    /**
    * 카드사용여부
    */
    protected String cardYn;
    /**
    * 출납전표일자
    */
    protected String cslipDate;
    /**
    * 출납지사ID
    */
    protected String cdeptId;
    /**
    * 출납전표번호
    */
    protected String cslipSeq;
    /**
    * 출납전표순번
    */
    protected String cslipItem;
    /**
    * 은행구분
    */
    protected String bankDiv;
    /**
    * 계좌번호
    */
    protected String depositno;
    /**
    * 현금결재
    */
    protected Long cashAmt;
    /**
    * 카드결재
    */
    protected Long cardAmt;
    /**
    * 미수금
    */
    protected Long misuAmt;
    /**
    * 무통장결재
    */
    protected Long bankAmt;
    /**
    * 구청청구일자
    */
    protected LocalDateTime reqDate;
    /**
    * 구청반제여부
    */
    protected String reqYn;
    /**
    * 구청반제일자
    */
    protected LocalDateTime reqRedate;
    protected String eslipDiv;
    protected LocalDateTime eslipDate;
    protected String edeptId;
    protected Integer eslipSeq;
    protected Integer eslipItem;
    /**
    * 원가_단가
    */
    protected BigDecimal costUnitcost;
    /**
    * 원가_금액
    */
    protected Long costAmt;
    /**
    * 입고항목 SLIP_DATE
    */
    protected LocalDateTime buySlipDate;
    /**
    * 입고항목 DEPT_ID
    */
    protected String buyDeptId;
    /**
    * 입고항목 SLIP_SEQ
    */
    protected Integer buySlipSeq;
    /**
    * 입고항목 SLIP_ITEM
    */
    protected Integer buySlipItem;
    protected String proxyDeptid;
    protected String useDiv;
    /**
    * 수량_판매용
    */
    protected Integer qty1;
    /**
    * 수량_대여용
    */
    protected Integer qty2;
    /**
    * 수량_비치용
    */
    protected Integer qty3;
    /**
    * 대여물품 product_id
    */
    protected Integer rentProductId;
    /**
    * 출력회수
    */
    protected Integer printcnt;
    /**
    * 출력일자
    */
    protected LocalDateTime printdate;
    /**
    * 판매 종류(고객, 지사간..)
    */
    protected String slipKind;
    /**
    * 공단지원금 수금금액
    */
    protected Long reqReceiptAmt;
    protected String subulCode;
    /**
    * 판매금액(반품차감)
    */
    protected Long amtReturn;
    /**
    * 공급가액(반품차감)
    */
    protected Long supplyAmtReturn;
    /**
    * 부가세금액(반품차감)
    */
    protected Long vatAmtReturn;
    /**
    * 본인부담금(반품차감)
    */
    protected Long payAmtReturn;
    /**
    * 공단지원금(반품차감)
    */
    protected Long reqAmtReturn;
    /**
    * 반품수량
    */
    protected Long qtyReturn;
    protected Double incentiveRate;
    protected Long incentiveAmt;
    protected String introId2;
    protected Double incentiveRate2;
    protected Long incentiveAmt2;
    protected String introId3;
    protected Double incentiveRate3;
    protected Long incentiveAmt3;
    /**
    * 세금계산서 출력여부
    */
    protected String taxinvoiceYn;
    protected String saleStatus;
    protected String rowInputEmpNo;
    protected LocalDateTime rowInputDate;
    protected String rowInputIp;
    protected String rowUpdateEmpNo;
    protected String rowUpdateDate;
    protected String rowUpdateIp;

    protected Map<String, Object> _meta = new HashMap();
}
