/*
 * Source code generated by UnvUS.
 * Copyright(c) 2017 unvus.com All rights reserved.
 * Template skrull-pack-mybatis:src/main/java/rest/Rest.e.vm.java
 * Template is part of project: https://git.unvus.com/unvus/opensource/pack-unvus-mybatis
 */
package com.neofect.gts.web.cms.rest.gs;

import java.net.URISyntaxException;
import java.util.HashMap;
import java.util.List;
import java.util.Map;

import org.springframework.http.HttpHeaders;
import org.springframework.http.HttpStatus;
import org.springframework.http.MediaType;
import org.springframework.http.ResponseEntity;
import org.springframework.web.bind.annotation.*;

import com.google.common.collect.ImmutableMap;
import com.neofect.gts.core.services.gs.domain.GsSlipAcnt;
import com.neofect.gts.core.services.gs.service.GsSlipAcntService;
import com.unvus.web.util.PaginationUtil;

import lombok.extern.slf4j.Slf4j;

/**
 * Rest for {@link GsSlipAcnt}<br/>
 */
@Slf4j
@RestController
@RequestMapping("/api")
public class GsSlipAcntResource {

    private final GsSlipAcntService gsSlipAcntService;

    public GsSlipAcntResource(GsSlipAcntService gsSlipAcntService) {
        this.gsSlipAcntService = gsSlipAcntService;
    }

    //region ------------------------------------------------------------------------------------------------ gsSlipAcnt API

    /**
     *
     */
    @GetMapping(value = "/gs-slip-acnt", produces = MediaType.APPLICATION_JSON_VALUE)
    public ResponseEntity<List<GsSlipAcnt>> listGsSlipAcnt(@RequestParam(value = "q", required = false) Map<String, Object> q) throws URISyntaxException {
        if (q == null) {
            q = new HashMap();
        }

        List<GsSlipAcnt> gsSlipAcntList = gsSlipAcntService.listGsSlipAcnt(q);

        HttpHeaders headers = PaginationUtil.generatePaginationHttpHeaders();

        return new ResponseEntity<>(gsSlipAcntList, headers, HttpStatus.OK);
    }

    /**
     * get count
     * @return
     */
    @GetMapping(value = "/gs-slip-acnt/_count", produces = MediaType.APPLICATION_JSON_VALUE)
    public ResponseEntity<Map> getCount(@RequestParam(value = "q", required = false) Map<String, Object> q) {
        int count = gsSlipAcntService.listGsSlipAcntCnt(q);

        return new ResponseEntity<>(ImmutableMap.of("count", count), HttpStatus.OK);
    }

    /**
     * get empty object
     * @return
     */
    @GetMapping(value = "/gs-slip-acnt/_empty", produces = MediaType.APPLICATION_JSON_VALUE)
    public ResponseEntity<GsSlipAcnt> getEmptyGsSlipAcnt() {
        GsSlipAcnt gsSlipAcnt = new GsSlipAcnt();
        return new ResponseEntity<>(gsSlipAcnt, HttpStatus.OK);
    }

    /**
     * get
     */
    @GetMapping(value = "/gs-slip-acnt/{id}", produces = MediaType.APPLICATION_JSON_VALUE)
    public ResponseEntity<GsSlipAcnt> getGsSlipAcnt(@PathVariable("id") Long id) {
        GsSlipAcnt gsSlipAcnt = gsSlipAcntService.getGsSlipAcnt(id);
        return new ResponseEntity<>(gsSlipAcnt, HttpStatus.OK);
    }

    /**
     * add
     */
    @PostMapping("/gs-slip-acnt")
    public ResponseEntity<Void> addGsSlipAcnt(@RequestBody GsSlipAcnt gsSlipAcnt) {
        gsSlipAcntService.saveGsSlipAcnt(gsSlipAcnt);

        return ResponseEntity.ok().build();
    }

    /**
     * modify
     */
    @PutMapping("/gs-slip-acnt/{id}")
    public ResponseEntity<Void> updateGsSlipAcnt(@PathVariable("id") Long id, @RequestBody GsSlipAcnt gsSlipAcnt) throws Exception {
        if (!id.equals(gsSlipAcnt.getId())) {
            return new ResponseEntity(HttpStatus.BAD_REQUEST);
        }
        gsSlipAcntService.saveGsSlipAcnt(gsSlipAcnt);
        return ResponseEntity.ok().build();
    }

    /**
     * delete
     */
    @DeleteMapping("/gs-slip-acnt/{id}")
    public ResponseEntity<Void> removeGsSlipAcnt(@PathVariable("id") Long id) {
        gsSlipAcntService.removeGsSlipAcnt(id);
        return ResponseEntity.ok().build();
    }

    //endregion

}
