/*
 * Source code generated by UnvUS.
 * Copyright(c) 2017 unvus.com All rights reserved.
 * Template skrull-pack-mybatis:src/main/java/rest/Rest.e.vm.java
 * Template is part of project: https://git.unvus.com/unvus/opensource/pack-unvus-mybatis
 */
package com.neofect.gts.web.cms.rest.gs;

import java.net.URISyntaxException;
import java.util.HashMap;
import java.util.List;
import java.util.Map;

import org.springframework.http.HttpHeaders;
import org.springframework.http.HttpStatus;
import org.springframework.http.MediaType;
import org.springframework.http.ResponseEntity;
import org.springframework.web.bind.annotation.*;

import com.google.common.collect.ImmutableMap;
import com.neofect.gts.core.services.gs.domain.IncentiveReceipt;
import com.neofect.gts.core.services.gs.service.IncentiveReceiptService;
import com.unvus.web.util.PaginationUtil;

import lombok.extern.slf4j.Slf4j;

/**
 * Rest for {@link IncentiveReceipt}<br/>
 */
@Slf4j
@RestController
@RequestMapping("/api")
public class IncentiveReceiptResource {

    private final IncentiveReceiptService incentiveReceiptService;

    public IncentiveReceiptResource(IncentiveReceiptService incentiveReceiptService) {
        this.incentiveReceiptService = incentiveReceiptService;
    }

    //region ------------------------------------------------------------------------------------------------ incentiveReceipt API

    /**
     *
     */
    @GetMapping(value = "/incentive-receipt", produces = MediaType.APPLICATION_JSON_VALUE)
    public ResponseEntity<List<IncentiveReceipt>> listIncentiveReceipt(@RequestParam(value = "q", required = false) Map<String, Object> q)
            throws URISyntaxException {
        if (q == null) {
            q = new HashMap();
        }

        List<IncentiveReceipt> incentiveReceiptList = incentiveReceiptService.listIncentiveReceipt(q);

        HttpHeaders headers = PaginationUtil.generatePaginationHttpHeaders();

        return new ResponseEntity<>(incentiveReceiptList, headers, HttpStatus.OK);
    }

    /**
     * get count
     * @return
     */
    @GetMapping(value = "/incentive-receipt/_count", produces = MediaType.APPLICATION_JSON_VALUE)
    public ResponseEntity<Map> getCount(@RequestParam(value = "q", required = false) Map<String, Object> q) {
        int count = incentiveReceiptService.listIncentiveReceiptCnt(q);

        return new ResponseEntity<>(ImmutableMap.of("count", count), HttpStatus.OK);
    }

    /**
     * get empty object
     * @return
     */
    @GetMapping(value = "/incentive-receipt/_empty", produces = MediaType.APPLICATION_JSON_VALUE)
    public ResponseEntity<IncentiveReceipt> getEmptyIncentiveReceipt() {
        IncentiveReceipt incentiveReceipt = new IncentiveReceipt();
        return new ResponseEntity<>(incentiveReceipt, HttpStatus.OK);
    }

    /**
     * get
     */
    @GetMapping(value = "/incentive-receipt/{id}", produces = MediaType.APPLICATION_JSON_VALUE)
    public ResponseEntity<IncentiveReceipt> getIncentiveReceipt(@PathVariable("id") Long id) {
        IncentiveReceipt incentiveReceipt = incentiveReceiptService.getIncentiveReceipt(id);
        return new ResponseEntity<>(incentiveReceipt, HttpStatus.OK);
    }

    /**
     * add
     */
    @PostMapping("/incentive-receipt")
    public ResponseEntity<Void> addIncentiveReceipt(@RequestBody IncentiveReceipt incentiveReceipt) {
        incentiveReceiptService.saveIncentiveReceipt(incentiveReceipt);

        return ResponseEntity.ok().build();
    }

    /**
     * modify
     */
    @PutMapping("/incentive-receipt/{id}")
    public ResponseEntity<Void> updateIncentiveReceipt(@PathVariable("id") Long id, @RequestBody IncentiveReceipt incentiveReceipt) throws Exception {
        // if (!id.equals(incentiveReceipt.getId())) {
        //     return new ResponseEntity(HttpStatus.BAD_REQUEST);
        // }
        incentiveReceiptService.saveIncentiveReceipt(incentiveReceipt);
        return ResponseEntity.ok().build();
    }

    /**
     * delete
     */
    @DeleteMapping("/incentive-receipt/{id}")
    public ResponseEntity<Void> removeIncentiveReceipt(@PathVariable("id") Long id) {
        incentiveReceiptService.removeIncentiveReceipt(id);
        return ResponseEntity.ok().build();
    }

    //endregion

}
