/*
 * Source code generated by UnvUS.
 * Copyright(c) 2017 unvus.com All rights reserved.
 * Template skrull-pack-mybatis:src/main/java/repository/Repository.e.vm.java
 * Template is part of project: https://git.unvus.com/unvus/opensource/pack-unvus-mybatis
 */
package com.neofect.gts.core.services.common.repository;

import java.util.List;
import java.util.Map;

import org.springframework.stereotype.Repository;

import com.neofect.gts.core.services.common.domain.CodeCustprotector;
import com.unvus.config.mybatis.pagination.Pageable;
import com.unvus.config.mybatis.support.DefaultMapper;

/**
 * Repository for {@link CodeCustprotector}<br/>
 * Available methods are.. <br/>
 * <ul>
 * <li>CodeCustprotector getCodeCustprotector(Long id);</li>
 * <li>int listCodeCustprotectorCnt(Map<String, Object> params);</li>
 * <li>List<CodeCustprotector> listCodeCustprotector(Map<String, Object> params);</li>
 * <li>int insertCodeCustprotector(CodeCustprotector codecustprotector);</li>
 * <li>int updateCodeCustprotector(CodeCustprotector codecustprotector);</li>
 * <li>int deleteCodeCustprotector(Long id);</li>
 * </ul>
 */
@DefaultMapper
@Repository
public interface CodeCustprotectorRepository extends CodeCustprotectorRepository_ {
    CodeCustprotector getCodeCustprotector(Long id);

    int listCodeCustprotectorCnt(Map<String, Object> params);

    /**
     * if yuou want to avoid result objects less than dataPerPage caused by "1:N mappings".. <br/>
     * add function that return "distinct id list" and name it with : <br/>
     * <code>List<Long> listCodeCustprotectorIds(Map<String, Object> params)</code> <br/>
     * and replace @Pageable with :  <br/>
     * <code>@Pageable(useMergeQuery = true)</code> <br/>
     */
    @Pageable
    List<CodeCustprotector> listCodeCustprotector(Map<String, Object> params);

    List<Long> listCodeCustprotectorIds(Map<String, Object> params);

}
