/*
 * Source code generated by UnvUS.
 * Copyright(c) 2017 unvus.com All rights reserved.
 * Template skrull-pack-mybatis:src/main/java/repository/Repository.e.vm.java
 * Template is part of project: https://git.unvus.com/unvus/opensource/pack-unvus-mybatis
 */
package com.neofect.gts.core.services.common.repository;

import java.util.List;
import java.util.Map;

import org.springframework.stereotype.Repository;

import com.neofect.gts.core.services.common.domain.CodeCard;
import com.unvus.config.mybatis.pagination.Pageable;
import com.unvus.config.mybatis.support.DefaultMapper;

/**
 * Repository for {@link CodeCard}<br/>
 * Available methods are.. <br/>
 * <ul>
 * <li>CodeCard getCodeCard(Long id);</li>
 * <li>int listCodeCardCnt(Map<String, Object> params);</li>
 * <li>List<CodeCard> listCodeCard(Map<String, Object> params);</li>
 * <li>int insertCodeCard(CodeCard codecard);</li>
 * <li>int updateCodeCard(CodeCard codecard);</li>
 * <li>int deleteCodeCard(Long id);</li>
 * </ul>
 */
@DefaultMapper
@Repository
public interface CodeCardRepository extends CodeCardRepository_ {
    CodeCard getCodeCard(Long id);

    int listCodeCardCnt(Map<String, Object> params);

    /**
     * if yuou want to avoid result objects less than dataPerPage caused by "1:N mappings".. <br/>
     * add function that return "distinct id list" and name it with : <br/>
     * <code>List<Long> listCodeCardIds(Map<String, Object> params)</code> <br/>
     * and replace @Pageable with :  <br/>
     * <code>@Pageable(useMergeQuery = true)</code> <br/>
     */
    @Pageable
    List<CodeCard> listCodeCard(Map<String, Object> params);

    List<Long> listCodeCardIds(Map<String, Object> params);

}
