/*
 * Source code generated by UnvUS.
 * Copyright(c) 2017 unvus.com All rights reserved.
 * Template skrull-pack-mybatis:src/main/java/repository/Repository.e.vm.java
 * Template is part of project: https://git.unvus.com/unvus/opensource/pack-unvus-mybatis
 */
package com.neofect.gts.core.services.common.repository;

import java.util.List;
import java.util.Map;

import org.springframework.stereotype.Repository;

import com.neofect.gts.core.services.common.domain.CodeDeptAuthority;
import com.unvus.config.mybatis.pagination.Pageable;
import com.unvus.config.mybatis.support.DefaultMapper;

/**
 * Repository for {@link CodeDeptAuthority}<br/>
 * Available methods are.. <br/>
 * <ul>
 * <li>CodeDeptAuthority getCodeDeptAuthority(Long id);</li>
 * <li>int listCodeDeptAuthorityCnt(Map<String, Object> params);</li>
 * <li>List<CodeDeptAuthority> listCodeDeptAuthority(Map<String, Object> params);</li>
 * <li>int insertCodeDeptAuthority(CodeDeptAuthority codedeptauthority);</li>
 * <li>int updateCodeDeptAuthority(CodeDeptAuthority codedeptauthority);</li>
 * <li>int deleteCodeDeptAuthority(Long id);</li>
 * </ul>
 */
@DefaultMapper
@Repository
public interface CodeDeptAuthorityRepository extends CodeDeptAuthorityRepository_ {
    CodeDeptAuthority getCodeDeptAuthority(Long id);

    int listCodeDeptAuthorityCnt(Map<String, Object> params);

    /**
     * if yuou want to avoid result objects less than dataPerPage caused by "1:N mappings".. <br/>
     * add function that return "distinct id list" and name it with : <br/>
     * <code>List<Long> listCodeDeptAuthorityIds(Map<String, Object> params)</code> <br/>
     * and replace @Pageable with :  <br/>
     * <code>@Pageable(useMergeQuery = true)</code> <br/>
     */
    @Pageable
    List<CodeDeptAuthority> listCodeDeptAuthority(Map<String, Object> params);

    List<Long> listCodeDeptAuthorityIds(Map<String, Object> params);

}
