/*
 * Source code generated by UnvUS.
 * Copyright(c) 2017 unvus.com All rights reserved.
 * Template skrull-pack-mybatis:src/main/java/repository/Repository.e.vm.java
 * Template is part of project: https://git.unvus.com/unvus/opensource/pack-unvus-mybatis
 */
package com.neofect.gts.core.services.common.repository;

import java.util.List;
import java.util.Map;

import com.neofect.gts.core.services.common.domain.LabelValue;
import org.springframework.stereotype.Repository;

import com.unvus.config.mybatis.pagination.Pageable;
import com.unvus.config.mybatis.support.DefaultMapper;
import com.neofect.gts.core.services.common.domain.LabelValue;

/**
 * Repository for {@link LabelValue}<br/>
 * Available methods are.. <br/>
 * <ul>
 * <li>LabelValue getLabelValue(Long id);</li>
 * <li>int listLabelValueCnt(Map<String, Object> params);</li>
 * <li>List<LabelValue> listLabelValue(Map<String, Object> params);</li>
 * <li>int insertLabelValue(LabelValue labelvalue);</li>
 * <li>int updateLabelValue(LabelValue labelvalue);</li>
 * <li>int deleteLabelValue(Long id);</li>
 * </ul>
 */
@DefaultMapper
@Repository
public interface LabelValueRepository extends LabelValueRepository_ {
    LabelValue getLabelValue(Long id);

    int listLabelValueCnt(Map<String, Object> params);

    /**
     * if yuou want to avoid result objects less than dataPerPage caused by "1:N mappings".. <br/>
     * add function that return "distinct id list" and name it with : <br/>
     * <code>List<Long> listLabelValueIds(Map<String, Object> params)</code> <br/>
     * and replace @Pageable with :  <br/>
     * <code>@Pageable(useMergeQuery = true)</code> <br/>
     */
    @Pageable
    List<LabelValue> listLabelValue(Map<String, Object> params);

    List<Long> listLabelValueIds(Map<String, Object> params);

}
