/*
 * Source code generated by UnvUS.
 * Copyright(c) 2017 unvus.com All rights reserved.
 * Template skrull-pack-mybatis:src/main/java/repository/Repository.e.vm.java
 * Template is part of project: https://git.unvus.com/unvus/opensource/pack-unvus-mybatis
 */
package com.neofect.gts.core.services.srvce.repository;

import java.util.List;
import java.util.Map;

import org.springframework.stereotype.Repository;

import com.neofect.gts.core.services.srvce.domain.ServicePayReceipt;
import com.unvus.config.mybatis.pagination.Pageable;
import com.unvus.config.mybatis.support.DefaultMapper;

/**
 * Repository for {@link ServicePayReceipt}<br/>
 * Available methods are.. <br/>
 * <ul>
 * <li>ServicePayReceipt getServicePayReceipt(Long id);</li>
 * <li>int listServicePayReceiptCnt(Map<String, Object> params);</li>
 * <li>List<ServicePayReceipt> listServicePayReceipt(Map<String, Object> params);</li>
 * <li>int insertServicePayReceipt(ServicePayReceipt servicepayreceipt);</li>
 * <li>int updateServicePayReceipt(ServicePayReceipt servicepayreceipt);</li>
 * <li>int deleteServicePayReceipt(Long id);</li>
 * </ul>
 */
@DefaultMapper
@Repository
public interface ServicePayReceiptRepository extends ServicePayReceiptRepository_ {
    ServicePayReceipt getServicePayReceipt(Long id);

    int listServicePayReceiptCnt(Map<String, Object> params);

    /**
     * if yuou want to avoid result objects less than dataPerPage caused by "1:N mappings".. <br/>
     * add function that return "distinct id list" and name it with : <br/>
     * <code>List<Long> listServicePayReceiptIds(Map<String, Object> params)</code> <br/>
     * and replace @Pageable with :  <br/>
     * <code>@Pageable(useMergeQuery = true)</code> <br/>
     */
    @Pageable
    List<ServicePayReceipt> listServicePayReceipt(Map<String, Object> params);

    List<Long> listServicePayReceiptIds(Map<String, Object> params);

}
