/*
 * Source code generated by UnvUS.
 * Copyright(c) 2017 unvus.com All rights reserved.
 * Template skrull-pack-mybatis:src/main/java/repository/Repository.e.vm.java
 * Template is part of project: https://git.unvus.com/unvus/opensource/pack-unvus-mybatis
 */
package com.neofect.gts.core.services.srvce.repository;

import java.util.List;
import java.util.Map;

import org.springframework.stereotype.Repository;

import com.neofect.gts.core.services.srvce.domain.ServiceSummary;
import com.unvus.config.mybatis.pagination.Pageable;
import com.unvus.config.mybatis.support.DefaultMapper;

/**
 * Repository for {@link ServiceSummary}<br/>
 * Available methods are.. <br/>
 * <ul>
 * <li>ServiceSummary getServiceSummary(Long id);</li>
 * <li>int listServiceSummaryCnt(Map<String, Object> params);</li>
 * <li>List<ServiceSummary> listServiceSummary(Map<String, Object> params);</li>
 * <li>int insertServiceSummary(ServiceSummary servicesummary);</li>
 * <li>int updateServiceSummary(ServiceSummary servicesummary);</li>
 * <li>int deleteServiceSummary(Long id);</li>
 * </ul>
 */
@DefaultMapper
@Repository
public interface ServiceSummaryRepository extends ServiceSummaryRepository_ {
    ServiceSummary getServiceSummary(Long id);

    int listServiceSummaryCnt(Map<String, Object> params);

    /**
     * if yuou want to avoid result objects less than dataPerPage caused by "1:N mappings".. <br/>
     * add function that return "distinct id list" and name it with : <br/>
     * <code>List<Long> listServiceSummaryIds(Map<String, Object> params)</code> <br/>
     * and replace @Pageable with :  <br/>
     * <code>@Pageable(useMergeQuery = true)</code> <br/>
     */
    @Pageable
    List<ServiceSummary> listServiceSummary(Map<String, Object> params);

    List<Long> listServiceSummaryIds(Map<String, Object> params);

}
