/*
 * Source code generated by UnvUS.
 * Copyright(c) 2017 unvus.com All rights reserved.
 * Template skrull-pack-mybatis:src/main/java/repository/RepositoryBase.e.vm.java
 * Template is part of project: https://git.unvus.com/unvus/opensource/pack-unvus-mybatis
 */
package com.neofect.gts.core.services.srvce.repository;

import java.util.List;
import java.util.Map;

import org.springframework.stereotype.Repository;

import com.neofect.gts.core.services.srvce.domain.ServiceSupplySchedule;
import com.unvus.config.mybatis.pagination.Pageable;
import com.unvus.config.mybatis.support.DefaultMapper;

/**
 * Repository for {@link ServiceSupplySchedule}
 * @see com.neofect.gts.core.services.srvce.repository.ServiceSupplyScheduleRepository
 */
@DefaultMapper
@Repository
public interface ServiceSupplyScheduleRepository_ {

    ServiceSupplySchedule simpleGetServiceSupplySchedule(Long id);

    int simpleListServiceSupplyScheduleCnt(Map<String, Object> params);

    /**
     * if yuou want to avoid result objects less than dataPerPage caused by "1:N mappings".. <br/>
     * add function that return "distinct id list" and name it with : <br/>
     * <code>List<Long> listServiceSupplyScheduleIds(Map<String, Object> params)</code> <br/>
     * and replace @Pageable with :  <br/>
     * <code>@Pageable(useMergeQuery = true)</code> <br/>
     */
    @Pageable
    List<ServiceSupplySchedule> simpleListServiceSupplySchedule(Map<String, Object> params);

    int insertServiceSupplySchedule(ServiceSupplySchedule serviceSupplySchedule);

    int updateServiceSupplySchedule(ServiceSupplySchedule serviceSupplySchedule);

    int updateServiceSupplyScheduleDynamic(ServiceSupplySchedule serviceSupplySchedule);

    int deleteServiceSupplySchedule(Long id);

}
