/*
 * Source code generated by UnvUS.
 * Copyright(c) 2017 unvus.com All rights reserved.
 * Template skrull-pack-mybatis:src/main/java/rest/Rest.e.vm.java
 * Template is part of project: https://git.unvus.com/unvus/opensource/pack-unvus-mybatis
 */
package com.neofect.gts.web.cms.rest.srvce;

import java.net.URISyntaxException;
import java.util.HashMap;
import java.util.List;
import java.util.Map;

import org.springframework.http.HttpHeaders;
import org.springframework.http.HttpStatus;
import org.springframework.http.MediaType;
import org.springframework.http.ResponseEntity;
import org.springframework.web.bind.annotation.*;

import com.google.common.collect.ImmutableMap;
import com.neofect.gts.core.services.srvce.domain.ServicePayReceipt;
import com.neofect.gts.core.services.srvce.service.ServicePayReceiptService;
import com.unvus.web.util.PaginationUtil;

import lombok.extern.slf4j.Slf4j;

/**
 * Rest for {@link ServicePayReceipt}<br/>
 */
@Slf4j
@RestController
@RequestMapping("/api")
public class ServicePayReceiptResource {

    private final ServicePayReceiptService servicePayReceiptService;

    public ServicePayReceiptResource(ServicePayReceiptService servicePayReceiptService) {
        this.servicePayReceiptService = servicePayReceiptService;
    }

    //region ------------------------------------------------------------------------------------------------ servicePayReceipt API

    /**
     *
     */
    @GetMapping(value = "/service-pay-receipt", produces = MediaType.APPLICATION_JSON_VALUE)
    public ResponseEntity<List<ServicePayReceipt>> listServicePayReceipt(@RequestParam(value = "q", required = false) Map<String, Object> q)
            throws URISyntaxException {
        if (q == null) {
            q = new HashMap();
        }

        List<ServicePayReceipt> servicePayReceiptList = servicePayReceiptService.listServicePayReceipt(q);

        HttpHeaders headers = PaginationUtil.generatePaginationHttpHeaders();

        return new ResponseEntity<>(servicePayReceiptList, headers, HttpStatus.OK);
    }

    /**
     * get count
     * @return
     */
    @GetMapping(value = "/service-pay-receipt/_count", produces = MediaType.APPLICATION_JSON_VALUE)
    public ResponseEntity<Map> getCount(@RequestParam(value = "q", required = false) Map<String, Object> q) {
        int count = servicePayReceiptService.listServicePayReceiptCnt(q);

        return new ResponseEntity<>(ImmutableMap.of("count", count), HttpStatus.OK);
    }

    /**
     * get empty object
     * @return
     */
    @GetMapping(value = "/service-pay-receipt/_empty", produces = MediaType.APPLICATION_JSON_VALUE)
    public ResponseEntity<ServicePayReceipt> getEmptyServicePayReceipt() {
        ServicePayReceipt servicePayReceipt = new ServicePayReceipt();
        return new ResponseEntity<>(servicePayReceipt, HttpStatus.OK);
    }

    /**
     * get
     */
    @GetMapping(value = "/service-pay-receipt/{id}", produces = MediaType.APPLICATION_JSON_VALUE)
    public ResponseEntity<ServicePayReceipt> getServicePayReceipt(@PathVariable("id") Long id) {
        ServicePayReceipt servicePayReceipt = servicePayReceiptService.getServicePayReceipt(id);
        return new ResponseEntity<>(servicePayReceipt, HttpStatus.OK);
    }

    /**
     * add
     */
    @PostMapping("/service-pay-receipt")
    public ResponseEntity<Void> addServicePayReceipt(@RequestBody ServicePayReceipt servicePayReceipt) {
        servicePayReceiptService.saveServicePayReceipt(servicePayReceipt);

        return ResponseEntity.ok().build();
    }

    /**
     * modify
     */
    @PutMapping("/service-pay-receipt/{id}")
    public ResponseEntity<Void> updateServicePayReceipt(@PathVariable("id") Long id, @RequestBody ServicePayReceipt servicePayReceipt) throws Exception {
        // if (!id.equals(servicePayReceipt.getId())) {
        //     return new ResponseEntity(HttpStatus.BAD_REQUEST);
        // }
        servicePayReceiptService.saveServicePayReceipt(servicePayReceipt);
        return ResponseEntity.ok().build();
    }

    /**
     * delete
     */
    @DeleteMapping("/service-pay-receipt/{id}")
    public ResponseEntity<Void> removeServicePayReceipt(@PathVariable("id") Long id) {
        servicePayReceiptService.removeServicePayReceipt(id);
        return ResponseEntity.ok().build();
    }

    //endregion

}
