/*
 * Source code generated by UnvUS.
 * Copyright(c) 2017 unvus.com All rights reserved.
 * Template skrull-pack-mybatis:src/main/java/rest/Rest.e.vm.java
 * Template is part of project: https://git.unvus.com/unvus/opensource/pack-unvus-mybatis
 */
package com.neofect.gts.web.cms.rest.srvce;

import java.net.URISyntaxException;
import java.util.HashMap;
import java.util.List;
import java.util.Map;

import org.springframework.http.HttpHeaders;
import org.springframework.http.HttpStatus;
import org.springframework.http.MediaType;
import org.springframework.http.ResponseEntity;
import org.springframework.web.bind.annotation.*;

import com.google.common.collect.ImmutableMap;
import com.neofect.gts.core.services.srvce.domain.ServiceContract;
import com.neofect.gts.core.services.srvce.service.ServiceContractService;
import com.unvus.web.util.PaginationUtil;

import lombok.extern.slf4j.Slf4j;

/**
 * Rest for {@link ServiceContract}<br/>
 */
@Slf4j
@RestController
@RequestMapping("/api")
public class ServiceContractResource {

    private final ServiceContractService serviceContractService;

    public ServiceContractResource(ServiceContractService serviceContractService) {
        this.serviceContractService = serviceContractService;
    }

    //region ------------------------------------------------------------------------------------------------ serviceContract API

    /**
     *
     */
    @GetMapping(value = "/service-contract", produces = MediaType.APPLICATION_JSON_VALUE)
    public ResponseEntity<List<ServiceContract>> listServiceContract(@RequestParam(value = "q", required = false) Map<String, Object> q)
            throws URISyntaxException {
        if (q == null) {
            q = new HashMap();
        }

        List<ServiceContract> serviceContractList = serviceContractService.listServiceContract(q);

        HttpHeaders headers = PaginationUtil.generatePaginationHttpHeaders();

        return new ResponseEntity<>(serviceContractList, headers, HttpStatus.OK);
    }

    /**
     * get count
     * @return
     */
    @GetMapping(value = "/service-contract/_count", produces = MediaType.APPLICATION_JSON_VALUE)
    public ResponseEntity<Map> getCount(@RequestParam(value = "q", required = false) Map<String, Object> q) {
        int count = serviceContractService.listServiceContractCnt(q);

        return new ResponseEntity<>(ImmutableMap.of("count", count), HttpStatus.OK);
    }

    /**
     * get empty object
     * @return
     */
    @GetMapping(value = "/service-contract/_empty", produces = MediaType.APPLICATION_JSON_VALUE)
    public ResponseEntity<ServiceContract> getEmptyServiceContract() {
        ServiceContract serviceContract = new ServiceContract();
        return new ResponseEntity<>(serviceContract, HttpStatus.OK);
    }

    /**
     * get
     */
    @GetMapping(value = "/service-contract/{id}", produces = MediaType.APPLICATION_JSON_VALUE)
    public ResponseEntity<ServiceContract> getServiceContract(@PathVariable("id") Long id) {
        ServiceContract serviceContract = serviceContractService.getServiceContract(id);
        return new ResponseEntity<>(serviceContract, HttpStatus.OK);
    }

    /**
     * add
     */
    @PostMapping("/service-contract")
    public ResponseEntity<Void> addServiceContract(@RequestBody ServiceContract serviceContract) {
        serviceContractService.saveServiceContract(serviceContract);

        return ResponseEntity.ok().build();
    }

    /**
     * modify
     */
    @PutMapping("/service-contract/{id}")
    public ResponseEntity<Void> updateServiceContract(@PathVariable("id") Long id, @RequestBody ServiceContract serviceContract) throws Exception {
        // if (!id.equals(serviceContract.getId())) {
        //     return new ResponseEntity(HttpStatus.BAD_REQUEST);
        // }
        serviceContractService.saveServiceContract(serviceContract);
        return ResponseEntity.ok().build();
    }

    /**
     * delete
     */
    @DeleteMapping("/service-contract/{id}")
    public ResponseEntity<Void> removeServiceContract(@PathVariable("id") Long id) {
        serviceContractService.removeServiceContract(id);
        return ResponseEntity.ok().build();
    }

    //endregion

}
