/*
 * Source code generated by UnvUS.
 * Copyright(c) 2017 unvus.com All rights reserved.
 * Template skrull-pack-mybatis:src/main/java/repository/Repository.e.vm.java
 * Template is part of project: https://git.unvus.com/unvus/opensource/pack-unvus-mybatis
 */
package com.neofect.gts.core.services.site.repository;

import java.util.List;
import java.util.Map;

import com.neofect.gts.core.services.site.domain.TermContent;
import org.springframework.stereotype.Repository;

import com.unvus.config.mybatis.pagination.Pageable;
import com.unvus.config.mybatis.support.DefaultMapper;
import com.neofect.gts.core.services.site.domain.TermContent;

/**
 * Repository for {@link TermContent}<br/>
 * Available methods are.. <br/>
 * <ul>
 * <li>TermContent getTermContent(Long id);</li>
 * <li>int listTermContentCnt(Map<String, Object> params);</li>
 * <li>List<TermContent> listTermContent(Map<String, Object> params);</li>
 * <li>int insertTermContent(TermContent termcontent);</li>
 * <li>int updateTermContent(TermContent termcontent);</li>
 * <li>int deleteTermContent(Long id);</li>
 * </ul>
 */
@DefaultMapper
@Repository
public interface TermContentRepository extends TermContentRepository_ {
    TermContent getTermContent(Long id);

    int listTermContentCnt(Map<String, Object> params);

    /**
     * if yuou want to avoid result objects less than dataPerPage caused by "1:N mappings".. <br/>
     * add function that return "distinct id list" and name it with : <br/>
     * <code>List<Long> listTermContentIds(Map<String, Object> params)</code> <br/>
     * and replace @Pageable with :  <br/>
     * <code>@Pageable(useMergeQuery = true)</code> <br/>
     */
    @Pageable
    List<TermContent> listTermContent(Map<String, Object> params);

    List<Long> listTermContentIds(Map<String, Object> params);

}
