/*
 * Source code generated by UnvUS.
 * Copyright(c) 2017 unvus.com All rights reserved.
 * Template skrull-pack-mybatis:src/main/java/service/Service.e.vm.java
 * Template is part of project: https://git.unvus.com/unvus/opensource/pack-unvus-mybatis
 */
package com.neofect.gts.core.services.srvce.service;

import java.util.List;
import java.util.Map;

import org.springframework.stereotype.Service;
import org.springframework.transaction.annotation.Transactional;

import com.neofect.gts.core.services.srvce.domain.ServiceContractPlan;
import com.neofect.gts.core.services.srvce.repository.ServiceContractPlanRepository;
import com.unvus.config.mybatis.pagination.OrderBy;
import com.unvus.query.QueryTool;


/**
 * Service for {@link ServiceContractPlan}<br/>
 */
@Service
public class ServiceContractPlanService {

    private final ServiceContractPlanRepository serviceContractPlanRepository;

    public ServiceContractPlanService(ServiceContractPlanRepository serviceContractPlanRepository) {
        this.serviceContractPlanRepository = serviceContractPlanRepository;
    }

    //region ------------------------------------------------------------------------------------------------ serviceContractPlan CRUD

    @Transactional
    public ServiceContractPlan saveServiceContractPlan(ServiceContractPlan serviceContractPlan) {
        // if (serviceContractPlan.getId() == null) {
        //     addServiceContractPlan(serviceContractPlan);
        // } else {
        //     modifyServiceContractPlan(serviceContractPlan);
        // }

        return serviceContractPlan;
    }

    private int addServiceContractPlan(ServiceContractPlan serviceContractPlan) {
        int result = serviceContractPlanRepository.insertServiceContractPlan(serviceContractPlan);
        return result;
    }

    private int modifyServiceContractPlan(ServiceContractPlan serviceContractPlan) {
        int result = serviceContractPlanRepository.updateServiceContractPlan(serviceContractPlan);
        return result;
    }

    @Transactional
    public int removeServiceContractPlan(Long id) {
        int rows = serviceContractPlanRepository.deleteServiceContractPlan(id);
        return rows;
    }

    public ServiceContractPlan getServiceContractPlan(Long id) {
        ServiceContractPlan serviceContractPlan = serviceContractPlanRepository.getServiceContractPlan(id);

        return serviceContractPlan;
    }

    public int listServiceContractPlanCnt(Map<String, Object> params) {
        int rows = serviceContractPlanRepository.listServiceContractPlanCnt(params);
        return rows;
    }

    public List<ServiceContractPlan> listServiceContractPlan(Map<String, Object> params) {
        List<ServiceContractPlan> lists = serviceContractPlanRepository.listServiceContractPlan(params);

        return lists;
    }

    public List<ServiceContractPlan> listServiceContractPlanByIds(List<Long> ids, Map<String, Object> params) {
        params.put("ids", ids);
        QueryTool.setDefaultOrderBy(new OrderBy("CUST_ID", ids));
        QueryTool.setDefaultOrderBy(new OrderBy("CONT_SEQ", ids));
        QueryTool.setDefaultOrderBy(new OrderBy("PLAN_SEQ", ids));
        List<ServiceContractPlan> lists = serviceContractPlanRepository.listServiceContractPlan(params);

        return lists;
    }

    //endregion

}
