/*
 * Source code generated by UnvUS.
 * Copyright(c) 2017 unvus.com All rights reserved.
 * Template skrull-pack-mybatis:src/main/java/service/Service.e.vm.java
 * Template is part of project: https://git.unvus.com/unvus/opensource/pack-unvus-mybatis
 */
package com.neofect.gts.core.services.srvce.service;

import java.util.List;
import java.util.Map;

import org.springframework.stereotype.Service;
import org.springframework.transaction.annotation.Transactional;

import com.neofect.gts.core.services.srvce.domain.ServiceSupplySchedule;
import com.neofect.gts.core.services.srvce.repository.ServiceSupplyScheduleRepository;
import com.unvus.config.mybatis.pagination.OrderBy;
import com.unvus.query.QueryTool;


/**
 * Service for {@link ServiceSupplySchedule}<br/>
 */
@Service
public class ServiceSupplyScheduleService {

    private final ServiceSupplyScheduleRepository serviceSupplyScheduleRepository;

    public ServiceSupplyScheduleService(ServiceSupplyScheduleRepository serviceSupplyScheduleRepository) {
        this.serviceSupplyScheduleRepository = serviceSupplyScheduleRepository;
    }

    //region ------------------------------------------------------------------------------------------------ serviceSupplySchedule CRUD

    @Transactional
    public ServiceSupplySchedule saveServiceSupplySchedule(ServiceSupplySchedule serviceSupplySchedule) {
        // if (serviceSupplySchedule.getId() == null) {
        //     addServiceSupplySchedule(serviceSupplySchedule);
        // } else {
        //     modifyServiceSupplySchedule(serviceSupplySchedule);
        // }

        return serviceSupplySchedule;
    }

    private int addServiceSupplySchedule(ServiceSupplySchedule serviceSupplySchedule) {
        int result = serviceSupplyScheduleRepository.insertServiceSupplySchedule(serviceSupplySchedule);
        return result;
    }

    private int modifyServiceSupplySchedule(ServiceSupplySchedule serviceSupplySchedule) {
        int result = serviceSupplyScheduleRepository.updateServiceSupplySchedule(serviceSupplySchedule);
        return result;
    }

    @Transactional
    public int removeServiceSupplySchedule(Long id) {
        int rows = serviceSupplyScheduleRepository.deleteServiceSupplySchedule(id);
        return rows;
    }

    public ServiceSupplySchedule getServiceSupplySchedule(Long id) {
        ServiceSupplySchedule serviceSupplySchedule = serviceSupplyScheduleRepository.getServiceSupplySchedule(id);

        return serviceSupplySchedule;
    }

    public int listServiceSupplyScheduleCnt(Map<String, Object> params) {
        int rows = serviceSupplyScheduleRepository.listServiceSupplyScheduleCnt(params);
        return rows;
    }

    public List<ServiceSupplySchedule> listServiceSupplySchedule(Map<String, Object> params) {
        List<ServiceSupplySchedule> lists = serviceSupplyScheduleRepository.listServiceSupplySchedule(params);

        return lists;
    }

    public List<ServiceSupplySchedule> listServiceSupplyScheduleByIds(List<Long> ids, Map<String, Object> params) {
        params.put("ids", ids);
        QueryTool.setDefaultOrderBy(new OrderBy("CUST_ID", ids));
        QueryTool.setDefaultOrderBy(new OrderBy("CONT_SEQ", ids));
        QueryTool.setDefaultOrderBy(new OrderBy("CONT_ITEM", ids));
        List<ServiceSupplySchedule> lists = serviceSupplyScheduleRepository.listServiceSupplySchedule(params);

        return lists;
    }

    //endregion

}
