/*
 * Source code generated by UnvUS.
 * Copyright(c) 2017 unvus.com All rights reserved.
 * Template skrull-pack-mybatis:src/main/java/service/Service.e.vm.java
 * Template is part of project: https://git.unvus.com/unvus/opensource/pack-unvus-mybatis
 */
package com.neofect.gts.core.services.srvce.service;

import java.util.List;
import java.util.Map;

import org.springframework.stereotype.Service;
import org.springframework.transaction.annotation.Transactional;

import com.neofect.gts.core.services.srvce.domain.ServiceSchedule;
import com.neofect.gts.core.services.srvce.repository.ServiceScheduleRepository;
import com.unvus.config.mybatis.pagination.OrderBy;
import com.unvus.query.QueryTool;


/**
 * Service for {@link ServiceSchedule}<br/>
 */
@Service
public class ServiceScheduleService {

    private final ServiceScheduleRepository serviceScheduleRepository;

    public ServiceScheduleService(ServiceScheduleRepository serviceScheduleRepository) {
        this.serviceScheduleRepository = serviceScheduleRepository;
    }

    //region ------------------------------------------------------------------------------------------------ serviceSchedule CRUD

    @Transactional
    public ServiceSchedule saveServiceSchedule(ServiceSchedule serviceSchedule) {
        if (serviceSchedule.getId() == null) {
            addServiceSchedule(serviceSchedule);
        } else {
            modifyServiceSchedule(serviceSchedule);
        }

        return serviceSchedule;
    }

    private int addServiceSchedule(ServiceSchedule serviceSchedule) {
        int result = serviceScheduleRepository.insertServiceSchedule(serviceSchedule);
        return result;
    }

    private int modifyServiceSchedule(ServiceSchedule serviceSchedule) {
        int result = serviceScheduleRepository.updateServiceSchedule(serviceSchedule);
        return result;
    }

    @Transactional
    public int removeServiceSchedule(Long id) {
        int rows = serviceScheduleRepository.deleteServiceSchedule(id);
        return rows;
    }

    public ServiceSchedule getServiceSchedule(Long id) {
        ServiceSchedule serviceSchedule = serviceScheduleRepository.getServiceSchedule(id);

        return serviceSchedule;
    }

    public int listServiceScheduleCnt(Map<String, Object> params) {
        int rows = serviceScheduleRepository.listServiceScheduleCnt(params);
        return rows;
    }

    public List<ServiceSchedule> listServiceSchedule(Map<String, Object> params) {
        List<ServiceSchedule> lists = serviceScheduleRepository.listServiceSchedule(params);

        return lists;
    }

    public List<ServiceSchedule> listServiceScheduleByIds(List<Long> ids, Map<String, Object> params) {
        params.put("ids", ids);
        QueryTool.setDefaultOrderBy(new OrderBy("S_ID", ids));
        List<ServiceSchedule> lists = serviceScheduleRepository.listServiceSchedule(params);

        return lists;
    }

    //endregion

}
