spring:
  application:
    name: gts-cms
  profiles:
    # The commented value for `active` can be replaced with valid Spring profiles to load.
    # Otherwise, it will be filled in by maven when building the WAR file
    # Either way, it can be overridden by `--spring.profiles.active` value passed in the commandline or `-Dspring.profiles.active` set in `JAVA_OPTS`
    active: #spring.profiles.active#
  servlet:
    multipart:
      max-file-size: 50MB
      max-request-size: 50MB

server:
  servlet:
    session:
      timeout: 30
  port: 8088
#  port: 8080
  error:
    whitelabel:
      enabled: false

unvus:
  app:
    name: gts-cms
  format:
    date-format: yyyy.MM.dd
    datetime-format: yyyy.MM.dd HH:mm:ss
