/*
 * Source code generated by UnvUS.
 * Copyright(c) 2017 unvus.com All rights reserved.
 * Template skrull-pack-mybatis:src/main/java/repository/Repository.e.vm.java
 * Template is part of project: https://git.unvus.com/unvus/opensource/pack-unvus-mybatis
 */
package com.neofect.gts.core.services.sm.repository;

import java.util.List;
import java.util.Map;

import org.springframework.stereotype.Repository;

import com.neofect.gts.core.services.sm.domain.SmManual;
import com.unvus.config.mybatis.pagination.Pageable;
import com.unvus.config.mybatis.support.DefaultMapper;

/**
 * Repository for {@link SmManual}<br/>
 * Available methods are.. <br/>
 * <ul>
 * <li>SmManual getSmManual(Long id);</li>
 * <li>int listSmManualCnt(Map<String, Object> params);</li>
 * <li>List<SmManual> listSmManual(Map<String, Object> params);</li>
 * <li>int insertSmManual(SmManual smmanual);</li>
 * <li>int updateSmManual(SmManual smmanual);</li>
 * <li>int deleteSmManual(Long id);</li>
 * </ul>
 */
@DefaultMapper
@Repository
public interface SmManualRepository extends SmManualRepository_ {
    SmManual getSmManual(Long id);

    int listSmManualCnt(Map<String, Object> params);

    /**
     * if yuou want to avoid result objects less than dataPerPage caused by "1:N mappings".. <br/>
     * add function that return "distinct id list" and name it with : <br/>
     * <code>List<Long> listSmManualIds(Map<String, Object> params)</code> <br/>
     * and replace @Pageable with :  <br/>
     * <code>@Pageable(useMergeQuery = true)</code> <br/>
     */
    @Pageable
    List<SmManual> listSmManual(Map<String, Object> params);

    List<Long> listSmManualIds(Map<String, Object> params);

}
