/*
 * Source code generated by UnvUS.
 * Copyright(c) 2017 unvus.com All rights reserved.
 * Template skrull-pack-mybatis:src/main/java/rest/Rest.e.vm.java
 * Template is part of project: https://git.unvus.com/unvus/opensource/pack-unvus-mybatis
 */
package com.neofect.gts.web.cms.rest.form;

import java.net.URISyntaxException;
import java.util.HashMap;
import java.util.List;
import java.util.Map;

import org.springframework.http.HttpHeaders;
import org.springframework.http.HttpStatus;
import org.springframework.http.MediaType;
import org.springframework.http.ResponseEntity;
import org.springframework.web.bind.annotation.*;

import com.google.common.collect.ImmutableMap;
import com.neofect.gts.core.services.form.domain.FormContract;
import com.neofect.gts.core.services.form.service.FormContractService;
import com.unvus.web.util.PaginationUtil;

import lombok.extern.slf4j.Slf4j;

/**
 * Rest for {@link FormContract}<br/>
 */
@Slf4j
@RestController
@RequestMapping("/api")
public class FormContractResource {

    private final FormContractService formContractService;

    public FormContractResource(FormContractService formContractService) {
        this.formContractService = formContractService;
    }

    //region ------------------------------------------------------------------------------------------------ formContract API

    /**
     *
     */
    @GetMapping(value = "/form-contract", produces = MediaType.APPLICATION_JSON_VALUE)
    public ResponseEntity<List<FormContract>> listFormContract(@RequestParam(value = "q", required = false) Map<String, Object> q) throws URISyntaxException {
        if (q == null) {
            q = new HashMap();
        }

        List<FormContract> formContractList = formContractService.listFormContract(q);

        HttpHeaders headers = PaginationUtil.generatePaginationHttpHeaders();

        return new ResponseEntity<>(formContractList, headers, HttpStatus.OK);
    }

    /**
     * get count
     * @return
     */
    @GetMapping(value = "/form-contract/_count", produces = MediaType.APPLICATION_JSON_VALUE)
    public ResponseEntity<Map> getCount(@RequestParam(value = "q", required = false) Map<String, Object> q) {
        int count = formContractService.listFormContractCnt(q);

        return new ResponseEntity<>(ImmutableMap.of("count", count), HttpStatus.OK);
    }

    /**
     * get empty object
     * @return
     */
    @GetMapping(value = "/form-contract/_empty", produces = MediaType.APPLICATION_JSON_VALUE)
    public ResponseEntity<FormContract> getEmptyFormContract() {
        FormContract formContract = new FormContract();
        return new ResponseEntity<>(formContract, HttpStatus.OK);
    }

    /**
     * get
     */
    @GetMapping(value = "/form-contract/{id}", produces = MediaType.APPLICATION_JSON_VALUE)
    public ResponseEntity<FormContract> getFormContract(@PathVariable("id") Long id) {
        FormContract formContract = formContractService.getFormContract(id);
        return new ResponseEntity<>(formContract, HttpStatus.OK);
    }

    /**
     * add
     */
    @PostMapping("/form-contract")
    public ResponseEntity<Void> addFormContract(@RequestBody FormContract formContract) {
        formContractService.saveFormContract(formContract);

        return ResponseEntity.ok().build();
    }

    /**
     * modify
     */
    @PutMapping("/form-contract/{id}")
    public ResponseEntity<Void> updateFormContract(@PathVariable("id") Long id, @RequestBody FormContract formContract) throws Exception {
        if (!id.equals(formContract.getId())) {
            return new ResponseEntity(HttpStatus.BAD_REQUEST);
        }
        formContractService.saveFormContract(formContract);
        return ResponseEntity.ok().build();
    }

    /**
     * delete
     */
    @DeleteMapping("/form-contract/{id}")
    public ResponseEntity<Void> removeFormContract(@PathVariable("id") Long id) {
        formContractService.removeFormContract(id);
        return ResponseEntity.ok().build();
    }

    //endregion

}
