/*
 * Source code generated by UnvUS.
 * Copyright(c) 2017 unvus.com All rights reserved.
 * Template skrull-pack-mybatis:src/main/java/domain/EntityBase.e.vm.java
 * Template is part of project: https://git.unvus.com/unvus/opensource/pack-unvus-mybatis
 */
package com.neofect.gts.core.services.lease.domain;

import java.io.Serializable;
import java.time.LocalDateTime;
import java.util.HashMap;
import java.util.Map;

import org.apache.ibatis.type.Alias;

import lombok.Data;

/**
 * 전표판매_상세
 */

/**
 * @see com.neofect.gts.core.services.lease.domain.LeaseContract
 */
@Alias("lease_leaseContract_")
@Data
public abstract class LeaseContract_ implements Serializable {

    private static final long serialVersionUID = 1L;

    // Raw attributes
    /**
    * 지사ID
    */
    protected String deptId;
    /**
    * 임대계약ID
    */
    protected Integer lId;
    /**
    * 대여구분
    */
    protected String leaseDiv;
    /**
    * 요청처리지사ID
    */
    protected String pdeptId;
    /**
    * 고객ID
    */
    protected Integer custId;
    /**
    * 거래처코드
    */
    protected String custCode;
    /**
    * 거래처명
    */
    protected String custName;
    /**
    * 품목ID
    */
    protected Integer productId;
    /**
    * 수량
    */
    protected Integer qty;
    /**
    * 단가
    */
    protected Long damt;
    /**
    * 금액
    */
    protected Long amt;
    /**
    * 공급가액
    */
    protected Long supplyAmt;
    /**
    * 부가세액
    */
    protected Long vatAmt;
    /**
    * 적요
    */
    protected String remark;
    /**
    * 입고일
    */
    protected LocalDateTime inDate;
    /**
    * 출고일
    */
    protected LocalDateTime outDate;
    /**
    * 서비스개시일
    */
    protected LocalDateTime startDate;
    /**
    * 서비스종료일
    */
    protected LocalDateTime endDate;
    /**
    * 반납일
    */
    protected LocalDateTime returnDate;
    /**
    * 반납확인사번
    */
    protected String mmemberId;
    /**
    * 임대료지급기준
    */
    protected String leasepayDiv;
    /**
    * 임대료지급완료여부 Y 완료
    */
    protected String leaspayYn;
    /**
    * 요청서전표구분
    */
    protected String eslipDiv;
    /**
    * 요청서전표일자
    */
    protected LocalDateTime eslipDate;
    /**
    * 요청서지사ID
    */
    protected String edeptId;
    /**
    * 요청서전표번호
    */
    protected Integer eslipSeq;
    /**
    * 요청서전표순번
    */
    protected Integer eslipItem;
    /**
    * 임대생성품목ID
    */
    protected Integer lprodId;
    protected String rowInputEmpNo;
    protected LocalDateTime rowInputDate;
    protected String rowInputIp;
    protected String rowUpdateEmpNo;
    protected String rowUpdateDate;
    protected String rowUpdateIp;

    protected Map<String, Object> _meta = new HashMap();
}
