/*
 * Source code generated by UnvUS.
 * Copyright(c) 2017 unvus.com All rights reserved.
 * Template skrull-pack-mybatis:src/main/java/rest/Rest.e.vm.java
 * Template is part of project: https://git.unvus.com/unvus/opensource/pack-unvus-mybatis
 */
package com.neofect.gts.web.cms.rest.sm;

import java.net.URISyntaxException;
import java.util.HashMap;
import java.util.List;
import java.util.Map;

import org.springframework.http.HttpHeaders;
import org.springframework.http.HttpStatus;
import org.springframework.http.MediaType;
import org.springframework.http.ResponseEntity;
import org.springframework.web.bind.annotation.*;

import com.google.common.collect.ImmutableMap;
import com.neofect.gts.core.services.sm.domain.SmAuthActUser;
import com.neofect.gts.core.services.sm.service.SmAuthActUserService;
import com.unvus.web.util.PaginationUtil;

import lombok.extern.slf4j.Slf4j;

/**
 * Rest for {@link SmAuthActUser}<br/>
 */
@Slf4j
@RestController
@RequestMapping("/api")
public class SmAuthActUserResource {

    private final SmAuthActUserService smAuthActUserService;

    public SmAuthActUserResource(SmAuthActUserService smAuthActUserService) {
        this.smAuthActUserService = smAuthActUserService;
    }

    //region ------------------------------------------------------------------------------------------------ smAuthActUser API

    /**
     *
     */
    @GetMapping(value = "/sm-auth-act-user", produces = MediaType.APPLICATION_JSON_VALUE)
    public ResponseEntity<List<SmAuthActUser>> listSmAuthActUser(@RequestParam(value = "q", required = false) Map<String, Object> q) throws URISyntaxException {
        if (q == null) {
            q = new HashMap();
        }

        List<SmAuthActUser> smAuthActUserList = smAuthActUserService.listSmAuthActUser(q);

        HttpHeaders headers = PaginationUtil.generatePaginationHttpHeaders();

        return new ResponseEntity<>(smAuthActUserList, headers, HttpStatus.OK);
    }

    /**
     * get count
     * @return
     */
    @GetMapping(value = "/sm-auth-act-user/_count", produces = MediaType.APPLICATION_JSON_VALUE)
    public ResponseEntity<Map> getCount(@RequestParam(value = "q", required = false) Map<String, Object> q) {
        int count = smAuthActUserService.listSmAuthActUserCnt(q);

        return new ResponseEntity<>(ImmutableMap.of("count", count), HttpStatus.OK);
    }

    /**
     * get empty object
     * @return
     */
    @GetMapping(value = "/sm-auth-act-user/_empty", produces = MediaType.APPLICATION_JSON_VALUE)
    public ResponseEntity<SmAuthActUser> getEmptySmAuthActUser() {
        SmAuthActUser smAuthActUser = new SmAuthActUser();
        return new ResponseEntity<>(smAuthActUser, HttpStatus.OK);
    }

    /**
     * get
     */
    @GetMapping(value = "/sm-auth-act-user/{id}", produces = MediaType.APPLICATION_JSON_VALUE)
    public ResponseEntity<SmAuthActUser> getSmAuthActUser(@PathVariable("id") Long id) {
        SmAuthActUser smAuthActUser = smAuthActUserService.getSmAuthActUser(id);
        return new ResponseEntity<>(smAuthActUser, HttpStatus.OK);
    }

    /**
     * add
     */
    @PostMapping("/sm-auth-act-user")
    public ResponseEntity<Void> addSmAuthActUser(@RequestBody SmAuthActUser smAuthActUser) {
        smAuthActUserService.saveSmAuthActUser(smAuthActUser);

        return ResponseEntity.ok().build();
    }

    /**
     * modify
     */
    @PutMapping("/sm-auth-act-user/{id}")
    public ResponseEntity<Void> updateSmAuthActUser(@PathVariable("id") Long id, @RequestBody SmAuthActUser smAuthActUser) throws Exception {
        // if (!id.equals(smAuthActUser.getId())) {
        //     return new ResponseEntity(HttpStatus.BAD_REQUEST);
        // }
        smAuthActUserService.saveSmAuthActUser(smAuthActUser);
        return ResponseEntity.ok().build();
    }

    /**
     * delete
     */
    @DeleteMapping("/sm-auth-act-user/{id}")
    public ResponseEntity<Void> removeSmAuthActUser(@PathVariable("id") Long id) {
        smAuthActUserService.removeSmAuthActUser(id);
        return ResponseEntity.ok().build();
    }

    //endregion

}
