/*
 * Source code generated by UnvUS.
 * Copyright(c) 2017 unvus.com All rights reserved.
 * Template skrull-pack-mybatis:src/main/java/rest/Rest.e.vm.java
 * Template is part of project: https://git.unvus.com/unvus/opensource/pack-unvus-mybatis
 */
package com.neofect.gts.web.cms.rest.sm;

import java.net.URISyntaxException;
import java.util.HashMap;
import java.util.List;
import java.util.Map;

import org.springframework.http.HttpHeaders;
import org.springframework.http.HttpStatus;
import org.springframework.http.MediaType;
import org.springframework.http.ResponseEntity;
import org.springframework.web.bind.annotation.*;

import com.google.common.collect.ImmutableMap;
import com.neofect.gts.core.services.sm.domain.SmAuthUserMenuRecent;
import com.neofect.gts.core.services.sm.service.SmAuthUserMenuRecentService;
import com.unvus.web.util.PaginationUtil;

import lombok.extern.slf4j.Slf4j;

/**
 * Rest for {@link SmAuthUserMenuRecent}<br/>
 */
@Slf4j
@RestController
@RequestMapping("/api")
public class SmAuthUserMenuRecentResource {

    private final SmAuthUserMenuRecentService smAuthUserMenuRecentService;

    public SmAuthUserMenuRecentResource(SmAuthUserMenuRecentService smAuthUserMenuRecentService) {
        this.smAuthUserMenuRecentService = smAuthUserMenuRecentService;
    }

    //region ------------------------------------------------------------------------------------------------ smAuthUserMenuRecent API

    /**
     *
     */
    @GetMapping(value = "/sm-auth-user-menu-recent", produces = MediaType.APPLICATION_JSON_VALUE)
    public ResponseEntity<List<SmAuthUserMenuRecent>> listSmAuthUserMenuRecent(@RequestParam(value = "q", required = false) Map<String, Object> q)
            throws URISyntaxException {
        if (q == null) {
            q = new HashMap();
        }

        List<SmAuthUserMenuRecent> smAuthUserMenuRecentList = smAuthUserMenuRecentService.listSmAuthUserMenuRecent(q);

        HttpHeaders headers = PaginationUtil.generatePaginationHttpHeaders();

        return new ResponseEntity<>(smAuthUserMenuRecentList, headers, HttpStatus.OK);
    }

    /**
     * get count
     * @return
     */
    @GetMapping(value = "/sm-auth-user-menu-recent/_count", produces = MediaType.APPLICATION_JSON_VALUE)
    public ResponseEntity<Map> getCount(@RequestParam(value = "q", required = false) Map<String, Object> q) {
        int count = smAuthUserMenuRecentService.listSmAuthUserMenuRecentCnt(q);

        return new ResponseEntity<>(ImmutableMap.of("count", count), HttpStatus.OK);
    }

    /**
     * get empty object
     * @return
     */
    @GetMapping(value = "/sm-auth-user-menu-recent/_empty", produces = MediaType.APPLICATION_JSON_VALUE)
    public ResponseEntity<SmAuthUserMenuRecent> getEmptySmAuthUserMenuRecent() {
        SmAuthUserMenuRecent smAuthUserMenuRecent = new SmAuthUserMenuRecent();
        return new ResponseEntity<>(smAuthUserMenuRecent, HttpStatus.OK);
    }

    /**
     * get
     */
    @GetMapping(value = "/sm-auth-user-menu-recent/{id}", produces = MediaType.APPLICATION_JSON_VALUE)
    public ResponseEntity<SmAuthUserMenuRecent> getSmAuthUserMenuRecent(@PathVariable("id") Long id) {
        SmAuthUserMenuRecent smAuthUserMenuRecent = smAuthUserMenuRecentService.getSmAuthUserMenuRecent(id);
        return new ResponseEntity<>(smAuthUserMenuRecent, HttpStatus.OK);
    }

    /**
     * add
     */
    @PostMapping("/sm-auth-user-menu-recent")
    public ResponseEntity<Void> addSmAuthUserMenuRecent(@RequestBody SmAuthUserMenuRecent smAuthUserMenuRecent) {
        smAuthUserMenuRecentService.saveSmAuthUserMenuRecent(smAuthUserMenuRecent);

        return ResponseEntity.ok().build();
    }

    /**
     * modify
     */
    @PutMapping("/sm-auth-user-menu-recent/{id}")
    public ResponseEntity<Void> updateSmAuthUserMenuRecent(@PathVariable("id") Long id, @RequestBody SmAuthUserMenuRecent smAuthUserMenuRecent)
            throws Exception {
        // if (!id.equals(smAuthUserMenuRecent.getId())) {
        //     return new ResponseEntity(HttpStatus.BAD_REQUEST);
        // }
        smAuthUserMenuRecentService.saveSmAuthUserMenuRecent(smAuthUserMenuRecent);
        return ResponseEntity.ok().build();
    }

    /**
     * delete
     */
    @DeleteMapping("/sm-auth-user-menu-recent/{id}")
    public ResponseEntity<Void> removeSmAuthUserMenuRecent(@PathVariable("id") Long id) {
        smAuthUserMenuRecentService.removeSmAuthUserMenuRecent(id);
        return ResponseEntity.ok().build();
    }

    //endregion

}
