/*
 * Source code generated by UnvUS.
 * Copyright(c) 2017 unvus.com All rights reserved.
 * Template skrull-pack-mybatis:src/main/java/rest/Rest.e.vm.java
 * Template is part of project: https://git.unvus.com/unvus/opensource/pack-unvus-mybatis
 */
package com.neofect.gts.web.cms.rest.sm;

import java.net.URISyntaxException;
import java.util.HashMap;
import java.util.List;
import java.util.Map;

import org.springframework.http.HttpHeaders;
import org.springframework.http.HttpStatus;
import org.springframework.http.MediaType;
import org.springframework.http.ResponseEntity;
import org.springframework.web.bind.annotation.*;

import com.google.common.collect.ImmutableMap;
import com.neofect.gts.core.services.sm.domain.SmAuthPgmcode;
import com.neofect.gts.core.services.sm.service.SmAuthPgmcodeService;
import com.unvus.web.util.PaginationUtil;

import lombok.extern.slf4j.Slf4j;

/**
 * Rest for {@link SmAuthPgmcode}<br/>
 */
@Slf4j
@RestController
@RequestMapping("/api")
public class SmAuthPgmcodeResource {

    private final SmAuthPgmcodeService smAuthPgmcodeService;

    public SmAuthPgmcodeResource(SmAuthPgmcodeService smAuthPgmcodeService) {
        this.smAuthPgmcodeService = smAuthPgmcodeService;
    }

    //region ------------------------------------------------------------------------------------------------ smAuthPgmcode API

    /**
     *
     */
    @GetMapping(value = "/sm-auth-pgmcode", produces = MediaType.APPLICATION_JSON_VALUE)
    public ResponseEntity<List<SmAuthPgmcode>> listSmAuthPgmcode(@RequestParam(value = "q", required = false) Map<String, Object> q) throws URISyntaxException {
        if (q == null) {
            q = new HashMap();
        }

        List<SmAuthPgmcode> smAuthPgmcodeList = smAuthPgmcodeService.listSmAuthPgmcode(q);

        HttpHeaders headers = PaginationUtil.generatePaginationHttpHeaders();

        return new ResponseEntity<>(smAuthPgmcodeList, headers, HttpStatus.OK);
    }

    /**
     * get count
     * @return
     */
    @GetMapping(value = "/sm-auth-pgmcode/_count", produces = MediaType.APPLICATION_JSON_VALUE)
    public ResponseEntity<Map> getCount(@RequestParam(value = "q", required = false) Map<String, Object> q) {
        int count = smAuthPgmcodeService.listSmAuthPgmcodeCnt(q);

        return new ResponseEntity<>(ImmutableMap.of("count", count), HttpStatus.OK);
    }

    /**
     * get empty object
     * @return
     */
    @GetMapping(value = "/sm-auth-pgmcode/_empty", produces = MediaType.APPLICATION_JSON_VALUE)
    public ResponseEntity<SmAuthPgmcode> getEmptySmAuthPgmcode() {
        SmAuthPgmcode smAuthPgmcode = new SmAuthPgmcode();
        return new ResponseEntity<>(smAuthPgmcode, HttpStatus.OK);
    }

    /**
     * get
     */
    @GetMapping(value = "/sm-auth-pgmcode/{id}", produces = MediaType.APPLICATION_JSON_VALUE)
    public ResponseEntity<SmAuthPgmcode> getSmAuthPgmcode(@PathVariable("id") Long id) {
        SmAuthPgmcode smAuthPgmcode = smAuthPgmcodeService.getSmAuthPgmcode(id);
        return new ResponseEntity<>(smAuthPgmcode, HttpStatus.OK);
    }

    /**
     * add
     */
    @PostMapping("/sm-auth-pgmcode")
    public ResponseEntity<Void> addSmAuthPgmcode(@RequestBody SmAuthPgmcode smAuthPgmcode) {
        smAuthPgmcodeService.saveSmAuthPgmcode(smAuthPgmcode);

        return ResponseEntity.ok().build();
    }

    /**
     * modify
     */
    @PutMapping("/sm-auth-pgmcode/{id}")
    public ResponseEntity<Void> updateSmAuthPgmcode(@PathVariable("id") Long id, @RequestBody SmAuthPgmcode smAuthPgmcode) throws Exception {
        // if (!id.equals(smAuthPgmcode.getId())) {
        //     return new ResponseEntity(HttpStatus.BAD_REQUEST);
        // }
        smAuthPgmcodeService.saveSmAuthPgmcode(smAuthPgmcode);
        return ResponseEntity.ok().build();
    }

    /**
     * delete
     */
    @DeleteMapping("/sm-auth-pgmcode/{id}")
    public ResponseEntity<Void> removeSmAuthPgmcode(@PathVariable("id") Long id) {
        smAuthPgmcodeService.removeSmAuthPgmcode(id);
        return ResponseEntity.ok().build();
    }

    //endregion

}
