/*
 * Source code generated by UnvUS.
 * Copyright(c) 2017 unvus.com All rights reserved.
 * Template skrull-pack-mybatis:src/main/java/rest/Rest.e.vm.java
 * Template is part of project: https://git.unvus.com/unvus/opensource/pack-unvus-mybatis
 */
package com.neofect.gts.web.cms.rest.sm;

import java.net.URISyntaxException;
import java.util.HashMap;
import java.util.List;
import java.util.Map;

import org.springframework.http.HttpHeaders;
import org.springframework.http.HttpStatus;
import org.springframework.http.MediaType;
import org.springframework.http.ResponseEntity;
import org.springframework.web.bind.annotation.*;

import com.google.common.collect.ImmutableMap;
import com.neofect.gts.core.services.sm.domain.SmCodeCalendar;
import com.neofect.gts.core.services.sm.service.SmCodeCalendarService;
import com.unvus.web.util.PaginationUtil;

import lombok.extern.slf4j.Slf4j;

/**
 * Rest for {@link SmCodeCalendar}<br/>
 */
@Slf4j
@RestController
@RequestMapping("/api")
public class SmCodeCalendarResource {

    private final SmCodeCalendarService smCodeCalendarService;

    public SmCodeCalendarResource(SmCodeCalendarService smCodeCalendarService) {
        this.smCodeCalendarService = smCodeCalendarService;
    }

    //region ------------------------------------------------------------------------------------------------ smCodeCalendar API

    /**
     *
     */
    @GetMapping(value = "/sm-code-calendar", produces = MediaType.APPLICATION_JSON_VALUE)
    public ResponseEntity<List<SmCodeCalendar>> listSmCodeCalendar(@RequestParam(value = "q", required = false) Map<String, Object> q)
            throws URISyntaxException {
        if (q == null) {
            q = new HashMap();
        }

        List<SmCodeCalendar> smCodeCalendarList = smCodeCalendarService.listSmCodeCalendar(q);

        HttpHeaders headers = PaginationUtil.generatePaginationHttpHeaders();

        return new ResponseEntity<>(smCodeCalendarList, headers, HttpStatus.OK);
    }

    /**
     * get count
     * @return
     */
    @GetMapping(value = "/sm-code-calendar/_count", produces = MediaType.APPLICATION_JSON_VALUE)
    public ResponseEntity<Map> getCount(@RequestParam(value = "q", required = false) Map<String, Object> q) {
        int count = smCodeCalendarService.listSmCodeCalendarCnt(q);

        return new ResponseEntity<>(ImmutableMap.of("count", count), HttpStatus.OK);
    }

    /**
     * get empty object
     * @return
     */
    @GetMapping(value = "/sm-code-calendar/_empty", produces = MediaType.APPLICATION_JSON_VALUE)
    public ResponseEntity<SmCodeCalendar> getEmptySmCodeCalendar() {
        SmCodeCalendar smCodeCalendar = new SmCodeCalendar();
        return new ResponseEntity<>(smCodeCalendar, HttpStatus.OK);
    }

    /**
     * get
     */
    @GetMapping(value = "/sm-code-calendar/{id}", produces = MediaType.APPLICATION_JSON_VALUE)
    public ResponseEntity<SmCodeCalendar> getSmCodeCalendar(@PathVariable("id") Long id) {
        SmCodeCalendar smCodeCalendar = smCodeCalendarService.getSmCodeCalendar(id);
        return new ResponseEntity<>(smCodeCalendar, HttpStatus.OK);
    }

    /**
     * add
     */
    @PostMapping("/sm-code-calendar")
    public ResponseEntity<Void> addSmCodeCalendar(@RequestBody SmCodeCalendar smCodeCalendar) {
        smCodeCalendarService.saveSmCodeCalendar(smCodeCalendar);

        return ResponseEntity.ok().build();
    }

    /**
     * modify
     */
    @PutMapping("/sm-code-calendar/{id}")
    public ResponseEntity<Void> updateSmCodeCalendar(@PathVariable("id") Long id, @RequestBody SmCodeCalendar smCodeCalendar) throws Exception {
        if (!id.equals(smCodeCalendar.getId())) {
            return new ResponseEntity(HttpStatus.BAD_REQUEST);
        }
        smCodeCalendarService.saveSmCodeCalendar(smCodeCalendar);
        return ResponseEntity.ok().build();
    }

    /**
     * delete
     */
    @DeleteMapping("/sm-code-calendar/{id}")
    public ResponseEntity<Void> removeSmCodeCalendar(@PathVariable("id") Long id) {
        smCodeCalendarService.removeSmCodeCalendar(id);
        return ResponseEntity.ok().build();
    }

    //endregion

}
