/*
 * Source code generated by UnvUS.
 * Copyright(c) 2017 unvus.com All rights reserved.
 * Template skrull-pack-mybatis:src/main/java/rest/Rest.e.vm.java
 * Template is part of project: https://git.unvus.com/unvus/opensource/pack-unvus-mybatis
 */
package com.neofect.gts.web.cms.rest.sm;

import java.net.URISyntaxException;
import java.util.HashMap;
import java.util.List;
import java.util.Map;

import org.springframework.http.HttpHeaders;
import org.springframework.http.HttpStatus;
import org.springframework.http.MediaType;
import org.springframework.http.ResponseEntity;
import org.springframework.web.bind.annotation.*;

import com.google.common.collect.ImmutableMap;
import com.neofect.gts.core.services.sm.domain.SubSum;
import com.neofect.gts.core.services.sm.service.SubSumService;
import com.unvus.web.util.PaginationUtil;

import lombok.extern.slf4j.Slf4j;

/**
 * Rest for {@link SubSum}<br/>
 */
@Slf4j
@RestController
@RequestMapping("/api")
public class SubSumResource {

    private final SubSumService subSumService;

    public SubSumResource(SubSumService subSumService) {
        this.subSumService = subSumService;
    }

    //region ------------------------------------------------------------------------------------------------ subSum API

    /**
     *
     */
    @GetMapping(value = "/sub-sum", produces = MediaType.APPLICATION_JSON_VALUE)
    public ResponseEntity<List<SubSum>> listSubSum(@RequestParam(value = "q", required = false) Map<String, Object> q) throws URISyntaxException {
        if (q == null) {
            q = new HashMap();
        }

        List<SubSum> subSumList = subSumService.listSubSum(q);

        HttpHeaders headers = PaginationUtil.generatePaginationHttpHeaders();

        return new ResponseEntity<>(subSumList, headers, HttpStatus.OK);
    }

    /**
     * get count
     * @return
     */
    @GetMapping(value = "/sub-sum/_count", produces = MediaType.APPLICATION_JSON_VALUE)
    public ResponseEntity<Map> getCount(@RequestParam(value = "q", required = false) Map<String, Object> q) {
        int count = subSumService.listSubSumCnt(q);

        return new ResponseEntity<>(ImmutableMap.of("count", count), HttpStatus.OK);
    }

    /**
     * get empty object
     * @return
     */
    @GetMapping(value = "/sub-sum/_empty", produces = MediaType.APPLICATION_JSON_VALUE)
    public ResponseEntity<SubSum> getEmptySubSum() {
        SubSum subSum = new SubSum();
        return new ResponseEntity<>(subSum, HttpStatus.OK);
    }

    /**
     * get
     */
    @GetMapping(value = "/sub-sum/{id}", produces = MediaType.APPLICATION_JSON_VALUE)
    public ResponseEntity<SubSum> getSubSum(@PathVariable("id") Long id) {
        SubSum subSum = subSumService.getSubSum(id);
        return new ResponseEntity<>(subSum, HttpStatus.OK);
    }

    /**
     * add
     */
    @PostMapping("/sub-sum")
    public ResponseEntity<Void> addSubSum(@RequestBody SubSum subSum) {
        subSumService.saveSubSum(subSum);

        return ResponseEntity.ok().build();
    }

    /**
     * modify
     */
    @PutMapping("/sub-sum/{id}")
    public ResponseEntity<Void> updateSubSum(@PathVariable("id") Long id, @RequestBody SubSum subSum) throws Exception {
        if (!id.equals(subSum.getId())) {
            return new ResponseEntity(HttpStatus.BAD_REQUEST);
        }
        subSumService.saveSubSum(subSum);
        return ResponseEntity.ok().build();
    }

    /**
     * delete
     */
    @DeleteMapping("/sub-sum/{id}")
    public ResponseEntity<Void> removeSubSum(@PathVariable("id") Long id) {
        subSumService.removeSubSum(id);
        return ResponseEntity.ok().build();
    }

    //endregion

}
