/*
 * Source code generated by UnvUS.
 * Copyright(c) 2017 unvus.com All rights reserved.
 * Template skrull-pack-mybatis:src/main/java/domain/EntityBase.e.vm.java
 * Template is part of project: https://git.unvus.com/unvus/opensource/pack-unvus-mybatis
 */
package com.neofect.gts.core.services.user.domain;

import java.io.Serializable;
import java.time.LocalDateTime;
import java.util.HashMap;
import java.util.Map;

import com.neofect.gts.core.services.user.repository.TermAgreeRepository;
import org.apache.ibatis.type.Alias;

import lombok.Data;

/**
 * 약관 동의
 */

/**
 * Generated Files
 * <dl>
 *     <dt>model_</dt>
 *     <dd>
 *         @see TermAgree_
 *     </dd>
 *     <dt>repository_</dt>
 *     <dd>
 *         @see TermAgreeRepository
 *     </dd>
 * </ul>
 *
 * Extended Files
 * <dl>
 *     <dt>model</dt>
 *     <dd>
 *         @see TermAgree
 *     </dd>
 *     <dt>repository</dt>
 *     <dd>
 *         @see TermAgreeRepository
 *     </dd>
 * </ul>
 *
 */
@Alias("user_termAgree_")
@Data
public abstract class TermAgree_ implements Serializable {

    private static final long serialVersionUID = 1L;

    // Raw attributes
    /**
    * 계정아이디
    */
    protected Long acntId;
    /**
    * 약관코드
    */
    protected String termCode;
    /**
    * 동의여부
    */
    protected Boolean agree;
    /**
    * 수정일시
    */
    protected LocalDateTime modifiedDt;
    /**
    * 수정자
    */
    protected Long modifiedBy;

    protected Map<String, Object> _meta = new HashMap();
}
