/*
 * Source code generated by UnvUS.
 * Copyright(c) 2017 unvus.com All rights reserved.
 * Template skrull-pack-mybatis:src/main/java/repository/Repository.e.vm.java
 * Template is part of project: https://git.unvus.com/unvus/opensource/pack-unvus-mybatis
 */
package com.neofect.gts.core.services.lease.repository;

import java.util.List;
import java.util.Map;

import org.springframework.stereotype.Repository;

import com.neofect.gts.core.services.lease.domain.LeaseContract;
import com.unvus.config.mybatis.pagination.Pageable;
import com.unvus.config.mybatis.support.DefaultMapper;

/**
 * Repository for {@link LeaseContract}<br/>
 * Available methods are.. <br/>
 * <ul>
 * <li>LeaseContract getLeaseContract(Long id);</li>
 * <li>int listLeaseContractCnt(Map<String, Object> params);</li>
 * <li>List<LeaseContract> listLeaseContract(Map<String, Object> params);</li>
 * <li>int insertLeaseContract(LeaseContract leasecontract);</li>
 * <li>int updateLeaseContract(LeaseContract leasecontract);</li>
 * <li>int deleteLeaseContract(Long id);</li>
 * </ul>
 */
@DefaultMapper
@Repository
public interface LeaseContractRepository extends LeaseContractRepository_ {
    LeaseContract getLeaseContract(Long id);

    int listLeaseContractCnt(Map<String, Object> params);

    /**
     * if yuou want to avoid result objects less than dataPerPage caused by "1:N mappings".. <br/>
     * add function that return "distinct id list" and name it with : <br/>
     * <code>List<Long> listLeaseContractIds(Map<String, Object> params)</code> <br/>
     * and replace @Pageable with :  <br/>
     * <code>@Pageable(useMergeQuery = true)</code> <br/>
     */
    @Pageable
    List<LeaseContract> listLeaseContract(Map<String, Object> params);

    List<Long> listLeaseContractIds(Map<String, Object> params);

}
