/*
 * Source code generated by UnvUS.
 * Copyright(c) 2017 unvus.com All rights reserved.
 * Template skrull-pack-mybatis:src/main/java/service/Service.e.vm.java
 * Template is part of project: https://git.unvus.com/unvus/opensource/pack-unvus-mybatis
 */
package com.neofect.gts.core.services.am.service;

import java.util.List;
import java.util.Map;

import org.springframework.stereotype.Service;
import org.springframework.transaction.annotation.Transactional;

import com.neofect.gts.core.services.am.domain.AmBdgtDrawup;
import com.neofect.gts.core.services.am.repository.AmBdgtDrawupRepository;
import com.unvus.config.mybatis.pagination.OrderBy;
import com.unvus.query.QueryTool;

/**
 * Service for {@link AmBdgtDrawup}<br/>
 */
@Service
public class AmBdgtDrawupService {

    private final AmBdgtDrawupRepository amBdgtDrawupRepository;

    public AmBdgtDrawupService(AmBdgtDrawupRepository amBdgtDrawupRepository) {
        this.amBdgtDrawupRepository = amBdgtDrawupRepository;
    }

    //region ------------------------------------------------------------------------------------------------ amBdgtDrawup CRUD

    @Transactional
    public AmBdgtDrawup saveAmBdgtDrawup(AmBdgtDrawup amBdgtDrawup) {
        // if (amBdgtDrawup.getId() == null) {
        //     addAmBdgtDrawup(amBdgtDrawup);
        // } else {
        //     modifyAmBdgtDrawup(amBdgtDrawup);
        // }

        return amBdgtDrawup;
    }

    private int addAmBdgtDrawup(AmBdgtDrawup amBdgtDrawup) {
        int result = amBdgtDrawupRepository.insertAmBdgtDrawup(amBdgtDrawup);
        return result;
    }

    private int modifyAmBdgtDrawup(AmBdgtDrawup amBdgtDrawup) {
        int result = amBdgtDrawupRepository.updateAmBdgtDrawup(amBdgtDrawup);
        return result;
    }

    @Transactional
    public int removeAmBdgtDrawup(Long id) {
        int rows = amBdgtDrawupRepository.deleteAmBdgtDrawup(id);
        return rows;
    }

    public AmBdgtDrawup getAmBdgtDrawup(Long id) {
        AmBdgtDrawup amBdgtDrawup = amBdgtDrawupRepository.getAmBdgtDrawup(id);

        return amBdgtDrawup;
    }

    public int listAmBdgtDrawupCnt(Map<String, Object> params) {
        int rows = amBdgtDrawupRepository.listAmBdgtDrawupCnt(params);
        return rows;
    }

    public List<AmBdgtDrawup> listAmBdgtDrawup(Map<String, Object> params) {
        List<AmBdgtDrawup> lists = amBdgtDrawupRepository.listAmBdgtDrawup(params);

        return lists;
    }

    public List<AmBdgtDrawup> listAmBdgtDrawupByIds(List<Long> ids, Map<String, Object> params) {
        params.put("ids", ids);
        QueryTool.setDefaultOrderBy(new OrderBy("COMPANY_CODE", ids));
        QueryTool.setDefaultOrderBy(new OrderBy("DEPT_CODE", ids));
        QueryTool.setDefaultOrderBy(new OrderBy("PROJ_CODE", ids));
        QueryTool.setDefaultOrderBy(new OrderBy("ACNT_CODE", ids));
        QueryTool.setDefaultOrderBy(new OrderBy("DRAWUP_YYMM", ids));
        List<AmBdgtDrawup> lists = amBdgtDrawupRepository.listAmBdgtDrawup(params);

        return lists;
    }

    //endregion

}
