/*
 * Source code generated by UnvUS.
 * Copyright(c) 2017 unvus.com All rights reserved.
 * Template skrull-pack-mybatis:src/main/java/service/Service.e.vm.java
 * Template is part of project: https://git.unvus.com/unvus/opensource/pack-unvus-mybatis
 */
package com.neofect.gts.core.services.am.service;

import java.util.List;
import java.util.Map;

import org.springframework.stereotype.Service;
import org.springframework.transaction.annotation.Transactional;

import com.neofect.gts.core.services.am.domain.AmCodeDept;
import com.neofect.gts.core.services.am.repository.AmCodeDeptRepository;
import com.unvus.config.mybatis.pagination.OrderBy;
import com.unvus.query.QueryTool;

/**
 * Service for {@link AmCodeDept}<br/>
 */
@Service
public class AmCodeDeptService {

    private final AmCodeDeptRepository amCodeDeptRepository;

    public AmCodeDeptService(AmCodeDeptRepository amCodeDeptRepository) {
        this.amCodeDeptRepository = amCodeDeptRepository;
    }

    //region ------------------------------------------------------------------------------------------------ amCodeDept CRUD

    @Transactional
    public AmCodeDept saveAmCodeDept(AmCodeDept amCodeDept) {
        // if (amCodeDept.getId() == null) {
        //     addAmCodeDept(amCodeDept);
        // } else {
        //     modifyAmCodeDept(amCodeDept);
        // }

        return amCodeDept;
    }

    private int addAmCodeDept(AmCodeDept amCodeDept) {
        int result = amCodeDeptRepository.insertAmCodeDept(amCodeDept);
        return result;
    }

    private int modifyAmCodeDept(AmCodeDept amCodeDept) {
        int result = amCodeDeptRepository.updateAmCodeDept(amCodeDept);
        return result;
    }

    @Transactional
    public int removeAmCodeDept(Long id) {
        int rows = amCodeDeptRepository.deleteAmCodeDept(id);
        return rows;
    }

    public AmCodeDept getAmCodeDept(Long id) {
        AmCodeDept amCodeDept = amCodeDeptRepository.getAmCodeDept(id);

        return amCodeDept;
    }

    public int listAmCodeDeptCnt(Map<String, Object> params) {
        int rows = amCodeDeptRepository.listAmCodeDeptCnt(params);
        return rows;
    }

    public List<AmCodeDept> listAmCodeDept(Map<String, Object> params) {
        List<AmCodeDept> lists = amCodeDeptRepository.listAmCodeDept(params);

        return lists;
    }

    public List<AmCodeDept> listAmCodeDeptByIds(List<Long> ids, Map<String, Object> params) {
        params.put("ids", ids);
        QueryTool.setDefaultOrderBy(new OrderBy("COMPANY_CODE", ids));
        QueryTool.setDefaultOrderBy(new OrderBy("DEPT_CODE", ids));
        List<AmCodeDept> lists = amCodeDeptRepository.listAmCodeDept(params);

        return lists;
    }

    //endregion

}
