/*
 * Source code generated by UnvUS.
 * Copyright(c) 2017 unvus.com All rights reserved.
 * Template skrull-pack-mybatis:src/main/java/domain/EntityBase.e.vm.java
 * Template is part of project: https://git.unvus.com/unvus/opensource/pack-unvus-mybatis
 */
package com.neofect.gts.core.services.gs.domain;

import java.io.Serializable;
import java.time.LocalDateTime;
import java.util.HashMap;
import java.util.Map;

import org.apache.ibatis.type.Alias;

import lombok.Data;

/**
 * @see com.neofect.gts.core.services.gs.domain.IncentiveReceipt
 */
@Alias("gs_incentiveReceipt_")
@Data
public abstract class IncentiveReceipt_ implements Serializable {

    private static final long serialVersionUID = 1L;

    // Raw attributes
    /**
    * 지사ID
    */
    protected String deptId;
    /**
    * 사번
    */
    protected String memberId;
    /**
    * 지불일자
    */
    protected LocalDateTime payDate;
    /**
    * 지불금액
    */
    protected Integer payAmt;
    /**
    * 적요
    */
    protected String remark;
    protected String rowInputEmpNo;
    protected LocalDateTime rowInputDate;
    protected String rowInputIp;
    protected String rowUpdateEmpNo;
    protected String rowUpdateDate;
    protected String rowUpdateIp;

    protected Map<String, Object> _meta = new HashMap();
}
