/*
 * Source code generated by UnvUS.
 * Copyright(c) 2017 unvus.com All rights reserved.
 * Template skrull-pack-mybatis:src/main/java/rest/Rest.e.vm.java
 * Template is part of project: https://git.unvus.com/unvus/opensource/pack-unvus-mybatis
 */
package com.neofect.gts.web.cms.rest.am;

import java.net.URISyntaxException;
import java.util.HashMap;
import java.util.List;
import java.util.Map;

import org.springframework.http.HttpHeaders;
import org.springframework.http.HttpStatus;
import org.springframework.http.MediaType;
import org.springframework.http.ResponseEntity;
import org.springframework.web.bind.annotation.*;

import com.google.common.collect.ImmutableMap;
import com.neofect.gts.core.services.am.domain.AmBdgtDrawup;
import com.neofect.gts.core.services.am.service.AmBdgtDrawupService;
import com.unvus.web.util.PaginationUtil;

import lombok.extern.slf4j.Slf4j;

/**
 * Rest for {@link AmBdgtDrawup}<br/>
 */
@Slf4j
@RestController
@RequestMapping("/api")
public class AmBdgtDrawupResource {

    private final AmBdgtDrawupService amBdgtDrawupService;

    public AmBdgtDrawupResource(AmBdgtDrawupService amBdgtDrawupService) {
        this.amBdgtDrawupService = amBdgtDrawupService;
    }

    //region ------------------------------------------------------------------------------------------------ amBdgtDrawup API

    /**
     *
     */
    @GetMapping(value = "/am-bdgt-drawup", produces = MediaType.APPLICATION_JSON_VALUE)
    public ResponseEntity<List<AmBdgtDrawup>> listAmBdgtDrawup(@RequestParam(value = "q", required = false) Map<String, Object> q) throws URISyntaxException {
        if (q == null) {
            q = new HashMap();
        }

        List<AmBdgtDrawup> amBdgtDrawupList = amBdgtDrawupService.listAmBdgtDrawup(q);

        HttpHeaders headers = PaginationUtil.generatePaginationHttpHeaders();

        return new ResponseEntity<>(amBdgtDrawupList, headers, HttpStatus.OK);
    }

    /**
     * get count
     * @return
     */
    @GetMapping(value = "/am-bdgt-drawup/_count", produces = MediaType.APPLICATION_JSON_VALUE)
    public ResponseEntity<Map> getCount(@RequestParam(value = "q", required = false) Map<String, Object> q) {
        int count = amBdgtDrawupService.listAmBdgtDrawupCnt(q);

        return new ResponseEntity<>(ImmutableMap.of("count", count), HttpStatus.OK);
    }

    /**
     * get empty object
     * @return
     */
    @GetMapping(value = "/am-bdgt-drawup/_empty", produces = MediaType.APPLICATION_JSON_VALUE)
    public ResponseEntity<AmBdgtDrawup> getEmptyAmBdgtDrawup() {
        AmBdgtDrawup amBdgtDrawup = new AmBdgtDrawup();
        return new ResponseEntity<>(amBdgtDrawup, HttpStatus.OK);
    }

    /**
     * get
     */
    @GetMapping(value = "/am-bdgt-drawup/{id}", produces = MediaType.APPLICATION_JSON_VALUE)
    public ResponseEntity<AmBdgtDrawup> getAmBdgtDrawup(@PathVariable("id") Long id) {
        AmBdgtDrawup amBdgtDrawup = amBdgtDrawupService.getAmBdgtDrawup(id);
        return new ResponseEntity<>(amBdgtDrawup, HttpStatus.OK);
    }

    /**
     * add
     */
    @PostMapping("/am-bdgt-drawup")
    public ResponseEntity<Void> addAmBdgtDrawup(@RequestBody AmBdgtDrawup amBdgtDrawup) {
        amBdgtDrawupService.saveAmBdgtDrawup(amBdgtDrawup);

        return ResponseEntity.ok().build();
    }

    /**
     * modify
     */
    @PutMapping("/am-bdgt-drawup/{id}")
    public ResponseEntity<Void> updateAmBdgtDrawup(@PathVariable("id") Long id, @RequestBody AmBdgtDrawup amBdgtDrawup) throws Exception {
        // if (!id.equals(amBdgtDrawup.getId())) {
        //     return new ResponseEntity(HttpStatus.BAD_REQUEST);
        // }
        amBdgtDrawupService.saveAmBdgtDrawup(amBdgtDrawup);
        return ResponseEntity.ok().build();
    }

    /**
     * delete
     */
    @DeleteMapping("/am-bdgt-drawup/{id}")
    public ResponseEntity<Void> removeAmBdgtDrawup(@PathVariable("id") Long id) {
        amBdgtDrawupService.removeAmBdgtDrawup(id);
        return ResponseEntity.ok().build();
    }

    //endregion

}
