/*
 * Source code generated by UnvUS.
 * Copyright(c) 2017 unvus.com All rights reserved.
 * Template skrull-pack-mybatis:src/main/java/rest/Rest.e.vm.java
 * Template is part of project: https://git.unvus.com/unvus/opensource/pack-unvus-mybatis
 */
package com.neofect.gts.web.cms.rest.am;

import java.net.URISyntaxException;
import java.util.HashMap;
import java.util.List;
import java.util.Map;

import org.springframework.http.HttpHeaders;
import org.springframework.http.HttpStatus;
import org.springframework.http.MediaType;
import org.springframework.http.ResponseEntity;
import org.springframework.web.bind.annotation.*;

import com.google.common.collect.ImmutableMap;
import com.neofect.gts.core.services.am.domain.AmCalcKind;
import com.neofect.gts.core.services.am.service.AmCalcKindService;
import com.unvus.web.util.PaginationUtil;

import lombok.extern.slf4j.Slf4j;

/**
 * Rest for {@link AmCalcKind}<br/>
 */
@Slf4j
@RestController
@RequestMapping("/api")
public class AmCalcKindResource {

    private final AmCalcKindService amCalcKindService;

    public AmCalcKindResource(AmCalcKindService amCalcKindService) {
        this.amCalcKindService = amCalcKindService;
    }

    //region ------------------------------------------------------------------------------------------------ amCalcKind API

    /**
     *
     */
    @GetMapping(value = "/am-calc-kind", produces = MediaType.APPLICATION_JSON_VALUE)
    public ResponseEntity<List<AmCalcKind>> listAmCalcKind(@RequestParam(value = "q", required = false) Map<String, Object> q) throws URISyntaxException {
        if (q == null) {
            q = new HashMap();
        }

        List<AmCalcKind> amCalcKindList = amCalcKindService.listAmCalcKind(q);

        HttpHeaders headers = PaginationUtil.generatePaginationHttpHeaders();

        return new ResponseEntity<>(amCalcKindList, headers, HttpStatus.OK);
    }

    /**
     * get count
     * @return
     */
    @GetMapping(value = "/am-calc-kind/_count", produces = MediaType.APPLICATION_JSON_VALUE)
    public ResponseEntity<Map> getCount(@RequestParam(value = "q", required = false) Map<String, Object> q) {
        int count = amCalcKindService.listAmCalcKindCnt(q);

        return new ResponseEntity<>(ImmutableMap.of("count", count), HttpStatus.OK);
    }

    /**
     * get empty object
     * @return
     */
    @GetMapping(value = "/am-calc-kind/_empty", produces = MediaType.APPLICATION_JSON_VALUE)
    public ResponseEntity<AmCalcKind> getEmptyAmCalcKind() {
        AmCalcKind amCalcKind = new AmCalcKind();
        return new ResponseEntity<>(amCalcKind, HttpStatus.OK);
    }

    /**
     * get
     */
    @GetMapping(value = "/am-calc-kind/{id}", produces = MediaType.APPLICATION_JSON_VALUE)
    public ResponseEntity<AmCalcKind> getAmCalcKind(@PathVariable("id") Long id) {
        AmCalcKind amCalcKind = amCalcKindService.getAmCalcKind(id);
        return new ResponseEntity<>(amCalcKind, HttpStatus.OK);
    }

    /**
     * add
     */
    @PostMapping("/am-calc-kind")
    public ResponseEntity<Void> addAmCalcKind(@RequestBody AmCalcKind amCalcKind) {
        amCalcKindService.saveAmCalcKind(amCalcKind);

        return ResponseEntity.ok().build();
    }

    /**
     * modify
     */
    @PutMapping("/am-calc-kind/{id}")
    public ResponseEntity<Void> updateAmCalcKind(@PathVariable("id") Long id, @RequestBody AmCalcKind amCalcKind) throws Exception {
        // if (!id.equals(amCalcKind.getId())) {
        //     return new ResponseEntity(HttpStatus.BAD_REQUEST);
        // }
        amCalcKindService.saveAmCalcKind(amCalcKind);
        return ResponseEntity.ok().build();
    }

    /**
     * delete
     */
    @DeleteMapping("/am-calc-kind/{id}")
    public ResponseEntity<Void> removeAmCalcKind(@PathVariable("id") Long id) {
        amCalcKindService.removeAmCalcKind(id);
        return ResponseEntity.ok().build();
    }

    //endregion

}
