/*
 * Source code generated by UnvUS.
 * Copyright(c) 2017 unvus.com All rights reserved.
 * Template skrull-pack-mybatis:src/main/java/rest/Rest.e.vm.java
 * Template is part of project: https://git.unvus.com/unvus/opensource/pack-unvus-mybatis
 */
package com.neofect.gts.web.cms.rest.am;

import java.net.URISyntaxException;
import java.util.HashMap;
import java.util.List;
import java.util.Map;

import org.springframework.http.HttpHeaders;
import org.springframework.http.HttpStatus;
import org.springframework.http.MediaType;
import org.springframework.http.ResponseEntity;
import org.springframework.web.bind.annotation.*;

import com.google.common.collect.ImmutableMap;
import com.neofect.gts.core.services.am.domain.AmCodeRate;
import com.neofect.gts.core.services.am.service.AmCodeRateService;
import com.unvus.web.util.PaginationUtil;

import lombok.extern.slf4j.Slf4j;

/**
 * Rest for {@link AmCodeRate}<br/>
 */
@Slf4j
@RestController
@RequestMapping("/api")
public class AmCodeRateResource {

    private final AmCodeRateService amCodeRateService;

    public AmCodeRateResource(AmCodeRateService amCodeRateService) {
        this.amCodeRateService = amCodeRateService;
    }

    //region ------------------------------------------------------------------------------------------------ amCodeRate API

    /**
     *
     */
    @GetMapping(value = "/am-code-rate", produces = MediaType.APPLICATION_JSON_VALUE)
    public ResponseEntity<List<AmCodeRate>> listAmCodeRate(@RequestParam(value = "q", required = false) Map<String, Object> q) throws URISyntaxException {
        if (q == null) {
            q = new HashMap();
        }

        List<AmCodeRate> amCodeRateList = amCodeRateService.listAmCodeRate(q);

        HttpHeaders headers = PaginationUtil.generatePaginationHttpHeaders();

        return new ResponseEntity<>(amCodeRateList, headers, HttpStatus.OK);
    }

    /**
     * get count
     * @return
     */
    @GetMapping(value = "/am-code-rate/_count", produces = MediaType.APPLICATION_JSON_VALUE)
    public ResponseEntity<Map> getCount(@RequestParam(value = "q", required = false) Map<String, Object> q) {
        int count = amCodeRateService.listAmCodeRateCnt(q);

        return new ResponseEntity<>(ImmutableMap.of("count", count), HttpStatus.OK);
    }

    /**
     * get empty object
     * @return
     */
    @GetMapping(value = "/am-code-rate/_empty", produces = MediaType.APPLICATION_JSON_VALUE)
    public ResponseEntity<AmCodeRate> getEmptyAmCodeRate() {
        AmCodeRate amCodeRate = new AmCodeRate();
        return new ResponseEntity<>(amCodeRate, HttpStatus.OK);
    }

    /**
     * get
     */
    @GetMapping(value = "/am-code-rate/{id}", produces = MediaType.APPLICATION_JSON_VALUE)
    public ResponseEntity<AmCodeRate> getAmCodeRate(@PathVariable("id") Long id) {
        AmCodeRate amCodeRate = amCodeRateService.getAmCodeRate(id);
        return new ResponseEntity<>(amCodeRate, HttpStatus.OK);
    }

    /**
     * add
     */
    @PostMapping("/am-code-rate")
    public ResponseEntity<Void> addAmCodeRate(@RequestBody AmCodeRate amCodeRate) {
        amCodeRateService.saveAmCodeRate(amCodeRate);

        return ResponseEntity.ok().build();
    }

    /**
     * modify
     */
    @PutMapping("/am-code-rate/{id}")
    public ResponseEntity<Void> updateAmCodeRate(@PathVariable("id") Long id, @RequestBody AmCodeRate amCodeRate) throws Exception {
        if (!id.equals(amCodeRate.getId())) {
            return new ResponseEntity(HttpStatus.BAD_REQUEST);
        }
        amCodeRateService.saveAmCodeRate(amCodeRate);
        return ResponseEntity.ok().build();
    }

    /**
     * delete
     */
    @DeleteMapping("/am-code-rate/{id}")
    public ResponseEntity<Void> removeAmCodeRate(@PathVariable("id") Long id) {
        amCodeRateService.removeAmCodeRate(id);
        return ResponseEntity.ok().build();
    }

    //endregion

}
