/*
 * Source code generated by UnvUS.
 * Copyright(c) 2017 unvus.com All rights reserved.
 * Template skrull-pack-mybatis:src/main/java/rest/Rest.e.vm.java
 * Template is part of project: https://git.unvus.com/unvus/opensource/pack-unvus-mybatis
 */
package com.neofect.gts.web.cms.rest.am;

import java.net.URISyntaxException;
import java.util.HashMap;
import java.util.List;
import java.util.Map;

import org.springframework.http.HttpHeaders;
import org.springframework.http.HttpStatus;
import org.springframework.http.MediaType;
import org.springframework.http.ResponseEntity;
import org.springframework.web.bind.annotation.*;

import com.google.common.collect.ImmutableMap;
import com.neofect.gts.core.services.am.domain.AmCodeSourDiv;
import com.neofect.gts.core.services.am.service.AmCodeSourDivService;
import com.unvus.web.util.PaginationUtil;

import lombok.extern.slf4j.Slf4j;

/**
 * Rest for {@link AmCodeSourDiv}<br/>
 */
@Slf4j
@RestController
@RequestMapping("/api")
public class AmCodeSourDivResource {

    private final AmCodeSourDivService amCodeSourDivService;

    public AmCodeSourDivResource(AmCodeSourDivService amCodeSourDivService) {
        this.amCodeSourDivService = amCodeSourDivService;
    }

    //region ------------------------------------------------------------------------------------------------ amCodeSourDiv API

    /**
     *
     */
    @GetMapping(value = "/am-code-sour-div", produces = MediaType.APPLICATION_JSON_VALUE)
    public ResponseEntity<List<AmCodeSourDiv>> listAmCodeSourDiv(@RequestParam(value = "q", required = false) Map<String, Object> q) throws URISyntaxException {
        if (q == null) {
            q = new HashMap();
        }

        List<AmCodeSourDiv> amCodeSourDivList = amCodeSourDivService.listAmCodeSourDiv(q);

        HttpHeaders headers = PaginationUtil.generatePaginationHttpHeaders();

        return new ResponseEntity<>(amCodeSourDivList, headers, HttpStatus.OK);
    }

    /**
     * get count
     * @return
     */
    @GetMapping(value = "/am-code-sour-div/_count", produces = MediaType.APPLICATION_JSON_VALUE)
    public ResponseEntity<Map> getCount(@RequestParam(value = "q", required = false) Map<String, Object> q) {
        int count = amCodeSourDivService.listAmCodeSourDivCnt(q);

        return new ResponseEntity<>(ImmutableMap.of("count", count), HttpStatus.OK);
    }

    /**
     * get empty object
     * @return
     */
    @GetMapping(value = "/am-code-sour-div/_empty", produces = MediaType.APPLICATION_JSON_VALUE)
    public ResponseEntity<AmCodeSourDiv> getEmptyAmCodeSourDiv() {
        AmCodeSourDiv amCodeSourDiv = new AmCodeSourDiv();
        return new ResponseEntity<>(amCodeSourDiv, HttpStatus.OK);
    }

    /**
     * get
     */
    @GetMapping(value = "/am-code-sour-div/{id}", produces = MediaType.APPLICATION_JSON_VALUE)
    public ResponseEntity<AmCodeSourDiv> getAmCodeSourDiv(@PathVariable("id") Long id) {
        AmCodeSourDiv amCodeSourDiv = amCodeSourDivService.getAmCodeSourDiv(id);
        return new ResponseEntity<>(amCodeSourDiv, HttpStatus.OK);
    }

    /**
     * add
     */
    @PostMapping("/am-code-sour-div")
    public ResponseEntity<Void> addAmCodeSourDiv(@RequestBody AmCodeSourDiv amCodeSourDiv) {
        amCodeSourDivService.saveAmCodeSourDiv(amCodeSourDiv);

        return ResponseEntity.ok().build();
    }

    /**
     * modify
     */
    @PutMapping("/am-code-sour-div/{id}")
    public ResponseEntity<Void> updateAmCodeSourDiv(@PathVariable("id") Long id, @RequestBody AmCodeSourDiv amCodeSourDiv) throws Exception {
        if (!id.equals(amCodeSourDiv.getId())) {
            return new ResponseEntity(HttpStatus.BAD_REQUEST);
        }
        amCodeSourDivService.saveAmCodeSourDiv(amCodeSourDiv);
        return ResponseEntity.ok().build();
    }

    /**
     * delete
     */
    @DeleteMapping("/am-code-sour-div/{id}")
    public ResponseEntity<Void> removeAmCodeSourDiv(@PathVariable("id") Long id) {
        amCodeSourDivService.removeAmCodeSourDiv(id);
        return ResponseEntity.ok().build();
    }

    //endregion

}
