/*
 * Source code generated by UnvUS.
 * Copyright(c) 2017 unvus.com All rights reserved.
 * Template skrull-pack-mybatis:src/main/java/rest/Rest.e.vm.java
 * Template is part of project: https://git.unvus.com/unvus/opensource/pack-unvus-mybatis
 */
package com.neofect.gts.web.cms.rest.am;

import java.net.URISyntaxException;
import java.util.HashMap;
import java.util.List;
import java.util.Map;

import org.springframework.http.HttpHeaders;
import org.springframework.http.HttpStatus;
import org.springframework.http.MediaType;
import org.springframework.http.ResponseEntity;
import org.springframework.web.bind.annotation.*;

import com.google.common.collect.ImmutableMap;
import com.neofect.gts.core.services.am.domain.AmCodeAsset;
import com.neofect.gts.core.services.am.service.AmCodeAssetService;
import com.unvus.web.util.PaginationUtil;

import lombok.extern.slf4j.Slf4j;

/**
 * Rest for {@link AmCodeAsset}<br/>
 */
@Slf4j
@RestController
@RequestMapping("/api")
public class AmCodeAssetResource {

    private final AmCodeAssetService amCodeAssetService;

    public AmCodeAssetResource(AmCodeAssetService amCodeAssetService) {
        this.amCodeAssetService = amCodeAssetService;
    }

    //region ------------------------------------------------------------------------------------------------ amCodeAsset API

    /**
     *
     */
    @GetMapping(value = "/am-code-asset", produces = MediaType.APPLICATION_JSON_VALUE)
    public ResponseEntity<List<AmCodeAsset>> listAmCodeAsset(@RequestParam(value = "q", required = false) Map<String, Object> q) throws URISyntaxException {
        if (q == null) {
            q = new HashMap();
        }

        List<AmCodeAsset> amCodeAssetList = amCodeAssetService.listAmCodeAsset(q);

        HttpHeaders headers = PaginationUtil.generatePaginationHttpHeaders();

        return new ResponseEntity<>(amCodeAssetList, headers, HttpStatus.OK);
    }

    /**
     * get count
     * @return
     */
    @GetMapping(value = "/am-code-asset/_count", produces = MediaType.APPLICATION_JSON_VALUE)
    public ResponseEntity<Map> getCount(@RequestParam(value = "q", required = false) Map<String, Object> q) {
        int count = amCodeAssetService.listAmCodeAssetCnt(q);

        return new ResponseEntity<>(ImmutableMap.of("count", count), HttpStatus.OK);
    }

    /**
     * get empty object
     * @return
     */
    @GetMapping(value = "/am-code-asset/_empty", produces = MediaType.APPLICATION_JSON_VALUE)
    public ResponseEntity<AmCodeAsset> getEmptyAmCodeAsset() {
        AmCodeAsset amCodeAsset = new AmCodeAsset();
        return new ResponseEntity<>(amCodeAsset, HttpStatus.OK);
    }

    /**
     * get
     */
    @GetMapping(value = "/am-code-asset/{id}", produces = MediaType.APPLICATION_JSON_VALUE)
    public ResponseEntity<AmCodeAsset> getAmCodeAsset(@PathVariable("id") Long id) {
        AmCodeAsset amCodeAsset = amCodeAssetService.getAmCodeAsset(id);
        return new ResponseEntity<>(amCodeAsset, HttpStatus.OK);
    }

    /**
     * add
     */
    @PostMapping("/am-code-asset")
    public ResponseEntity<Void> addAmCodeAsset(@RequestBody AmCodeAsset amCodeAsset) {
        amCodeAssetService.saveAmCodeAsset(amCodeAsset);

        return ResponseEntity.ok().build();
    }

    /**
     * modify
     */
    @PutMapping("/am-code-asset/{id}")
    public ResponseEntity<Void> updateAmCodeAsset(@PathVariable("id") Long id, @RequestBody AmCodeAsset amCodeAsset) throws Exception {
        // if (!id.equals(amCodeAsset.getId())) {
        //     return new ResponseEntity(HttpStatus.BAD_REQUEST);
        // }
        amCodeAssetService.saveAmCodeAsset(amCodeAsset);
        return ResponseEntity.ok().build();
    }

    /**
     * delete
     */
    @DeleteMapping("/am-code-asset/{id}")
    public ResponseEntity<Void> removeAmCodeAsset(@PathVariable("id") Long id) {
        amCodeAssetService.removeAmCodeAsset(id);
        return ResponseEntity.ok().build();
    }

    //endregion

}
