/*
 * Source code generated by UnvUS.
 * Copyright(c) 2017 unvus.com All rights reserved.
 * Template skrull-pack-mybatis:src/main/java/rest/Rest.e.vm.java
 * Template is part of project: https://git.unvus.com/unvus/opensource/pack-unvus-mybatis
 */
package com.neofect.gts.web.cms.rest.am;

import java.net.URISyntaxException;
import java.util.HashMap;
import java.util.List;
import java.util.Map;

import org.springframework.http.HttpHeaders;
import org.springframework.http.HttpStatus;
import org.springframework.http.MediaType;
import org.springframework.http.ResponseEntity;
import org.springframework.web.bind.annotation.*;

import com.google.common.collect.ImmutableMap;
import com.neofect.gts.core.services.am.domain.AmCodeCostCenter;
import com.neofect.gts.core.services.am.service.AmCodeCostCenterService;
import com.unvus.web.util.PaginationUtil;

import lombok.extern.slf4j.Slf4j;

/**
 * Rest for {@link AmCodeCostCenter}<br/>
 */
@Slf4j
@RestController
@RequestMapping("/api")
public class AmCodeCostCenterResource {

    private final AmCodeCostCenterService amCodeCostCenterService;

    public AmCodeCostCenterResource(AmCodeCostCenterService amCodeCostCenterService) {
        this.amCodeCostCenterService = amCodeCostCenterService;
    }

    //region ------------------------------------------------------------------------------------------------ amCodeCostCenter API

    /**
     *
     */
    @GetMapping(value = "/am-code-cost-center", produces = MediaType.APPLICATION_JSON_VALUE)
    public ResponseEntity<List<AmCodeCostCenter>> listAmCodeCostCenter(@RequestParam(value = "q", required = false) Map<String, Object> q)
            throws URISyntaxException {
        if (q == null) {
            q = new HashMap();
        }

        List<AmCodeCostCenter> amCodeCostCenterList = amCodeCostCenterService.listAmCodeCostCenter(q);

        HttpHeaders headers = PaginationUtil.generatePaginationHttpHeaders();

        return new ResponseEntity<>(amCodeCostCenterList, headers, HttpStatus.OK);
    }

    /**
     * get count
     * @return
     */
    @GetMapping(value = "/am-code-cost-center/_count", produces = MediaType.APPLICATION_JSON_VALUE)
    public ResponseEntity<Map> getCount(@RequestParam(value = "q", required = false) Map<String, Object> q) {
        int count = amCodeCostCenterService.listAmCodeCostCenterCnt(q);

        return new ResponseEntity<>(ImmutableMap.of("count", count), HttpStatus.OK);
    }

    /**
     * get empty object
     * @return
     */
    @GetMapping(value = "/am-code-cost-center/_empty", produces = MediaType.APPLICATION_JSON_VALUE)
    public ResponseEntity<AmCodeCostCenter> getEmptyAmCodeCostCenter() {
        AmCodeCostCenter amCodeCostCenter = new AmCodeCostCenter();
        return new ResponseEntity<>(amCodeCostCenter, HttpStatus.OK);
    }

    /**
     * get
     */
    @GetMapping(value = "/am-code-cost-center/{id}", produces = MediaType.APPLICATION_JSON_VALUE)
    public ResponseEntity<AmCodeCostCenter> getAmCodeCostCenter(@PathVariable("id") Long id) {
        AmCodeCostCenter amCodeCostCenter = amCodeCostCenterService.getAmCodeCostCenter(id);
        return new ResponseEntity<>(amCodeCostCenter, HttpStatus.OK);
    }

    /**
     * add
     */
    @PostMapping("/am-code-cost-center")
    public ResponseEntity<Void> addAmCodeCostCenter(@RequestBody AmCodeCostCenter amCodeCostCenter) {
        amCodeCostCenterService.saveAmCodeCostCenter(amCodeCostCenter);

        return ResponseEntity.ok().build();
    }

    /**
     * modify
     */
    @PutMapping("/am-code-cost-center/{id}")
    public ResponseEntity<Void> updateAmCodeCostCenter(@PathVariable("id") Long id, @RequestBody AmCodeCostCenter amCodeCostCenter) throws Exception {
        // if (!id.equals(amCodeCostCenter.getId())) {
        //     return new ResponseEntity(HttpStatus.BAD_REQUEST);
        // }
        amCodeCostCenterService.saveAmCodeCostCenter(amCodeCostCenter);
        return ResponseEntity.ok().build();
    }

    /**
     * delete
     */
    @DeleteMapping("/am-code-cost-center/{id}")
    public ResponseEntity<Void> removeAmCodeCostCenter(@PathVariable("id") Long id) {
        amCodeCostCenterService.removeAmCodeCostCenter(id);
        return ResponseEntity.ok().build();
    }

    //endregion

}
