/*
 * Source code generated by UnvUS.
 * Copyright(c) 2017 unvus.com All rights reserved.
 * Template skrull-pack-mybatis:src/main/java/service/Service.e.vm.java
 * Template is part of project: https://git.unvus.com/unvus/opensource/pack-unvus-mybatis
 */
package com.neofect.gts.core.services.lease.service;

import java.util.List;
import java.util.Map;

import org.springframework.stereotype.Service;
import org.springframework.transaction.annotation.Transactional;

import com.neofect.gts.core.services.lease.domain.LeaseContract;
import com.neofect.gts.core.services.lease.repository.LeaseContractRepository;
import com.unvus.config.mybatis.pagination.OrderBy;
import com.unvus.query.QueryTool;

/**
 * Service for {@link LeaseContract}<br/>
 */
@Service
public class LeaseContractService {

    private final LeaseContractRepository leaseContractRepository;

    public LeaseContractService(LeaseContractRepository leaseContractRepository) {
        this.leaseContractRepository = leaseContractRepository;
    }

    //region ------------------------------------------------------------------------------------------------ leaseContract CRUD

    @Transactional
    public LeaseContract saveLeaseContract(LeaseContract leaseContract) {
        // if (leaseContract.getId() == null) {
        //     addLeaseContract(leaseContract);
        // } else {
        //     modifyLeaseContract(leaseContract);
        // }

        return leaseContract;
    }

    private int addLeaseContract(LeaseContract leaseContract) {
        int result = leaseContractRepository.insertLeaseContract(leaseContract);
        return result;
    }

    private int modifyLeaseContract(LeaseContract leaseContract) {
        int result = leaseContractRepository.updateLeaseContract(leaseContract);
        return result;
    }

    @Transactional
    public int removeLeaseContract(Long id) {
        int rows = leaseContractRepository.deleteLeaseContract(id);
        return rows;
    }

    public LeaseContract getLeaseContract(Long id) {
        LeaseContract leaseContract = leaseContractRepository.getLeaseContract(id);

        return leaseContract;
    }

    public int listLeaseContractCnt(Map<String, Object> params) {
        int rows = leaseContractRepository.listLeaseContractCnt(params);
        return rows;
    }

    public List<LeaseContract> listLeaseContract(Map<String, Object> params) {
        List<LeaseContract> lists = leaseContractRepository.listLeaseContract(params);

        return lists;
    }

    public List<LeaseContract> listLeaseContractByIds(List<Long> ids, Map<String, Object> params) {
        params.put("ids", ids);
        QueryTool.setDefaultOrderBy(new OrderBy("DEPT_ID", ids));
        QueryTool.setDefaultOrderBy(new OrderBy("L_ID", ids));
        List<LeaseContract> lists = leaseContractRepository.listLeaseContract(params);

        return lists;
    }

    //endregion

}
