/*
 * Source code generated by UnvUS.
 * Copyright(c) 2017 unvus.com All rights reserved.
 * Template skrull-pack-mybatis:src/main/java/domain/EntityBase.e.vm.java
 * Template is part of project: https://git.unvus.com/unvus/opensource/pack-unvus-mybatis
 */
package com.neofect.gts.core.services.xg.domain;

import java.io.Serializable;
import java.time.LocalDateTime;
import java.util.HashMap;
import java.util.Map;

import org.apache.ibatis.type.Alias;

import lombok.Data;

/**
 * @see com.neofect.gts.core.services.xg.domain.XgComtnLoginlog
 */
@Alias("xg_xgComtnLoginlog_")
@Data
public abstract class XgComtnLoginlog_ implements Serializable {

    private static final long serialVersionUID = 1L;

    // Raw attributes
    protected String companyCode;
    protected String logId;
    protected String conectId;
    protected String conectIp;
    protected String conectMthd;
    protected String errorOccrrncAt;
    protected String errorCode;
    protected LocalDateTime creatDt;

    protected Map<String, Object> _meta = new HashMap();
}
