/*
 * Source code generated by UnvUS.
 * Copyright(c) 2017 unvus.com All rights reserved.
 * Template skrull-pack-mybatis:src/main/java/domain/EntityBase.e.vm.java
 * Template is part of project: https://git.unvus.com/unvus/opensource/pack-unvus-mybatis
 */
package com.neofect.gts.core.services.xg.domain;

import java.io.Serializable;
import java.util.HashMap;
import java.util.Map;

import org.apache.ibatis.type.Alias;

import lombok.Data;

/**
 * @see com.neofect.gts.core.services.xg.domain.XgSysSvclog
 */
@Alias("xg_xgSysSvclog_")
@Data
public abstract class XgSysSvclog_ implements Serializable {

    private static final long serialVersionUID = 1L;

    // Raw attributes
    protected String companyCode;
    protected Long requstId;
    protected String jobSeCode;
    protected String insttCode;
    protected String occrrncDe;
    protected String rqesterIp;
    protected String rqesterId;
    protected String trgetMenuNm;
    protected String svcNm;
    protected String methodNm;
    protected String processSeCode;
    protected Integer processCo;
    protected Long processTime;
    protected String rspnsCode;
    protected String errorSe;
    protected Integer errorCo;
    protected String errorCode;
    protected Long packetSize;

    protected Map<String, Object> _meta = new HashMap();
}
