/*
 * Source code generated by UnvUS.
 * Copyright(c) 2017 unvus.com All rights reserved.
 * Template skrull-pack-mybatis:src/main/java/domain/Entity.e.vm.java
 * Template is part of project: https://git.unvus.com/unvus/opensource/pack-unvus-mybatis
 */
package com.neofect.gts.core.services.am.domain;

import java.io.Serializable;

import org.apache.ibatis.type.Alias;

import lombok.Data;

/**
 * AM_재무제표_산식종류별계정
 */

@Alias("amCalcAcnt")
@Data
public class AmCalcAcnt extends AmCalcAcnt_ implements Serializable {

    private static final long serialVersionUID = 1L;

}
