/*
 * Source code generated by UnvUS.
 * Copyright(c) 2017 unvus.com All rights reserved.
 * Template skrull-pack-mybatis:src/main/java/rest/Rest.e.vm.java
 * Template is part of project: https://git.unvus.com/unvus/opensource/pack-unvus-mybatis
 */
package com.neofect.gts.web.cms.rest.zp;

import java.net.URISyntaxException;
import java.util.HashMap;
import java.util.List;
import java.util.Map;

import org.springframework.http.HttpHeaders;
import org.springframework.http.HttpStatus;
import org.springframework.http.MediaType;
import org.springframework.http.ResponseEntity;
import org.springframework.web.bind.annotation.*;

import com.google.common.collect.ImmutableMap;
import com.neofect.gts.core.services.zp.domain.ZDwoconfig;
import com.neofect.gts.core.services.zp.service.ZDwoconfigService;
import com.unvus.web.util.PaginationUtil;

import lombok.extern.slf4j.Slf4j;

/**
 * Rest for {@link ZDwoconfig}<br/>
 */
@Slf4j
@RestController
@RequestMapping("/api")
public class ZDwoconfigResource {

    private final ZDwoconfigService zDwoconfigService;

    public ZDwoconfigResource(ZDwoconfigService zDwoconfigService) {
        this.zDwoconfigService = zDwoconfigService;
    }

    //region ------------------------------------------------------------------------------------------------ zDwoconfig API

    /**
     *
     */
    @GetMapping(value = "/z-dwoconfig", produces = MediaType.APPLICATION_JSON_VALUE)
    public ResponseEntity<List<ZDwoconfig>> listZDwoconfig(@RequestParam(value = "q", required = false) Map<String, Object> q) throws URISyntaxException {
        if (q == null) {
            q = new HashMap();
        }

        List<ZDwoconfig> zDwoconfigList = zDwoconfigService.listZDwoconfig(q);

        HttpHeaders headers = PaginationUtil.generatePaginationHttpHeaders();

        return new ResponseEntity<>(zDwoconfigList, headers, HttpStatus.OK);
    }

    /**
     * get count
     * @return
     */
    @GetMapping(value = "/z-dwoconfig/_count", produces = MediaType.APPLICATION_JSON_VALUE)
    public ResponseEntity<Map> getCount(@RequestParam(value = "q", required = false) Map<String, Object> q) {
        int count = zDwoconfigService.listZDwoconfigCnt(q);

        return new ResponseEntity<>(ImmutableMap.of("count", count), HttpStatus.OK);
    }

    /**
     * get empty object
     * @return
     */
    @GetMapping(value = "/z-dwoconfig/_empty", produces = MediaType.APPLICATION_JSON_VALUE)
    public ResponseEntity<ZDwoconfig> getEmptyZDwoconfig() {
        ZDwoconfig zDwoconfig = new ZDwoconfig();
        return new ResponseEntity<>(zDwoconfig, HttpStatus.OK);
    }

    /**
     * get
     */
    @GetMapping(value = "/z-dwoconfig/{id}", produces = MediaType.APPLICATION_JSON_VALUE)
    public ResponseEntity<ZDwoconfig> getZDwoconfig(@PathVariable("id") Long id) {
        ZDwoconfig zDwoconfig = zDwoconfigService.getZDwoconfig(id);
        return new ResponseEntity<>(zDwoconfig, HttpStatus.OK);
    }

    /**
     * add
     */
    @PostMapping("/z-dwoconfig")
    public ResponseEntity<Void> addZDwoconfig(@RequestBody ZDwoconfig zDwoconfig) {
        zDwoconfigService.saveZDwoconfig(zDwoconfig);

        return ResponseEntity.ok().build();
    }

    /**
     * modify
     */
    @PutMapping("/z-dwoconfig/{id}")
    public ResponseEntity<Void> updateZDwoconfig(@PathVariable("id") Long id, @RequestBody ZDwoconfig zDwoconfig) throws Exception {
        // if (!id.equals(zDwoconfig.getId())) {
        //     return new ResponseEntity(HttpStatus.BAD_REQUEST);
        // }
        zDwoconfigService.saveZDwoconfig(zDwoconfig);
        return ResponseEntity.ok().build();
    }

    /**
     * delete
     */
    @DeleteMapping("/z-dwoconfig/{id}")
    public ResponseEntity<Void> removeZDwoconfig(@PathVariable("id") Long id) {
        zDwoconfigService.removeZDwoconfig(id);
        return ResponseEntity.ok().build();
    }

    //endregion

}
