/*
 * Source code generated by UnvUS.
 * Copyright(c) 2017 unvus.com All rights reserved.
 * Template skrull-pack-mybatis:src/main/java/rest/Rest.e.vm.java
 * Template is part of project: https://git.unvus.com/unvus/opensource/pack-unvus-mybatis
 */
package com.neofect.gts.web.cms.rest.zp;

import java.net.URISyntaxException;
import java.util.HashMap;
import java.util.List;
import java.util.Map;

import org.springframework.http.HttpHeaders;
import org.springframework.http.HttpStatus;
import org.springframework.http.MediaType;
import org.springframework.http.ResponseEntity;
import org.springframework.web.bind.annotation.*;

import com.google.common.collect.ImmutableMap;
import com.neofect.gts.core.services.zp.domain.ZPgmcode;
import com.neofect.gts.core.services.zp.service.ZPgmcodeService;
import com.unvus.web.util.PaginationUtil;

import lombok.extern.slf4j.Slf4j;

/**
 * Rest for {@link ZPgmcode}<br/>
 */
@Slf4j
@RestController
@RequestMapping("/api")
public class ZPgmcodeResource {

    private final ZPgmcodeService zPgmcodeService;

    public ZPgmcodeResource(ZPgmcodeService zPgmcodeService) {
        this.zPgmcodeService = zPgmcodeService;
    }

    //region ------------------------------------------------------------------------------------------------ zPgmcode API

    /**
     *
     */
    @GetMapping(value = "/z-pgmcode", produces = MediaType.APPLICATION_JSON_VALUE)
    public ResponseEntity<List<ZPgmcode>> listZPgmcode(@RequestParam(value = "q", required = false) Map<String, Object> q) throws URISyntaxException {
        if (q == null) {
            q = new HashMap();
        }

        List<ZPgmcode> zPgmcodeList = zPgmcodeService.listZPgmcode(q);

        HttpHeaders headers = PaginationUtil.generatePaginationHttpHeaders();

        return new ResponseEntity<>(zPgmcodeList, headers, HttpStatus.OK);
    }

    /**
     * get count
     * @return
     */
    @GetMapping(value = "/z-pgmcode/_count", produces = MediaType.APPLICATION_JSON_VALUE)
    public ResponseEntity<Map> getCount(@RequestParam(value = "q", required = false) Map<String, Object> q) {
        int count = zPgmcodeService.listZPgmcodeCnt(q);

        return new ResponseEntity<>(ImmutableMap.of("count", count), HttpStatus.OK);
    }

    /**
     * get empty object
     * @return
     */
    @GetMapping(value = "/z-pgmcode/_empty", produces = MediaType.APPLICATION_JSON_VALUE)
    public ResponseEntity<ZPgmcode> getEmptyZPgmcode() {
        ZPgmcode zPgmcode = new ZPgmcode();
        return new ResponseEntity<>(zPgmcode, HttpStatus.OK);
    }

    /**
     * get
     */
    @GetMapping(value = "/z-pgmcode/{id}", produces = MediaType.APPLICATION_JSON_VALUE)
    public ResponseEntity<ZPgmcode> getZPgmcode(@PathVariable("id") Long id) {
        ZPgmcode zPgmcode = zPgmcodeService.getZPgmcode(id);
        return new ResponseEntity<>(zPgmcode, HttpStatus.OK);
    }

    /**
     * add
     */
    @PostMapping("/z-pgmcode")
    public ResponseEntity<Void> addZPgmcode(@RequestBody ZPgmcode zPgmcode) {
        zPgmcodeService.saveZPgmcode(zPgmcode);

        return ResponseEntity.ok().build();
    }

    /**
     * modify
     */
    @PutMapping("/z-pgmcode/{id}")
    public ResponseEntity<Void> updateZPgmcode(@PathVariable("id") Long id, @RequestBody ZPgmcode zPgmcode) throws Exception {
        if (!id.equals(zPgmcode.getId())) {
            return new ResponseEntity(HttpStatus.BAD_REQUEST);
        }
        zPgmcodeService.saveZPgmcode(zPgmcode);
        return ResponseEntity.ok().build();
    }

    /**
     * delete
     */
    @DeleteMapping("/z-pgmcode/{id}")
    public ResponseEntity<Void> removeZPgmcode(@PathVariable("id") Long id) {
        zPgmcodeService.removeZPgmcode(id);
        return ResponseEntity.ok().build();
    }

    //endregion

}
