/*
 * Source code generated by UnvUS.
 * Copyright(c) 2017 unvus.com All rights reserved.
 * Template skrull-pack-mybatis:src/main/java/domain/EntityBase.e.vm.java
 * Template is part of project: https://git.unvus.com/unvus/opensource/pack-unvus-mybatis
 */
package com.neofect.gts.core.services.rent.domain;

import java.io.Serializable;
import java.time.LocalDateTime;
import java.util.HashMap;
import java.util.Map;

import org.apache.ibatis.type.Alias;

import lombok.Data;

/**
 * @see com.neofect.gts.core.services.rent.domain.RentReqMain
 */
@Alias("rent_rentReqMain_")
@Data
public abstract class RentReqMain_ implements Serializable {

    private static final long serialVersionUID = 1L;

    // Raw attributes
    /**
    * 지사ID
    */
    protected String deptId;
    /**
    * 입력일자
    */
    protected LocalDateTime enterDate;
    /**
    * 입력순번
    */
    protected Integer enterSeq;
    /**
    * 입력자
    */
    protected String enterId;
    /**
    * 수정자
    */
    protected String editId;
    /**
    * 수정일자
    */
    protected LocalDateTime editDate;
    /**
    * 승인자
    */
    protected String accId;
    /**
    * 승인일자
    */
    protected LocalDateTime accDate;
    /**
    * 적요
    */
    protected String remark;
    /**
    * 지사명
    */
    protected String deptName;
    /**
    * 거래처ID
    */
    protected Integer custId;
    /**
    * 거래처코드
    */
    protected String custCode;
    /**
    * 거래처명
    */
    protected String custName;
    /**
    * 요청일
    */
    protected LocalDateTime reqDate;
    /**
    * 입출고일자
    */
    protected LocalDateTime inoutDate;
    /**
    * 납기일자
    */
    protected LocalDateTime ndate;
    /**
    * 유효기간
    */
    protected LocalDateTime ydate;
    /**
    * 부가세포함여부
    */
    protected String vatDiv;
    /**
    * 지불조건
    */
    protected String paycond;
    /**
    * 납품조건
    */
    protected String delicond;
    /**
    * 요청자ID
    */
    protected String reqId;
    /**
    * 발의전표일자
    */
    protected LocalDateTime bSlipDate;
    /**
    * 발의지사ID
    */
    protected Integer bDeptId;
    /**
    * 발의전표번호
    */
    protected Integer bSlipSeq;
    /**
    * 처리지사ID
    */
    protected String pdeptId;
    /**
    * 시작일
    */
    protected LocalDateTime startDate;
    /**
    * 종료일
    */
    protected LocalDateTime endDate;
    /**
    * 현재상태
    */
    protected String orderStatus;
    protected String rowInputEmpNo;
    protected LocalDateTime rowInputDate;
    protected String rowInputIp;
    protected String rowUpdateEmpNo;
    protected LocalDateTime rowUpdateDate;
    protected String rowUpdateIp;
    /**
    * 전화번호
    */
    protected String phone;
    /**
    * 팩스번호
    */
    protected String fax;
    /**
    * 핸드폰
    */
    protected String hp;
    /**
    * 이메일
    */
    protected String email;
    /**
    * 담당자성명
    */
    protected String managerName;
    /**
    * 담당자전화
    */
    protected String managerPhone;
    /**
    * 담당자핸드폰
    */
    protected String managerHp;

    protected Map<String, Object> _meta = new HashMap();
}
