/*
 * Source code generated by UnvUS.
 * Copyright(c) 2017 unvus.com All rights reserved.
 * Template skrull-pack-mybatis:src/main/java/service/Service.e.vm.java
 * Template is part of project: https://git.unvus.com/unvus/opensource/pack-unvus-mybatis
 */
package com.neofect.gts.core.services.rent.service;

import java.util.List;
import java.util.Map;

import org.springframework.stereotype.Service;
import org.springframework.transaction.annotation.Transactional;

import com.neofect.gts.core.services.rent.domain.RentContract;
import com.neofect.gts.core.services.rent.repository.RentContractRepository;
import com.unvus.config.mybatis.pagination.OrderBy;
import com.unvus.query.QueryTool;


/**
 * Service for {@link RentContract}<br/>
 */
@Service
public class RentContractService {

    private final RentContractRepository rentContractRepository;

    public RentContractService(RentContractRepository rentContractRepository) {
        this.rentContractRepository = rentContractRepository;
    }

    //region ------------------------------------------------------------------------------------------------ rentContract CRUD

    @Transactional
    public RentContract saveRentContract(RentContract rentContract) {
        // if (rentContract.getId() == null) {
        //     addRentContract(rentContract);
        // } else {
        //     modifyRentContract(rentContract);
        // }

        return rentContract;
    }

    private int addRentContract(RentContract rentContract) {
        int result = rentContractRepository.insertRentContract(rentContract);
        return result;
    }

    private int modifyRentContract(RentContract rentContract) {
        int result = rentContractRepository.updateRentContract(rentContract);
        return result;
    }

    @Transactional
    public int removeRentContract(Long id) {
        int rows = rentContractRepository.deleteRentContract(id);
        return rows;
    }

    public RentContract getRentContract(Long id) {
        RentContract rentContract = rentContractRepository.getRentContract(id);

        return rentContract;
    }

    public int listRentContractCnt(Map<String, Object> params) {
        int rows = rentContractRepository.listRentContractCnt(params);
        return rows;
    }

    public List<RentContract> listRentContract(Map<String, Object> params) {
        List<RentContract> lists = rentContractRepository.listRentContract(params);

        return lists;
    }

    public List<RentContract> listRentContractByIds(List<Long> ids, Map<String, Object> params) {
        params.put("ids", ids);
        QueryTool.setDefaultOrderBy(new OrderBy("DEPT_ID", ids));
        QueryTool.setDefaultOrderBy(new OrderBy("R_ID", ids));
        List<RentContract> lists = rentContractRepository.listRentContract(params);

        return lists;
    }

    //endregion

}
