/*
 * Source code generated by UnvUS.
 * Copyright(c) 2017 unvus.com All rights reserved.
 * Template skrull-pack-mybatis:src/main/java/service/Service.e.vm.java
 * Template is part of project: https://git.unvus.com/unvus/opensource/pack-unvus-mybatis
 */
package com.neofect.gts.core.services.rent.service;

import java.util.List;
import java.util.Map;

import org.springframework.stereotype.Service;
import org.springframework.transaction.annotation.Transactional;

import com.neofect.gts.core.services.rent.domain.RentReqMain;
import com.neofect.gts.core.services.rent.repository.RentReqMainRepository;
import com.unvus.config.mybatis.pagination.OrderBy;
import com.unvus.query.QueryTool;

/**
 * Service for {@link RentReqMain}<br/>
 */
@Service
public class RentReqMainService {

    private final RentReqMainRepository rentReqMainRepository;

    public RentReqMainService(RentReqMainRepository rentReqMainRepository) {
        this.rentReqMainRepository = rentReqMainRepository;
    }

    //region ------------------------------------------------------------------------------------------------ rentReqMain CRUD

    @Transactional
    public RentReqMain saveRentReqMain(RentReqMain rentReqMain) {
        // if (rentReqMain.getId() == null) {
        //     addRentReqMain(rentReqMain);
        // } else {
        //     modifyRentReqMain(rentReqMain);
        // }

        return rentReqMain;
    }

    private int addRentReqMain(RentReqMain rentReqMain) {
        int result = rentReqMainRepository.insertRentReqMain(rentReqMain);
        return result;
    }

    private int modifyRentReqMain(RentReqMain rentReqMain) {
        int result = rentReqMainRepository.updateRentReqMain(rentReqMain);
        return result;
    }

    @Transactional
    public int removeRentReqMain(Long id) {
        int rows = rentReqMainRepository.deleteRentReqMain(id);
        return rows;
    }

    public RentReqMain getRentReqMain(Long id) {
        RentReqMain rentReqMain = rentReqMainRepository.getRentReqMain(id);

        return rentReqMain;
    }

    public int listRentReqMainCnt(Map<String, Object> params) {
        int rows = rentReqMainRepository.listRentReqMainCnt(params);
        return rows;
    }

    public List<RentReqMain> listRentReqMain(Map<String, Object> params) {
        List<RentReqMain> lists = rentReqMainRepository.listRentReqMain(params);

        return lists;
    }

    public List<RentReqMain> listRentReqMainByIds(List<Long> ids, Map<String, Object> params) {
        params.put("ids", ids);
        QueryTool.setDefaultOrderBy(new OrderBy("DEPT_ID", ids));
        QueryTool.setDefaultOrderBy(new OrderBy("ENTER_DATE", ids));
        QueryTool.setDefaultOrderBy(new OrderBy("ENTER_SEQ", ids));
        List<RentReqMain> lists = rentReqMainRepository.listRentReqMain(params);

        return lists;
    }

    //endregion

}
