/*
 * Source code generated by UnvUS.
 * Copyright(c) 2017 unvus.com All rights reserved.
 * Template skrull-pack-mybatis:src/main/java/repository/Repository.e.vm.java
 * Template is part of project: https://git.unvus.com/unvus/opensource/pack-unvus-mybatis
 */
package com.neofect.gts.core.services.form.repository;

import java.util.List;
import java.util.Map;

import org.springframework.stereotype.Repository;

import com.neofect.gts.core.services.form.domain.FormContractPlan;
import com.unvus.config.mybatis.pagination.Pageable;
import com.unvus.config.mybatis.support.DefaultMapper;

/**
 * Repository for {@link FormContractPlan}<br/>
 * Available methods are.. <br/>
 * <ul>
 * <li>FormContractPlan getFormContractPlan(Long id);</li>
 * <li>int listFormContractPlanCnt(Map<String, Object> params);</li>
 * <li>List<FormContractPlan> listFormContractPlan(Map<String, Object> params);</li>
 * <li>int insertFormContractPlan(FormContractPlan formcontractplan);</li>
 * <li>int updateFormContractPlan(FormContractPlan formcontractplan);</li>
 * <li>int deleteFormContractPlan(Long id);</li>
 * </ul>
 */
@DefaultMapper
@Repository
public interface FormContractPlanRepository extends FormContractPlanRepository_ {
    FormContractPlan getFormContractPlan(Long id);

    int listFormContractPlanCnt(Map<String, Object> params);

    /**
     * if yuou want to avoid result objects less than dataPerPage caused by "1:N mappings".. <br/>
     * add function that return "distinct id list" and name it with : <br/>
     * <code>List<Long> listFormContractPlanIds(Map<String, Object> params)</code> <br/>
     * and replace @Pageable with :  <br/>
     * <code>@Pageable(useMergeQuery = true)</code> <br/>
     */
    @Pageable
    List<FormContractPlan> listFormContractPlan(Map<String, Object> params);

    List<Long> listFormContractPlanIds(Map<String, Object> params);

}
