/*
 * Source code generated by UnvUS.
 * Copyright(c) 2017 unvus.com All rights reserved.
 * Template skrull-pack-mybatis:src/main/java/repository/Repository.e.vm.java
 * Template is part of project: https://git.unvus.com/unvus/opensource/pack-unvus-mybatis
 */
package com.neofect.gts.core.services.form.repository;

import java.util.List;
import java.util.Map;

import org.springframework.stereotype.Repository;

import com.neofect.gts.core.services.form.domain.FormContractText;
import com.unvus.config.mybatis.pagination.Pageable;
import com.unvus.config.mybatis.support.DefaultMapper;

/**
 * Repository for {@link FormContractText}<br/>
 * Available methods are.. <br/>
 * <ul>
 * <li>FormContractText getFormContractText(Long id);</li>
 * <li>int listFormContractTextCnt(Map<String, Object> params);</li>
 * <li>List<FormContractText> listFormContractText(Map<String, Object> params);</li>
 * <li>int insertFormContractText(FormContractText formcontracttext);</li>
 * <li>int updateFormContractText(FormContractText formcontracttext);</li>
 * <li>int deleteFormContractText(Long id);</li>
 * </ul>
 */
@DefaultMapper
@Repository
public interface FormContractTextRepository extends FormContractTextRepository_ {
    FormContractText getFormContractText(Long id);

    int listFormContractTextCnt(Map<String, Object> params);

    /**
     * if yuou want to avoid result objects less than dataPerPage caused by "1:N mappings".. <br/>
     * add function that return "distinct id list" and name it with : <br/>
     * <code>List<Long> listFormContractTextIds(Map<String, Object> params)</code> <br/>
     * and replace @Pageable with :  <br/>
     * <code>@Pageable(useMergeQuery = true)</code> <br/>
     */
    @Pageable
    List<FormContractText> listFormContractText(Map<String, Object> params);

    List<Long> listFormContractTextIds(Map<String, Object> params);

}
