/*
 * Source code generated by UnvUS.
 * Copyright(c) 2017 unvus.com All rights reserved.
 * Template skrull-pack-mybatis:src/main/java/repository/Repository.e.vm.java
 * Template is part of project: https://git.unvus.com/unvus/opensource/pack-unvus-mybatis
 */
package com.neofect.gts.core.services.zp.repository;

import java.util.List;
import java.util.Map;

import org.springframework.stereotype.Repository;

import com.neofect.gts.core.services.zp.domain.ZDwoconfig;
import com.unvus.config.mybatis.pagination.Pageable;
import com.unvus.config.mybatis.support.DefaultMapper;

/**
 * Repository for {@link ZDwoconfig}<br/>
 * Available methods are.. <br/>
 * <ul>
 * <li>ZDwoconfig getZDwoconfig(Long id);</li>
 * <li>int listZDwoconfigCnt(Map<String, Object> params);</li>
 * <li>List<ZDwoconfig> listZDwoconfig(Map<String, Object> params);</li>
 * <li>int insertZDwoconfig(ZDwoconfig zdwoconfig);</li>
 * <li>int updateZDwoconfig(ZDwoconfig zdwoconfig);</li>
 * <li>int deleteZDwoconfig(Long id);</li>
 * </ul>
 */
@DefaultMapper
@Repository
public interface ZDwoconfigRepository extends ZDwoconfigRepository_ {
    ZDwoconfig getZDwoconfig(Long id);

    int listZDwoconfigCnt(Map<String, Object> params);

    /**
     * if yuou want to avoid result objects less than dataPerPage caused by "1:N mappings".. <br/>
     * add function that return "distinct id list" and name it with : <br/>
     * <code>List<Long> listZDwoconfigIds(Map<String, Object> params)</code> <br/>
     * and replace @Pageable with :  <br/>
     * <code>@Pageable(useMergeQuery = true)</code> <br/>
     */
    @Pageable
    List<ZDwoconfig> listZDwoconfig(Map<String, Object> params);

    List<Long> listZDwoconfigIds(Map<String, Object> params);

}
